from __future__ import annotations

"""Example mod: registers a simple exportable effect.

Preview + Arduino export parity is required by core registry.
"""

from typing import List, Tuple

from app.mod_api import register_effect

RGB = Tuple[int, int, int]


def preview_emit(*, num_leds: int, params: dict, t: float, **_kwargs) -> List[RGB]:
    import math
    speed = float(params.get('speed', 1.0) or 1.0)
    out: List[RGB] = []
    for i in range(int(num_leds)):
        x = (i / max(1, num_leds)) * 2.0 * math.pi
        v = 0.5 + 0.5 * math.sin(x + t * speed)
        c = int(255 * v)
        out.append((c, 0, 255 - c))
    return out


def arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout.get('num_leds', 60))
    pin = int(layout.get('led_pin', 6))
    speed = float(params.get('speed', 1.0) or 1.0)
    return f"""// Generated by Modulo (Mod Example Wave)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(128);
}}

void loop() {{
  float t = millis() / 1000.0f;
  for (int i = 0; i < NUM_LEDS; i++) {{
    float x = (float)i / (float)max(1, NUM_LEDS) * 6.2831853f;
    float v = 0.5f + 0.5f * sinf(x + t * {speed}f);
    uint8_t c = (uint8_t)(255.0f * v);
    leds[i] = CRGB(c, 0, 255 - c);
  }}
  FastLED.show();
  delay(16);
}}
"""


register_effect(
    "mod_example_wave",
    preview_emit=preview_emit,
    arduino_emit=arduino_emit,
    title="(Mod) Example Wave",
    capabilities={
        "description": "Example mod wave (exportable)",
        "targets": ["strip"],
        "export": "exportable"
    },
)
