from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Tuple

from export.arduino_exporter_validation import ExportValidationError

def make_solid_sketch(*, num_leds: int, led_pin: int, rgb: Tuple[int,int,int]) -> str:
    r,g,b = (int(rgb[0])&255, int(rgb[1])&255, int(rgb[2])&255)
    sketch = """/ Generated by Modulo
#include <FastLED.h>
#include <string.h>

// Debug option: print purpose channels over Serial
#define DBG_PURPOSE_SERIAL {1 if DBG_PURPOSE else 0}
#define DBG_SERIAL_BAUD {DBG_BAUD}

#define NUM_LEDS {num_leds}
// Wiring / LED config (filled by export target; defaults come from Export tab)
#define LED_PIN @@DATA_PIN@@
#define LED_TYPE @@LED_TYPE@@
#define COLOR_ORDER @@COLOR_ORDER@@
#define LED_BRIGHTNESS @@LED_BRIGHTNESS@@
CRGB leds[NUM_LEDS];

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{

  // --- Fixed-step updates for stateful behaviors (deterministic) ---
  if (__last_ms == 0) __last_ms = now;
  unsigned long __elapsed_ms = now - __last_ms;
  __last_ms = now;
  __accum_s += (float)__elapsed_ms / 1000.0f;

  int __steps = 0;
  while (__accum_s >= __FIXED_DT && __steps < 4) {
    __accum_s -= __FIXED_DT;
    __steps++;

    for (int li=0; li<LAYERS; li++) {
      float br, sp, wd, so, dn, dir;
      float pf0=0.0f, pf1=0.0f, pf2=0.0f, pf3=0.0f;
      float pi0=0.0f, pi1=0.0f, pi2=0.0f, pi3=0.0f;
      computeLayerParams(li, t, br, sp, wd, so, dn, dir, pf0, pf1, pf2, pf3, pi0, pi1, pi2, pi3);

      uint8_t beh = L_BEH[li];
      if (beh == 9) updateBreakout(li, __FIXED_DT, sp, wd, so, dn, pf0);
      else if (beh == 10) updateAsteroids(li, __FIXED_DT, sp, so, dn, pf0, pf1, pi0);
      else if (beh == 14) updateSnakeLite(li, __FIXED_DT, sp, pf0, pf1, pi0);
      else if (beh == 15) updateInvadersLite(li, __FIXED_DT, sp, pf0, pf1, pi0);
      else if (beh == 16) updateShooterLite(li, __FIXED_DT, sp, pf0, pf1, pi0);
      else if (beh == 17) updateBlocksBallLite(li, __FIXED_DT, sp, pf0, pf1, pi0);
      else if (beh == 19) updatePredatorPrey(li, __FIXED_DT, sp, pf0, pf1, pi0);
      else if (beh == 20) updateMemoryHeatmap(li, __FIXED_DT, sp, pf0, pf1, pi0);
    }
  }

  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = CRGB({r},{g},{b});
  }}
  FastLED.show();
  delay(10);
}}

"""
    sketch = sketch.replace("{1 if DBG_PURPOSE else 0}", str(1 if DBG_PURPOSE else 0))
    sketch = sketch.replace("{CA_MODULE_DECLS}", str(ca_module_decls))
    sketch = sketch.replace("{CA_MODULE_DISPATCH}", str(ca_module_dispatch))
    sketch = sketch.replace("{DBG_BAUD}", str(DBG_BAUD))
    sketch = sketch.replace("{num_leds}", str(num_leds))
    sketch = sketch.replace("{int(num_leds)}", str(int(num_leds)))
    sketch = sketch.replace("{int(led_pin)}", str(int(led_pin)))
    # Expand generated blocks
    sketch = sketch.replace("{rules_decls}", str(rules_decls))
    sketch = sketch.replace("{rules_apply}", str(rules_apply))
    sketch = sketch.replace("{postfx_decls}", str(postfx_decls))
    sketch = sketch.replace("{postfx_apply}", str(postfx_apply))
    sketch = sketch.replace("{KERNEL_DSL_CASES}", str(kernel_cases))
    sketch = sketch.replace("{WRITE_LOOP_CASES}", str(write_loop_cases))
    return sketch

def _validate_layers_for_export(layers: List[Dict[str, Any]]):
    if not layers:
        raise ExportValidationError("No layers to export.")
    for i, L in enumerate(layers):
        if str(L.get("behavior","")) != "solid":
            raise ExportValidationError(f"Layer {i+1}: only 'solid' is exportable in Phase 3D.")
        # modulotors: we support at most one enabled brightness lfo_sine per layer
        mods = L.get("modulotors", []) or []
        enabled = [m for m in mods if m.get("enabled")]
        for m in enabled:
            if m.get("target") != "brightness":
                raise ExportValidationError(f"Layer {i+1}: only brightness modulotion is exportable in Phase 3D.")
            if m.get("source") != "lfo_sine":
                raise ExportValidationError(f"Layer {i+1}: only lfo_sine modulotion is exportable in Phase 3D.")
            if m.get("mode") not in ("add","mul","set"):
                raise ExportValidationError(f"Layer {i+1}: unsupported mode {m.get('mode')}.")

def make_solid_layers_sketch(*, num_leds: int, led_pin: int, layers: List[Dict[str, Any]]) -> str:
    """Export for multiple SOLID layers with opacity + optional LFO brightness modulotion.

    Notes:
    - In Phase 3D, only 'solid' layers are exportable.
    - Each layer may have 0..1 enabled brightness modulotor using lfo_sine.
    """
    _validate_layers_for_export(layers)

    # emit layer constants arrays
    max_layers = 8
    if len(layers) > max_layers:
        raise ExportValidationError(f"Too many layers for Phase 3D export (max {max_layers}).")

    def clamp01(x):
        try: x = float(x)
        except Exception: x = 0.0
        return 0.0 if x < 0 else (1.0 if x > 1.0 else x)

    # Prepare lists
    lr, lg, lb, lop, lbr, lblend = [], [], [], [], [], []
    ltgt_kind, ltgt_ref = [], []
    lfo_on, lfo_mode, lfo_amt, lfo_hz = [], [], [], []
    for _ord, li, L in resolved_layers:
        c = L.get("color",(255,0,0))
        r,g,b = int(c[0])&255, int(c[1])&255, int(c[2])&255
        br = clamp01(L.get("brightness", 1.0))
        op = clamp01(_layer_opacity)
        lr.append(r); lg.append(g); lb.append(b); lbr.append(br); lop.append(op)
        bm = str(_layer_blend_mode).lower().strip()
        bm_id = 0
        if bm == 'add': bm_id = 1
        elif bm == 'max': bm_id = 2
        elif bm == 'multiply': bm_id = 3
        elif bm == 'screen': bm_id = 4
        lblend.append(bm_id)
        tk = str(L.get('target_kind','all')).lower().strip()
        tid = 0
        if tk == 'group': tid = 1
        elif tk == 'zone': tid = 2
        ltgt_kind.append(tid)
        ltgt_ref.append(int(L.get('target_ref',0)))

        # find first enabled mod
        mods = L.get("modulotors", []) or []
        m = next((m for m in mods if m.get("enabled")), None)
        if m is None:
            lfo_on.append(0); lfo_mode.append(0); lfo_amt.append(0.0); lfo_hz.append(0.0)
        else:
            lfo_on.append(1)
            mode = str(m.get("mode","mul"))
            mode_id = 1 if mode=="add" else (2 if mode=="set" else 0)  # 0=mul,1=add,2=set
            lfo_mode.append(mode_id)
            lfo_amt.append(float(m.get("amount", 0.5)))
            lfo_hz.append(float(m.get("rate_hz", 0.5)))

    # Convert python floats to C literals
    def f(x): 
        return ("%.6ff" % float(x))
    lr_s = ",".join(str(x) for x in lr)
    lg_s = ",".join(str(x) for x in lg)
    lb_s = ",".join(str(x) for x in lb)
    lop_s = ",".join(f(x) for x in lop)
    lbr_s = ",".join(f(x) for x in lbr)
    lblend_s = ",".join(str(x) for x in lblend)
    ltgt_kind_s = ",".join(str(x) for x in ltgt_kind)
    ltgt_ref_s = ",".join(str(x) for x in ltgt_ref)
    lfo_on_s = ",".join(str(x) for x in lfo_on)
    lfo_mode_s = ",".join(str(x) for x in lfo_mode)
    lfo_amt_s = ",".join(f(x) for x in lfo_amt)
    lfo_hz_s = ",".join(f(x) for x in lfo_hz)

    nL = len(layers)

    return """/ Generated by Modulo (Phase 3D: Multi-layer Solid + LFO brightness)
#include <FastLED.h>
#include <string.h>

// Debug option: print purpose channels over Serial
#define DBG_PURPOSE_SERIAL {1 if DBG_PURPOSE else 0}
#define DBG_SERIAL_BAUD {DBG_BAUD}
#include <math.h>

#define NUM_LEDS {int(num_leds)}
#define LED_PIN {int(led_pin)}
#define LAYERS {nL}

CRGB leds[NUM_LEDS];

const uint8_t L_R[LAYERS] = {{{lr_s}}};
const uint8_t L_G[LAYERS] = {{{lg_s}}};
const uint8_t L_B[LAYERS] = {{{lb_s}}};
const float   L_OP[LAYERS] = {{{lop_s}}};
const float   L_BR[LAYERS] = {{{lbr_s}}};
const uint8_t L_BLEND[LAYERS] = {{{lblend_s}}}; // 0=over,1=add,2=max,3=multiply,4=screen
const uint8_t L_TGT_KIND[LAYERS] = {{{ltgt_kind_s}}}; // 0=all,1=group,2=zone
const int16_t L_TGT_REF[LAYERS] = {{{ltgt_ref_s}}};

// Groups/Zones payload (may be empty)
const uint16_t GROUP_COUNT = @@GROUP_COUNT@@;
const uint16_t ZONE_COUNT  = @@ZONE_COUNT@@;
const uint16_t GROUP_OFFS[GROUP_COUNT] = @@GROUP_OFFS@@;
const uint16_t GROUP_LENS[GROUP_COUNT] = @@GROUP_LENS@@;
const uint16_t GROUP_INDEXES[@@GROUP_INDEXES_LEN@@] = @@GROUP_INDEXES@@;
const int16_t  ZONE_START[ZONE_COUNT] = @@ZONE_START@@;
const int16_t  ZONE_END[ZONE_COUNT]   = @@ZONE_END@@;

// LFO brightness modulotion per layer (optional)
const uint8_t LFO_ON[LAYERS] = {{{lfo_on_s}}};   // 0/1
const uint8_t LFO_MODE[LAYERS] = {{{lfo_mode_s}}}; // 0=mul,1=add,2=set
const float   LFO_AMT[LAYERS] = {{{lfo_amt_s}}};
const float   LFO_HZ[LAYERS] = {{{lfo_hz_s}}};

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float applyMode(float base, float sig, uint8_t mode, float amt) {{
  if (mode == 1) return base + sig * amt;       // add
  if (mode == 2) return sig * amt;             // set
  return base * (1.0f + sig * amt);            // mul
}}

void setup() {{
  if (DBG_PURPOSE_SERIAL) {{
    Serial.begin(DBG_SERIAL_BAUD);
    delay(10);
  }}
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  // time in seconds
  float t = (float)millis() / 1000.0f;

  // Compute final composite color once (solid layers)
  float outR = 0.0f, outG = 0.0f, outB = 0.0f;

  for (int li = 0; li < LAYERS; li++) {{
    float br = L_BR[li];

    if (LFO_ON[li]) {{
      float sig = sinf(2.0f * 3.1415926f * LFO_HZ[li] * t); // [-1..1]
      br = applyMode(br, sig, LFO_MODE[li], LFO_AMT[li]);
    }}
    br = clamp01(br);

    float layerR = ((float)L_R[li]) * br;
    float layerG = ((float)L_G[li]) * br;
    float layerB = ((float)L_B[li]) * br;

    float op = clamp01(L_OP[li]);

    float blendedR = blendChan(outR, layerR, L_BLEND[li]);
    float blendedG = blendChan(outG, layerG, L_BLEND[li]);
    float blendedB = blendChan(outB, layerB, L_BLEND[li]);

    outR = outR * (1.0f - op) + blendedR * op;
    outG = outG * (1.0f - op) + blendedG * op;
    outB = outB * (1.0f - op) + blendedB * op;
  }}

  uint8_t r = (uint8_t)constrain((int)(outR + 0.5f), 0, 255);
  uint8_t g = (uint8_t)constrain((int)(outG + 0.5f), 0, 255);
  uint8_t b = (uint8_t)constrain((int)(outB + 0.5f), 0, 255);

  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = CRGB(r,g,b);
  }}
  FastLED.show();
  delay(10);
}}

"""

def apply_audio_export_config(sketch: str, cfg: dict) -> str:
    if not isinstance(cfg, dict):
        return sketch
    use = bool(cfg.get("use_spectrum_shield", True))
    reset = cfg.get("reset_pin", 5)
    strobe = cfg.get("strobe_pin", 4)
    left = cfg.get("left_pin", "A0")
    right = cfg.get("right_pin", "A1")

    def _rep(pattern: str, repl: str) -> str:
        return re.sub(pattern, repl, sketch)

    sketch = _rep(r"#define\s+MODULA_USE_SPECTRUM_SHIELD\s+\d+", f"#define MODULA_USE_SPECTRUM_SHIELD {1 if use else 0}")
    sketch = _rep(r"#define\s+MSGEQ7_RESET_PIN\s+\S+", f"#define MSGEQ7_RESET_PIN {int(reset)}")
    sketch = _rep(r"#define\s+MSGEQ7_STROBE_PIN\s+\S+", f"#define MSGEQ7_STROBE_PIN {int(strobe)}")
    sketch = _rep(r"#define\s+MSGEQ7_LEFT_PIN\s+\S+", f"#define MSGEQ7_LEFT_PIN {left}")
    sketch = _rep(r"#define\s+MSGEQ7_RIGHT_PIN\s+\S+", f"#define MSGEQ7_RIGHT_PIN {right}")
    return sketch

def make_external_audio_streamer_sketch(export_audio_cfg: dict) -> str:
    """Generate an Arduino sketch that streams Spectrum Shield/MSGEQ7 audio to Modulo via Serial."""
    cfg = dict(export_audio_cfg or {})
    reset_pin = int(cfg.get("reset_pin", 5))
    strobe_pin = int(cfg.get("strobe_pin", 4))
    left_pin = str(cfg.get("left_pin", "A0"))
    right_pin = str(cfg.get("right_pin", "A1"))

    tpl_path = Path(__file__).resolve().parent / "arduino_external_audio_streamer.ino.tpl"
    tpl = tpl_path.read_text(encoding="utf-8")

    out = tpl.replace("@@MSGEQ7_RESET_PIN@@", str(reset_pin))              .replace("@@MSGEQ7_STROBE_PIN@@", str(strobe_pin))              .replace("@@MSGEQ7_LEFT_PIN@@", left_pin)              .replace("@@MSGEQ7_RIGHT_PIN@@", right_pin)

    # Validate no unreplaced tokens remain
    validate_export_text(out)
    return out

