from __future__ import annotations

from export.arduino_exporter_blocks import EXPORT_MARKER
from export.arduino_exporter_layerstack_support import csv_values


TEMPLATE = r'''/ Generated by Modulo (Layer Stack)
// Export build: {EXPORT_MARKER}

// Debug option: print purpose channels over Serial
#define DBG_PURPOSE_SERIAL {1 if DBG_PURPOSE else 0}
#define DBG_SERIAL_BAUD {DBG_BAUD}

#include <math.h>

#define NUM_LEDS {num_leds}
#define LED_PIN {led_pin}

// LED backend implementation (filled by export target)
@@LED_IMPL@@

{postfx_decls}

#define LAYERS @@LAYER_COUNT@@

const uint8_t L_BEH[LAYERS]   = {{{csv_values(L_BEH)}}};  // 0=solid,1=chase,2=wipe,3=sparkle,4=scanner,5=fade,6=strobe,7=rainbow,8=bouncer
const uint8_t L_R[LAYERS]     = {{{csv_values(LR)}}};
const uint8_t L_G[LAYERS]     = {{{csv_values(LG)}}};
const uint8_t L_B[LAYERS]     = {{{csv_values(LB)}}};

const uint8_t L_R2[LAYERS]    = {{{csv_values(L_R2)}}};
const uint8_t L_G2[LAYERS]    = {{{csv_values(L_G2)}}};
const uint8_t L_B2[LAYERS]    = {{{csv_values(L_B2)}}};

const float   L_DUTY[LAYERS]  = {{{csv_values(L_DUTY)}}};
const uint8_t L_HUEOFF[LAYERS]= {{{csv_values(L_HUEOFF)}}};
const float   L_HUESPAN[LAYERS]= {{{csv_values(L_HUESPAN)}}};

const float   L_BR[LAYERS]    = {{{csv_values(L_BR)}}};
	// Runtime overrides (Rules can override a small deterministic subset)
	static float  L_BR_RT[LAYERS];
	static bool   L_BR_SET[LAYERS];
const float   L_SP[LAYERS]    = {{{csv_values(L_SP)}}};
const float   L_WD[LAYERS]    = {{{csv_values(L_WD)}}};
const float   L_SO[LAYERS]    = {{{csv_values(L_SO)}}};
const float   L_DN[LAYERS]    = {{{csv_values(L_DN)}}};
const float   L_DIR[LAYERS]   = {{{csv_values(L_DIR)}}};

// Extra per-layer params (export defaults)
const float   L_PF0[LAYERS]   = {{{csv_values(L_PF0)}}};
const float   L_PF1[LAYERS]   = {{{csv_values(L_PF1)}}};
const float   L_PF2[LAYERS]   = {{{csv_values(L_PF2)}}};
const float   L_PF3[LAYERS]   = {{{csv_values(L_PF3)}}};
const int16_t L_PI0[LAYERS]   = {{{csv_values(L_PI0)}}};
const int16_t L_PI1[LAYERS]   = {{{csv_values(L_PI1)}}};
const int16_t L_PI2[LAYERS]   = {{{csv_values(L_PI2)}}};
const int16_t L_PI3[LAYERS]   = {{{csv_values(L_PI3)}}};

// Back-compat aliases for preview-only/game emitters
#define L_RBG L_R
#define L_GBG L_G
#define L_BBG L_B

// Purpose channels (signal bus; currently defaulted)
float purpose_f0 = 0.0f, purpose_f1 = 0.0f, purpose_f2 = 0.0f, purpose_f3 = 0.0f;
int16_t purpose_i0 = 0, purpose_i1 = 0, purpose_i2 = 0, purpose_i3 = 0;

{rules_decls}

// Modulotion runtime tables (defaults)
#ifndef MODS_PER_LAYER
#define MODS_PER_LAYER 4
#endif
#ifndef MODS_TOTAL
#define MODS_TOTAL (LAYERS * MODS_PER_LAYER)
#endif
float   M_PHASE[MODS_TOTAL] = {{0}};
uint8_t M_CURVE[MODS_TOTAL] = {{0}};

// Layer state tables for stateful effects (defaults)
#ifndef ST_F_SLOTS
#define ST_F_SLOTS 16
#endif
#ifndef ST_I_SLOTS
#define ST_I_SLOTS 16
#endif
uint8_t ST_INIT[LAYERS] = {{0}};
// C++ aggregate init: "{0}" zeros the whole table (including 2D arrays)
float   ST_F[LAYERS][ST_F_SLOTS] = {{0}};
int16_t ST_I[LAYERS][ST_I_SLOTS] = {{0}};
static inline void state_reset_layer(int li) {{
  ST_INIT[li] = 1;
  for (int k=0;k<ST_F_SLOTS;k++) ST_F[li][k] = 0.0f;
  for (int k=0;k<ST_I_SLOTS;k++) ST_I[li][k] = 0;
}}

const float   L_OP[LAYERS]    = {{{csv_values(L_OP)}}};
// Runtime overrides (Rules can override a small deterministic subset)
static float  L_OP_RT[LAYERS];
static bool   L_OP_SET[LAYERS];
const uint8_t L_BLEND[LAYERS] = {{{csv_values(L_BLEND)}}}; // 0=over,1=add,2=max,3=multiply,4=screen
const uint8_t L_TGT_KIND[LAYERS] = {{{csv_values(L_TK)}}};  // 0=all,1=group,2=zone
const int16_t L_TGT_REF[LAYERS]  = {{{csv_values(L_TR)}}};

// Operators (per-layer, pre-blend). Deterministic subset:
// 0=none,1=gain,2=gamma,3=posterize
#define OPS_PER_LAYER {OPS_PER_LAYER}
const uint8_t OP_KIND[LAYERS*OPS_PER_LAYER] = {{{csv_values(OP_KIND)}}};
const float   OP_P0[LAYERS*OPS_PER_LAYER]   = {{{csv_values(OP_P0)}}};
// Runtime overrides (Rules can override operator.gain deterministically)
static float  OP_P0_RT[LAYERS*OPS_PER_LAYER];
static bool   OP_P0_SET[LAYERS*OPS_PER_LAYER];

// Modulotors (flattened: LAYERS*2 entries)
#define MODS_PER_LAYER {MODS_PER_LAYER}
const uint8_t M_SRC[LAYERS*MODS_PER_LAYER]  = {{{csv_values(M_SRC)}}};   // 0 none, 1 lfo_sine, audio placeholders 10+
const uint8_t M_TGT[LAYERS*MODS_PER_LAYER]  = {{{csv_values(M_TGT)}}};   // 0 br,1 sp,2 wd,3 so,4 dn,5 dir
const uint8_t M_MODE[LAYERS*MODS_PER_LAYER] = {{{csv_values(M_MODE)}}};  // 0 mul,1 add,2 set
const float   M_AMT[LAYERS*MODS_PER_LAYER]  = {{{csv_values(M_AMT)}}};
const float   M_RATE[LAYERS*MODS_PER_LAYER] = {{{csv_values(M_RATE)}}};
const float   M_BIAS[LAYERS*MODS_PER_LAYER] = {{{csv_values(M_BIAS)}}};
const float   M_SMOOTH[LAYERS*MODS_PER_LAYER]= {{{csv_values(M_SMOOTH)}}};
float         M_LAST[LAYERS*MODS_PER_LAYER] = {{0}};

// Groups/Zones payload
const uint16_t GROUP_COUNT = {max(0, len(groups))};
const uint16_t ZONE_COUNT  = {max(0, len(zones))};
const uint16_t GROUP_OFFS[ (GROUP_COUNT>0)?GROUP_COUNT:1 ] = {{{csv_values(group_offs if len(groups)>0 else [0])}}};
const uint16_t GROUP_LENS[ (GROUP_COUNT>0)?GROUP_COUNT:1 ] = {{{csv_values(group_lens if len(groups)>0 else [0])}}};
const uint16_t GROUP_INDEXES[@@GROUP_INDEXES_LEN@@] = {{{csv_values(group_indexes)}}};
const int16_t  ZONE_START[ (ZONE_COUNT>0)?ZONE_COUNT:1 ] = {{{csv_values(zone_start if len(zones)>0 else [0])}}};
const int16_t  ZONE_END[   (ZONE_COUNT>0)?ZONE_COUNT:1 ] = {{{csv_values(zone_end if len(zones)>0 else [0])}}};

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float clamp255(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 255.0f) return 255.0f;
  return x;
}}

// Operators runtime (per-layer, pre-blend)
static inline void apply_one_operator(uint8_t kind, float p0, float &r, float &g, float &b) {{
  if (kind == 1) {{ // gain
    float k = fmaxf(0.0f, p0);
    r = clamp255(r * k);
    g = clamp255(g * k);
    b = clamp255(b * k);
    return;
  }}
  if (kind == 2) {{ // gamma
    float gamma = fmaxf(0.001f, p0);
    float inv = 1.0f / gamma;
    r = powf(clamp01(r/255.0f), inv) * 255.0f;
    g = powf(clamp01(g/255.0f), inv) * 255.0f;
    b = powf(clamp01(b/255.0f), inv) * 255.0f;
    r = clamp255(r); g = clamp255(g); b = clamp255(b);
    return;
  }}
  if (kind == 3) {{ // posterize
    int levels = (int)roundf(p0);
    if (levels < 2) levels = 2;
    if (levels > 64) levels = 64;
    float step = 255.0f / (float)(levels - 1);
    r = clamp255(roundf(r / step) * step);
    g = clamp255(roundf(g / step) * step);
    b = clamp255(roundf(b / step) * step);
    return;
  }}
}}

static inline void apply_layer_operators(int li, float &r, float &g, float &b) {{
  int base = li * OPS_PER_LAYER;
  for (int oi=0; oi<OPS_PER_LAYER; oi++) {{
    uint8_t k = OP_KIND[base + oi];
    if (k == 0) continue;
    float p0 = OP_P0_RT[base + oi];
    apply_one_operator(k, p0, r, g, b);
  }}
}}

static inline float applyMode(float base, float sig, uint8_t mode, float amt) {{
  if (mode == 1) return base + sig * amt;       // add
  if (mode == 2) return sig * amt;             // set
  return base * (1.0f + sig * amt);            // mul
}}

static inline float blendChan(float outC, float layerC, uint8_t mode) {{
  if (mode == 1) {{ // add
    float v = outC + layerC;
    return (v > 255.0f) ? 255.0f : v;
  }}
  if (mode == 2) {{ // max
    return (outC > layerC) ? outC : layerC;
  }}
  if (mode == 3) {{ // multiply
    return (outC * layerC) / 255.0f;
  }}
  if (mode == 4) {{ // screen
    return 255.0f - ((255.0f - outC) * (255.0f - layerC)) / 255.0f;
  }}
  return layerC; // over
}}

static inline bool targetContains(uint16_t idx, uint8_t kind, int16_t ref) {{
  if (kind == 0) return true;
  if (kind == 2) {{
    if (ref < 0 || ref >= (int16_t)ZONE_COUNT) return true;
    int16_t a = ZONE_START[ref];
    int16_t b = ZONE_END[ref];
    if (a > b) {{ int16_t t=a; a=b; b=t; }}
    return (idx >= (uint16_t)a) && (idx <= (uint16_t)b);
  }}
  if (kind == 1) {{
    if (ref < 0 || ref >= (int16_t)GROUP_COUNT) return true;
    uint16_t off = GROUP_OFFS[ref];
    uint16_t len = GROUP_LENS[ref];
    for (uint16_t j=0; j<len; j++) {{
      if (GROUP_INDEXES[off + j] == idx) return true;
    }}
    return false;
  }}
  return true;
}}

// Simple RNG for sparkle (deterministic-ish)
static uint32_t rng_state = 0x12345678u;
static inline uint32_t xorshift32() {{
  uint32_t x = rng_state;
  x ^= x << 13;
  x ^= x >> 17;
  x ^= x << 5;
  rng_state = x;
  return x;
}}

static inline float lfo_sine(float t, float hz) {{
  return sinf(6.2831853f * hz * t);
}}

// Compute per-layer params with modulotors
static inline void computeLayerParams(int li, float t, float &br, float &sp, float &wd, float &so, float &dn, float &dir, float &pf0, float &pf1, float &pf2, float &pf3, float &pi0, float &pi1, float &pi2, float &pi3) {{
	  br = L_BR_RT[li]; sp = L_SP[li]; wd = L_WD[li]; so = L_SO[li]; dn = L_DN[li]; dir = L_DIR[li];
  pf0 = L_PF0[li]; pf1 = L_PF1[li]; pf2 = L_PF2[li]; pf3 = L_PF3[li];
  // ints normalized to 0..1 via soft range [-1000..1000]
  pi0 = clamp01(((float)L_PI0[li] + 1000.0f) / 2000.0f);
  pi1 = clamp01(((float)L_PI1[li] + 1000.0f) / 2000.0f);
  pi2 = clamp01(((float)L_PI2[li] + 1000.0f) / 2000.0f);
  pi3 = clamp01(((float)L_PI3[li] + 1000.0f) / 2000.0f);

  for (int mi=0; mi<MODS_PER_LAYER; mi++) {{
    int idx = li*MODS_PER_LAYER + mi;
    uint8_t src = M_SRC[idx];
    uint8_t tgt = M_TGT[idx];
    uint8_t mode = M_MODE[idx];
    float amt = M_AMT[idx];
    float rate = M_RATE[idx];
    float bias = M_BIAS[idx];
    float smooth = M_SMOOTH[idx];

    float sig = 0.0f;
    if (src == 0) {{ sig = 0.0f; }}
    else if (src == 1) {{ // lfo_sine
      sig = sinf(6.2831853f * (rate * t + M_PHASE[idx])); // [-1..1]
    }}
    else if (src == 10) {{ sig = (clamp01(g_energy) - 0.5f) * 2.0f; }}
    else if (src >= 11 && src <= 17) {{ sig = (clamp01(g_mono[src-11]) - 0.5f) * 2.0f; }}
    else if (src >= 21 && src <= 27) {{ sig = (clamp01((float)g_left[src-21] / 1023.0f) - 0.5f) * 2.0f; }}
    else if (src >= 31 && src <= 37) {{ sig = (clamp01((float)g_right[src-31] / 1023.0f) - 0.5f) * 2.0f; }}
    else if (src == 50) {{ sig = (clamp01(purpose_f0) - 0.5f) * 2.0f; }}
    else if (src == 51) {{ sig = (clamp01(purpose_f1) - 0.5f) * 2.0f; }}
    else if (src == 52) {{ sig = (clamp01(purpose_f2) - 0.5f) * 2.0f; }}
    else if (src == 53) {{ sig = (clamp01(purpose_f3) - 0.5f) * 2.0f; }}
    else if (src == 54) {{ sig = (clamp01((float)purpose_i0 * 0.001f) - 0.5f) * 2.0f; }}
    else if (src == 55) {{ sig = (clamp01((float)purpose_i1 * 0.001f) - 0.5f) * 2.0f; }}
    else if (src == 56) {{ sig = (clamp01((float)purpose_i2 * 0.001f) - 0.5f) * 2.0f; }}
    else if (src == 57) {{ sig = (clamp01((float)purpose_i3 * 0.001f) - 0.5f) * 2.0f; }}
    else {{ sig = 0.0f; }}

    // Convert to v in [0..1] for curve shaping, then back to [-1..1]
float v = 0.5f + 0.5f * sig;
uint8_t cv = M_CURVE[idx];
if (cv == 1) v = 1.0f - v;                 // invert
else if (cv == 2) v = fabsf((v - 0.5f) * 2.0f); // abs
else if (cv == 3) v = v * v;               // pow2
else if (cv == 4) v = v * v * v;           // pow3
sig = (v - 0.5f) * 2.0f; // back to [-1..1]

    if (smooth > 0.0f) {{
      float a = smooth;
      if (a < 0.0f) a = 0.0f;
      if (a > 0.999f) a = 0.999f;
      M_LAST[idx] = a * M_LAST[idx] + (1.0f - a) * sig;
      sig = M_LAST[idx];
    }}

    if (tgt == 0) br = clamp01(br + sig * amt + bias);
    else if (tgt == 1) sp = sp + sig * amt + bias;
    else if (tgt == 2) wd = clamp01(wd + sig * amt + bias);
    else if (tgt == 3) so = clamp01(so + sig * amt + bias);
    else if (tgt == 4) dn = clamp01(dn + sig * amt + bias);
    else if (tgt == 5) dir = applyMode(dir, sig, mode, amt);
  }}
}}

// Behavior evaluators: return layer RGB (0..255 floats) for LED i at time t.
static inline void evalSolid(int li, float br, float &r, float &g, float &b) {{
  r = (float)L_R[li] * br;
  g = (float)L_G[li] * br;
  b = (float)L_B[li] * br;
}}

static inline uint8_t clamp8(int v){{ if(v<0) return 0; if(v>255) return 255; return (uint8_t)v; }}

static inline void hsv2rgb(float h, float s, float v, float &r, float &g, float &b){{
  // h 0..1
  h = h - floorf(h);
  s = clamp01(s);
  v = clamp01(v);
  float hh = h * 6.0f;
  int i = (int)floorf(hh);
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f*s);
  float t = v * (1.0f - (1.0f - f)*s);
  i = i % 6;
  if(i==0){{ r=v; g=t; b=p; }}
  else if(i==1){{ r=q; g=v; b=p; }}
  else if(i==2){{ r=p; g=v; b=t; }}
  else if(i==3){{ r=p; g=q; b=v; }}
  else if(i==4){{ r=t; g=p; b=v; }}
  else {{ r=v; g=p; b=q; }}
  r*=255.0f; g*=255.0f; b*=255.0f;
}}

static inline void evalFade(int li, float t, float br, float sp, float &r, float &g, float &b) {{
  float alpha = 0.5f * (1.0f + sinf(t * fmaxf(0.0f, sp) * 6.2831853f));
  float r1 = (float)L_R[li], g1=(float)L_G[li], b1=(float)L_B[li];
  float r2 = (float)L_R2[li], g2=(float)L_G2[li], b2=(float)L_B2[li];
  r = (r1 + (r2-r1)*alpha) * br;
  g = (g1 + (g2-g1)*alpha) * br;
  b = (b1 + (b2-b1)*alpha) * br;
}}

static inline void evalStrobe(int li, float t, float br, float sp, float duty, float &r, float &g, float &b) {{
  float hz = fmaxf(0.0f, sp);
  float d = clamp01(duty);
  bool on = true;
  if(hz > 0.0001f){{
    float phase = fmodf(t * hz, 1.0f);
    on = (phase < d);
  }}
  if(!on){{ r=0; g=0; b=0; return; }}
  r = (float)L_R[li] * br;
  g = (float)L_G[li] * br;
  b = (float)L_B[li] * br;
}}

static inline void evalRainbow(int li, int i, float t, float br, float sp, uint8_t off, float span, float &r, float &g, float &b) {{
  float base = ((float)off / 255.0f) + t * fmaxf(0.0f, sp) * 0.15f;
  float h = base + ((float)i / fmaxf(1.0f, (float)(NUM_LEDS-1))) * span;
  float rr, gg, bb;
  hsv2rgb(h, 1.0f, 1.0f, rr, gg, bb);
  r = rr * br;
  g = gg * br;
  b = bb * br;
}}

static inline void evalChase(int li, int i, float t, float br, float sp, float wd, float dir, float &r, float &g, float &b) {{
  float phase = fmodf(t * fmaxf(0.0f, sp), 1.0f);
  float pos01 = (dir >= 0.0f) ? phase : (1.0f - phase);
  float pos = pos01 * (float)(NUM_LEDS - 1);
  float halfw = fmaxf(0.5f, wd * (float)NUM_LEDS * 0.5f);
  float d = fabsf((float)i - pos);
  float a = (d <= halfw) ? (1.0f - (d/halfw)) : 0.0f;
  r = (float)L_R[li] * br * a;
  g = (float)L_G[li] * br * a;
  b = (float)L_B[li] * br * a;
}}

// Phase 3.4: Kernel DSL (shader-like) — compiled per-layer at export time.
static inline float fractf_modulo(float v) { return v - floorf(v); }

static inline void evalKernelDSL(int li, int i, float t, float br, uint32_t seed_u32, float &r, float &g, float &b) {
  // Normalized coords.
#ifdef MATRIX_WIDTH
  // Kernel XY (mapping truth): applies serpentine/flip/rotate in MATRIX_* macros.
  int xi = (MATRIX_WIDTH > 0) ? (i % MATRIX_WIDTH) : 0;
  int yi = (MATRIX_WIDTH > 0) ? (i / MATRIX_WIDTH) : 0;

  // Serpentine: odd rows reversed in index→XY.
  #if defined(MATRIX_SERPENTINE) && (MATRIX_SERPENTINE)
    if ((yi & 1) != 0) { xi = (MATRIX_WIDTH - 1) - xi; }
  #endif

  // Flip
  #if defined(MATRIX_FLIP_X) && (MATRIX_FLIP_X)
    xi = (MATRIX_WIDTH - 1) - xi;
  #endif
  #if defined(MATRIX_FLIP_Y) && (MATRIX_FLIP_Y)
    yi = (MATRIX_HEIGHT - 1) - yi;
  #endif

  // Rotate (0/90/180/270)
  #if defined(MATRIX_ROTATE)
    #if (MATRIX_ROTATE == 90)
      { int _tx = xi; xi = (MATRIX_HEIGHT - 1) - yi; yi = _tx; }
    #elif (MATRIX_ROTATE == 180)
      xi = (MATRIX_WIDTH - 1) - xi;
      yi = (MATRIX_HEIGHT - 1) - yi;
    #elif (MATRIX_ROTATE == 270)
      { int _tx = xi; xi = yi; yi = (MATRIX_WIDTH - 1) - _tx; }
    #endif
  #endif

  const float x = (MATRIX_WIDTH <= 1) ? 0.0f : ((float)xi / (float)(MATRIX_WIDTH - 1));
  const float y = (MATRIX_HEIGHT <= 1) ? 0.0f : ((float)yi / (float)(MATRIX_HEIGHT - 1));
#else
  const float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
  const float y = 0.0f;
#endif
  const float seedf = (float)(seed_u32 & 0xFFFFu) * 0.001f;
  // Expose DSL variable name expected by the compiler.
  const float seed = seedf;
  float v = 0.0f;
  switch(li){
{KERNEL_DSL_CASES}
    default: v = 0.0f; break;
  }
  if (v < 0.0f) v = 0.0f; else if (v > 1.0f) v = 1.0f;
  r = (float)L_R[li] * br * v;
  g = (float)L_G[li] * br * v;
  b = (float)L_B[li] * br * v;
}

// Phase 3.6: Write-the-loop — per-layer injected C++ pixel body (advanced escape hatch).
// Exposes x,y,t,dt,seed,pf0..pf3,audio_energy and g_mono[0..6]; user body must set r,g,b (0..1 floats).
static inline void evalWriteLoop(int li, int i, float t, float dt, float br, uint32_t seed_u32, float pf0, float pf1, float pf2, float pf3, float &r, float &g, float &b) {
#ifdef MATRIX_WIDTH
  // Kernel XY (mapping truth): applies serpentine/flip/rotate in MATRIX_* macros.
  int xi = (MATRIX_WIDTH > 0) ? (i % MATRIX_WIDTH) : 0;
  int yi = (MATRIX_WIDTH > 0) ? (i / MATRIX_WIDTH) : 0;

  // Serpentine: odd rows reversed in index→XY.
  #if defined(MATRIX_SERPENTINE) && (MATRIX_SERPENTINE)
    if ((yi & 1) != 0) { xi = (MATRIX_WIDTH - 1) - xi; }
  #endif

  // Flip
  #if defined(MATRIX_FLIP_X) && (MATRIX_FLIP_X)
    xi = (MATRIX_WIDTH - 1) - xi;
  #endif
  #if defined(MATRIX_FLIP_Y) && (MATRIX_FLIP_Y)
    yi = (MATRIX_HEIGHT - 1) - yi;
  #endif

  // Rotate (0/90/180/270)
  #if defined(MATRIX_ROTATE)
    #if (MATRIX_ROTATE == 90)
      { int _tx = xi; xi = (MATRIX_HEIGHT - 1) - yi; yi = _tx; }
    #elif (MATRIX_ROTATE == 180)
      xi = (MATRIX_WIDTH - 1) - xi;
      yi = (MATRIX_HEIGHT - 1) - yi;
    #elif (MATRIX_ROTATE == 270)
      { int _tx = xi; xi = yi; yi = (MATRIX_WIDTH - 1) - _tx; }
    #endif
  #endif

  const float x = (MATRIX_WIDTH <= 1) ? 0.0f : ((float)xi / (float)(MATRIX_WIDTH - 1));
  const float y = (MATRIX_HEIGHT <= 1) ? 0.0f : ((float)yi / (float)(MATRIX_HEIGHT - 1));
#else
  const float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
  const float y = 0.0f;
#endif
  const float seed = (float)(seed_u32 & 0xFFFFu) * 0.001f;
  const float audio_energy = g_energy;
  r = 0.0f; g = 0.0f; b = 0.0f;
  switch(li){
{WRITE_LOOP_CASES}
    default: break;
  }
  if (r < 0.0f) r = 0.0f; else if (r > 1.0f) r = 1.0f;
  if (g < 0.0f) g = 0.0f; else if (g > 1.0f) g = 1.0f;
  if (b < 0.0f) b = 0.0f; else if (b > 1.0f) b = 1.0f;
  r *= br; g *= br; b *= br;
}

static inline uint8_t bit8(const uint8_t *rows, int x, int y){{
  if(x<0||y<0||x>7||y>7) return 0;
  uint8_t row = rows[y];
  return (row & (1 << (7-x))) ? 1 : 0;
}}

// Phase 2A: Tilemap+Sprite renderer (export path for tilemap_sprite / red_hat_runner / mariobros_clockface)
// Notes:
// - Uses pf0 as jump_now (Rules can set purpose_f0)
// - Uses speed for horizontal scroll
static inline void evalTilemapSprite(int li, int i, float t, float br, float sp, float pf0, float pf1, float &r, float &g, float &b){{
#ifndef MATRIX_WIDTH
  // Fallback for strip: simple moving dot
  float phase = fmodf(t * fmaxf(0.0f, sp), 1.0f);
  int pos = (int)floorf(phase * (float)(NUM_LEDS-1) + 0.5f);
  if(i==pos){{ r=(float)L_R[li]*br; g=(float)L_G[li]*br; b=(float)L_B[li]*br; }}
  else {{ r=0; g=0; b=0; }}
  return;
#else
  const int mw = (int)MATRIX_WIDTH;
  const int mh = (int)MATRIX_HEIGHT;
  int x = i % (mw>0?mw:1);
  int y = i / (mw>0?mw:1);

  // Variant id encoded in raw PI0 (set by exporter for tilemap/sprite showcase effects)
  const int variant = (int)L_PI0[li]; // 0=tilemap_sprite, 1=red_hat_runner, 2=mariobros_clockface

  // Default background: mario-ish sky + grass band + sprinkled bricks
  auto bg_default = [&](){{
    float skyR = 0.0f, skyG = 0.0f, skyB = 115.0f;
    float brickR = 230.0f, brickG = 89.0f, brickB = 16.0f;
    float grassR = 0.0f, grassG = 200.0f, grassB = 0.0f;

    bool is_grass = (y >= mh-8);
    bool is_brick = false;
    if(!is_grass){{
      if(y >= mh-24 && y < mh-16){{ if(((x/8) % 4) == 1) is_brick = true; }}
      if(y >= mh-40 && y < mh-32){{ if(((x/8) % 6) == 2) is_brick = true; }}
    }}

    if(is_grass){{ r = grassR * br; g = grassG * br; b = grassB * br; return; }}
    if(is_brick){{ r = brickR * br; g = brickG * br; b = brickB * br; return; }}
    r = skyR * br; g = skyG * br; b = skyB * br; return;
  }};

  // Variant 2: Mario clockface (deterministic millis-based clock)
  if(variant == 2){{
    bg_default();

    // Render mm:ss using a tiny 3x5 font, centered.
    int sec = (int)fmodf(t, 60.0f);
    int min = (int)fmodf(floorf(t/60.0f), 60.0f);
    int d0 = (min/10)%10, d1 = min%10, d2 = (sec/10)%10, d3 = sec%10;

    static const uint8_t DIG[10][5] = {{
      {{0b111,0b101,0b101,0b101,0b111}},
      {{0b010,0b110,0b010,0b010,0b111}},
      {{0b111,0b001,0b111,0b100,0b111}},
      {{0b111,0b001,0b111,0b001,0b111}},
      {{0b101,0b101,0b111,0b001,0b001}},
      {{0b111,0b100,0b111,0b001,0b111}},
      {{0b111,0b100,0b111,0b101,0b111}},
      {{0b111,0b001,0b010,0b010,0b010}},
      {{0b111,0b101,0b111,0b101,0b111}},
      {{0b111,0b101,0b111,0b001,0b111}},
    }};

    int sc = 1 + (int)floorf(clamp01(pf1) * 2.0f + 0.5f);
    if(sc<1) sc=1; if(sc>3) sc=3;

    int digitW = 3*sc;
    int digitH = 5*sc;
    int gap = 1*sc;
    int colonGap = 2*sc;
    int totalW = digitW*4 + gap*2 + colonGap;
    int x0 = (mw - totalW)/2;
    int y0 = 2;

    auto hit_digit = [&](int dx, int dy, int dig)->bool{{
      int rx = x - dx;
      int ry = y - dy;
      if(rx<0||ry<0||rx>=digitW||ry>=digitH) return false;
      int px = rx / sc;
      int py = ry / sc;
      uint8_t row = DIG[dig][py];
      bool on = ((row >> (2-px)) & 1) != 0;
      return on;
    }};

    bool hit = false;
    if(hit_digit(x0 + 0*(digitW+gap), y0, d0)) hit=true;
    if(hit_digit(x0 + 1*(digitW+gap), y0, d1)) hit=true;
    int colonX = x0 + 2*digitW + gap*2 + (colonGap/2);
    if(x>=colonX && x<colonX+sc){{
      if(y>=y0+1*sc && y<y0+2*sc) hit=true;
      if(y>=y0+3*sc && y<y0+4*sc) hit=true;
    }}
    int x2 = x0 + 2*digitW + gap*2 + colonGap;
    if(hit_digit(x2 + 0*(digitW+gap), y0, d2)) hit=true;
    if(hit_digit(x2 + 1*(digitW+gap), y0, d3)) hit=true;

    if(hit){{
      r = (float)L_R[li] * br;
      g = (float)L_G[li] * br;
      b = (float)L_B[li] * br;
    }}
    return;
  }}

  // Variant 1: Red Hat Runner
  if(variant == 1){{
    float skyR = 8.0f, skyG = 8.0f, skyB = 30.0f;
    float floorR = 70.0f, floorG = 70.0f, floorB = 70.0f;
    float pipeR = 10.0f, pipeG = 180.0f, pipeB = 40.0f;

    static const uint8_t SPRH[8] = {{
      0b00111100,
      0b01111110,
      0b11111111,
      0b01111110,
      0b00111100,
      0b00100100,
      0b01011010,
      0b10000001,
    }};

    float speed = fmaxf(0.0f, sp);
    int sx = (int)floorf(fmodf(t * speed * 12.0f, (float)(mw + 8)) - 8.0f);
    float jh = 4.0f + clamp01(pf1) * 14.0f;
    float jump = (pf0 > 0.5f) ? (fabsf(sinf(t * 6.2831853f)) * jh) : 0.0f;
    int sy = (mh - 14) - (int)floorf(jump + 0.5f);

    if(y >= mh-6){{ r = floorR * br; g = floorG * br; b = floorB * br; }}
    else {{ r = skyR * br; g = skyG * br; b = skyB * br; }}

    if(y >= mh-20 && y < mh-6){{
      int band = (int)fmodf(t*speed*2.0f, 8.0f);
      if(((x/8 + band) % 5) == 2){{ r = pipeR*br; g=pipeG*br; b=pipeB*br; }}
    }}

    if(x >= sx && x < sx+8 && y >= sy && y < sy+8){{
      if(bit8(SPRH, x-sx, y-sy)){{
        r = (float)L_R[li] * br;
        g = (float)L_G[li] * br;
        b = (float)L_B[li] * br;
        return;
      }}
    }}
    return;
  }}

  // Variant 0: generic tilemap_sprite
  static const uint8_t SPR[8] = {{
    0b00011000,
    0b00111100,
    0b01111110,
    0b00111100,
    0b00011000,
    0b00100100,
    0b01000010,
    0b10000001,
  }};

  float speed = fmaxf(0.0f, sp);
  int sx = (int)floorf(fmodf(t * speed * 10.0f, (float)(mw + 8)) - 8.0f);
  float jh = 4.0f + clamp01(pf1) * 12.0f;
  float jump = (pf0 > 0.5f) ? (fabsf(sinf(t * 6.2831853f)) * jh) : 0.0f;
  int sy = (mh - 16) - (int)floorf(jump + 0.5f);

  if(x >= sx && x < sx+8 && y >= sy && y < sy+8){{
    if(bit8(SPR, x-sx, y-sy)){{
      r = (float)L_R[li] * br;
      g = (float)L_G[li] * br;
      b = (float)L_B[li] * br;
      return;
    }}
  }}

  bg_default();
  return;
#endif
}}
// Phase 3B: CA cluster (Game of Life / Brian's Brain / Elementary CA / Langton's Ant)
// Export notes:
// - deterministic seed
// - updates at a fixed tick derived from speed
// - designed as stress-test proof path: runs on firmware with no external deps
static uint8_t CA_A[NUM_LEDS];
static uint8_t CA_B[NUM_LEDS];
static int CA_LAST_FRAME = -1;
static int CA_LAST_VARIANT = -1;
static uint8_t CA_INITED = 0;
static int ANT_X = 0, ANT_Y = 0, ANT_DIR = 0;

static inline void ca_init(int variant, float density01){
  CA_INITED = 1;
  CA_LAST_VARIANT = variant;
  CA_LAST_FRAME = -1;
  rng_state = 0xA5A5A5u ^ (uint32_t)(variant*2654435761u) ^ 0x1234567u;
#ifdef MATRIX_WIDTH
  int mw = (int)MATRIX_WIDTH;
  int mh = (int)MATRIX_HEIGHT;
  int n = mw*mh;
  if(n > NUM_LEDS) n = NUM_LEDS;
  float p = clamp01(density01);
  for(int i=0;i<n;i++){
    uint32_t rv = xorshift32();
    CA_A[i] = ((rv & 0xFFFFu) < (uint32_t)(p*65535.0f)) ? 1 : 0;
    CA_B[i] = 0;
  }
  // ant start
  ANT_X = mw/2; ANT_Y = mh/2; ANT_DIR = 0;
#else
  for(int i=0;i<NUM_LEDS;i++){ CA_A[i]=0; CA_B[i]=0; }
  CA_A[NUM_LEDS/2] = 1;
#endif
}

static inline void ca_step_elementary_rule30(){
  // 1D Rule 30 on CA_A -> CA_B (strip or top row), then swap.
  for(int i=0;i<NUM_LEDS;i++){
    uint8_t L = (i>0) ? CA_A[i-1] : 0;
    uint8_t C = CA_A[i];
    uint8_t R = (i<NUM_LEDS-1) ? CA_A[i+1] : 0;
    uint8_t pat = (L<<2)|(C<<1)|R;
    // Rule 30: 00011110 (bits 7..0), but we index by pat 0..7
    uint8_t out = (uint8_t)((0b00011110 >> pat) & 1);
    CA_B[i]=out;
  }
  for(int i=0;i<NUM_LEDS;i++) CA_A[i]=CA_B[i];
}

#ifdef MATRIX_WIDTH
static inline int ca_xy(int x,int y){ return XY(x,y); }

static inline void ca_step_life(){
  int mw = (int)MATRIX_WIDTH;
  int mh = (int)MATRIX_HEIGHT;
  for(int y=0;y<mh;y++){
    for(int x=0;x<mw;x++){
      int n=0;
      for(int dy=-1;dy<=1;dy++){
        int yy=y+dy; if(yy<0||yy>=mh) continue;
        for(int dx=-1;dx<=1;dx++){
          int xx=x+dx; if(xx<0||xx>=mw) continue;
          if(dx==0 && dy==0) continue;
          n += (CA_A[ca_xy(xx,yy)]?1:0);
        }
      }
      uint8_t cur = CA_A[ca_xy(x,y)];
      uint8_t nxt = 0;
      if(cur){
        nxt = (n==2 || n==3) ? 1 : 0;
      } else {
        nxt = (n==3) ? 1 : 0;
      }
      CA_B[ca_xy(x,y)] = nxt;
    }
  }
  int n = mw*mh; if(n>NUM_LEDS) n=NUM_LEDS;
  for(int i=0;i<n;i++) CA_A[i]=CA_B[i];
}

static inline void ca_step_brians_brain(){
  // States: 0=dead, 1=alive, 2=dying
  int mw = (int)MATRIX_WIDTH;
  int mh = (int)MATRIX_HEIGHT;
  for(int y=0;y<mh;y++){
    for(int x=0;x<mw;x++){
      int aliveN=0;
      for(int dy=-1;dy<=1;dy++){
        int yy=y+dy; if(yy<0||yy>=mh) continue;
        for(int dx=-1;dx<=1;dx++){
          int xx=x+dx; if(xx<0||xx>=mw) continue;
          if(dx==0 && dy==0) continue;
          aliveN += (CA_A[ca_xy(xx,yy)]==1)?1:0;
        }
      }
      uint8_t cur = CA_A[ca_xy(x,y)];
      uint8_t nxt = 0;
      if(cur==1) nxt=2;
      else if(cur==2) nxt=0;
      else { nxt = (aliveN==2) ? 1 : 0; }
      CA_B[ca_xy(x,y)] = nxt;
    }
  }
  int n = mw*mh; if(n>NUM_LEDS) n=NUM_LEDS;
  for(int i=0;i<n;i++) CA_A[i]=CA_B[i];
}

static inline void ca_step_langtons_ant(){
  int mw = (int)MATRIX_WIDTH;
  int mh = (int)MATRIX_HEIGHT;
  int idx = ca_xy(ANT_X, ANT_Y);
  uint8_t cell = CA_A[idx] & 1;
  if(cell==0){
    // turn right
    ANT_DIR = (ANT_DIR + 1) & 3;
    CA_A[idx] = 1;
  } else {
    // turn left
    ANT_DIR = (ANT_DIR + 3) & 3;
    CA_A[idx] = 0;
  }
  // move forward
  if(ANT_DIR==0) ANT_Y -= 1;
  else if(ANT_DIR==1) ANT_X += 1;
  else if(ANT_DIR==2) ANT_Y += 1;
  else ANT_X -= 1;

  if(ANT_X<0) ANT_X=0;
  if(ANT_Y<0) ANT_Y=0;
  if(ANT_X>=mw) ANT_X=mw-1;
  if(ANT_Y>=mh) ANT_Y=mh-1;
}
#endif

{CA_MODULE_DECLS}

static inline void evalCACluster(int li, int i, float t, float br, float sp, float pf1, float pf2, float pf3, float &r, float &g, float &b){
  const int variant = (int)L_PI0[li]; // 0=brians,1=life,2=elementary,3=ant
  if(!CA_INITED || CA_LAST_VARIANT != variant){
    ca_init(variant, pf1);
  }
  // tick rate: 6..60 Hz derived from speed
  float hz = 6.0f + clamp01(sp) * 54.0f;
  int frame = (int)floorf(t * hz);
  if(frame != CA_LAST_FRAME){
    CA_LAST_FRAME = frame;
    if(variant>=4){
{CA_MODULE_DISPATCH}
    } else {
#ifdef MATRIX_WIDTH
    if(variant==0) ca_step_brians_brain();
    else if(variant==1) ca_step_life();
    else if(variant==3) ca_step_langtons_ant();
    else ca_step_life(); // default
#else
    ca_step_elementary_rule30();
#endif
    }
  }

#ifdef MATRIX_WIDTH
  int mw=(int)MATRIX_WIDTH;
  int mh=(int)MATRIX_HEIGHT;
  int x = i % (mw>0?mw:1);
  int y = i / (mw>0?mw:1);
  int idx = XY(x,y);
  if(variant==0){
    uint8_t s = CA_A[idx];
    if(s==1){ r=255.0f*br; g=40.0f*br; b=10.0f*br; }
    else if(s==2){ r=20.0f*br; g=90.0f*br; b=255.0f*br; }
    else { r=0; g=0; b=0; }
    return;
  }
  if(variant==3){
    // ant highlighted
    if(x==ANT_X && y==ANT_Y){ r=255.0f*br; g=255.0f*br; b=255.0f*br; return; }
    uint8_t s = CA_A[idx] & 1;
    if(s){ r=20.0f*br; g=200.0f*br; b=40.0f*br; } else { r=0; g=0; b=0; }
    return;
  }
  // life
  uint8_t s = CA_A[idx] & 1;
  if(s){ r=(float)L_R[li]*br; g=(float)L_G[li]*br; b=(float)L_B[li]*br; }
  else { r=0; g=0; b=0; }
#else
  // strip elementary CA visualization
  uint8_t s = CA_A[i] & 1;
  if(s){ r=(float)L_R[li]*br; g=(float)L_G[li]*br; b=(float)L_B[li]*br; }
  else { r=0; g=0; b=0; }
#endif
}

static inline void evalMSGEQ7(int li, int i, float t, float br, float sp, float pf1, float &r, float &g, float &b){
  // pf1 = gain (default 1.0)
  float gain = pf1;
  if(gain < 0.05f) gain = 0.05f;
  if(gain > 4.0f) gain = 4.0f;

  const int variant = (int)L_PI0[li]; // 0=bars, 1=reactive strobe
  if(variant == 1){
    // Reactive strobe: energy drives duty
    float e = g_energy * gain;
    if(e < 0.0f) e = 0.0f;
    if(e > 1.0f) e = 1.0f;
    // Use time + energy to strobe
    float phase = fmodf(t * (6.0f + 40.0f*e), 1.0f);
    float on = (phase < (0.15f + 0.35f*e)) ? 1.0f : 0.0f;
    r = (float)L_R[li] * br * on;
    g = (float)L_G[li] * br * on;
    b = (float)L_B[li] * br * on;
    return;
  }

  // Bars: split canvas into 7 equal bands; fill each band based on mono[band]
  int n = NUM_LEDS;
  if(n < 7){ r=0; g=0; b=0; return; }
  int seg = n / 7;
  if(seg < 1) seg = 1;
  int band = i / seg;
  if(band < 0) band = 0;
  if(band > 6) band = 6;

  float v = g_mono[band] * gain; // 0..~1
  if(v < 0.0f) v = 0.0f;
  if(v > 1.0f) v = 1.0f;

  int within = i - band*seg;
  int filled = (int)(v * (float)seg);

  if(within < filled){
    r = (float)L_R[li] * br;
    g = (float)L_G[li] * br;
    b = (float)L_B[li] * br;
  }else{
    r=0; g=0; b=0;
  }
}

static inline void evalBouncer(int li, int i, float br, float sp, float wd, float &r, float &g, float &b) {{
  // Uses L_R/L_G/L_B as dot color and L_R2/L_G2/L_B2 as background.
  if (!ST_INIT[li]) state_reset_layer(li);
  float pos = ST_F[li][0];   // pos
  int center = (int)floorf(pos + 0.5f);
  int width = (int)floorf(wd + 0.5f);
  if (width < 1) width = 1;
  if (width > NUM_LEDS) width = NUM_LEDS;
  int half = width / 2;
  int start = center - half;
  int end = start + width;

  bool on = (i >= start && i < end);
  if (on) {{
    r = (float)L_R[li] * br;
    g = (float)L_G[li] * br;
    b = (float)L_B[li] * br;
  }} else {{
    r = (float)L_R2[li] * br;
    g = (float)L_G2[li] * br;
    b = (float)L_B2[li] * br;
  }}
}}

static inline void updateBouncer(int li, float dt, float sp) {{
  if (!ST_INIT[li]) state_reset_layer(li);
  float pos = ST_F[li][0];
  float vel = ST_F[li][1];
  if (vel == 0.0f) vel = 1.0f;

  float speed = sp;
  if (speed < 0.0f) {{
    vel = -fabsf(vel);
    speed = fabsf(speed);
  }} else {{
    vel = (vel >= 0.0f) ? fabsf(vel) : -fabsf(vel);
  }}

  pos += vel * speed * dt;

  if (pos < 0.0f) {{ pos = 0.0f; vel = fabsf(vel); }}
  if (pos > (float)(NUM_LEDS - 1)) {{ pos = (float)(NUM_LEDS - 1); vel = -fabsf(vel); }}

  ST_F[li][0] = pos;
  ST_F[li][1] = vel;
}}

static inline void resetBreakout(int li, float so, float dn) {{
  // blocks count 3..8 from density, hp 1..5 from softness
  int blocks = (int)roundf(3.0f + clamp01(dn) * 5.0f);
  if (blocks < 3) blocks = 3;
  if (blocks > 8) blocks = 8;
  int hp = (int)roundf(1.0f + clamp01(so) * 4.0f);
  if (hp < 1) hp = 1;
  if (hp > 5) hp = 5;
  // init block hp in ST_I[li][0..blocks-1], clear rest
  for (int k=0;k<8;k++) ST_I[li][k] = 0;
  for (int b=0;b<blocks;b++) ST_I[li][b] = hp;
  ST_I[li][6] = 0; // score
  ST_I[li][7] = 1; // lives placeholder
  // ball & paddle in ST_F
  ST_F[li][0] = (float)(NUM_LEDS - 5); // ball pos
  ST_F[li][1] = -1.0f;                // ball vel
  ST_F[li][2] = (float)(NUM_LEDS - 3); // paddle center
}}

static inline void updateBreakout(int li, float dt, float sp, float wd, float so, float dn, float pf0) {{
  if (!ST_INIT[li]) {{ state_reset_layer(li); resetBreakout(li, so, dn); ST_INIT[li]=1; }}
  int blocks = (int)roundf(3.0f + clamp01(dn) * 5.0f);
  if (blocks < 3) blocks = 3;
  if (blocks > 8) blocks = 8;
  int hp = (int)roundf(1.0f + clamp01(so) * 4.0f);
  if (hp < 1) hp = 1;
  if (hp > 5) hp = 5;

  int width = (int)wd;
  if (width < 2) width = 2;
  if (width > (NUM_LEDS/2)) width = NUM_LEDS/2;

  float ball = ST_F[li][0];
  float vel  = ST_F[li][1];
  float paddle = ST_F[li][2];

  if (vel == 0.0f) vel = -1.0f;
  float speed = fmaxf(0.0f, sp);
  // paddle control via purpose_f0 (0..1)
  if (pf0 > 0.02f) ST_F[li][2] = clamp01(pf0) * (float)(NUM_LEDS-1);
  // ship control 0..1 -> position
  ST_F[li][0] = clamp01(pf0) * (float)(NUM_LEDS-1);

  int blockRegion = max(6, NUM_LEDS/3);
  int blockW = max(1, blockRegion / blocks);

  // simple AI paddle follows ball
  float d = ball - paddle;
  if (d < -1.0f) d = -1.0f;
  if (d > 1.0f) d = 1.0f;
  paddle += d * speed * dt * 25.0f;
  float minP = (float)blockRegion + (float)width*0.5f;
  float maxP = (float)(NUM_LEDS-1) - (float)width*0.5f;
  if (paddle < minP) paddle = minP;
  if (paddle > maxP) paddle = maxP;

  // move ball
  ball += vel * speed * dt * 30.0f;

  if (ball < 0.0f) {{ ball = 0.0f; vel = fabsf(vel); }}
  if (ball > (float)(NUM_LEDS-1)) {{ ball = (float)(NUM_LEDS-1); vel = -fabsf(vel); }}

  // block collision
  if (ball < (float)blockRegion) {{
    int bi = (int)(ball / (float)blockW);
    if (bi >= 0 && bi < blocks && ST_I[li][bi] > 0) {{
      ST_I[li][bi] -= 1;
      ST_I[li][6] += 1; // score
      vel = fabsf(vel);
    }}
  }}

  // paddle collision
  if (vel > 0.0f) {{
    float pl = paddle - (float)width*0.5f;
    float pr = paddle + (float)width*0.5f;
    if (ball >= pl && ball <= pr) {{
      vel = -fabsf(vel);
      ball = pl - 0.1f;
    }}
  }}

  // win -> refill blocks
  bool any = false;
  for (int b=0;b<blocks;b++) if (ST_I[li][b] > 0) {{ any = true; break; }}
  if (!any) {{
    for (int b=0;b<blocks;b++) ST_I[li][b] = hp;
    vel = -fabsf(vel);
    ball = (float)(NUM_LEDS-5);
  }}

  ST_F[li][0] = ball;
  ST_F[li][1] = vel;
  ST_F[li][2] = paddle;
}}

static inline void evalBreakout(int li, int i, float br, float wd, float so, float dn, float &r, float &g, float &b) {{
  int blocks = (int)roundf(3.0f + clamp01(dn) * 5.0f);
  if (blocks < 3) blocks = 3;
  if (blocks > 8) blocks = 8;

  int width = (int)wd;
  if (width < 2) width = 2;
  if (width > (NUM_LEDS/2)) width = NUM_LEDS/2;

  int blockRegion = max(6, NUM_LEDS/3);
  int blockW = max(1, blockRegion / blocks);

  // default off
  r = g = b = 0.0f;

  // ball
  int ball = (int)roundf(ST_F[li][0]);
  if (i == ball) {{
    r = (float)L_R[li] * br;
    g = (float)L_G[li] * br;
    b = (float)L_B[li] * br;
    return;
  }}

  // blocks (use color2)
  if (i < blockRegion) {{
    int bi = i / blockW;
    if (bi >= 0 && bi < blocks && ST_I[li][bi] > 0) {{
      r = (float)L_R2[li] * br;
      g = (float)L_G2[li] * br;
      b = (float)L_B2[li] * br;
      return;
    }}
  }}

  // paddle (use bg color arrays in L_BG?? we store bg into L_RBG?? in exporter uses L_R2 for bg?)
  // In this exporter, bg is stored into L_R2/L_G2/L_B2 OR separate? We use L_R2 etc for secondary.
  // For breakout, we treat bg (paddle color) as L_R2/L_G2/L_B2 ONLY if you set color2; but we need distinct.
  // So we use L_R2/L_G2/L_B2 as blocks, and paddle uses L_RBG arrays if present; else fallback to blocks color.
  int hasBg = 0;
  #ifdef HAS_BG_COLOR
    hasBg = 1;
  #endif

  float paddle = ST_F[li][2];
  int pl = (int)roundf(paddle - (float)width*0.5f);
  int pr = (int)roundf(paddle + (float)width*0.5f);
  if (i >= pl && i <= pr) {{
    // paddle uses background color arrays if available, else uses blocks color2
    #if defined(L_RBG)
      r = (float)L_RBG[li] * br;
      g = (float)L_GBG[li] * br;
      b = (float)L_BBG[li] * br;
    #else
      r = (float)L_R2[li] * br;
      g = (float)L_G2[li] * br;
      b = (float)L_B2[li] * br;
    #endif
    return;
  }}
}}
static inline void resetAsteroids(int li, float so, float dn, float pi0) {{
  int k = (int)roundf(1.0f + clamp01(dn) * 2.0f);
  if (k < 1) k = 1;
  if (k > 3) k = 3;
  int hp = (int)roundf(1.0f + clamp01(so) * 4.0f);
  if (hp < 1) hp = 1;
  if (hp > 5) hp = 5;

  ST_F[li][0] = (float)(NUM_LEDS - 3); // ship
  ST_F[li][1] = 0.0f;                 // cooldown
  ST_F[li][2] = -1.0f; ST_F[li][3] = -1.0f; ST_F[li][4] = -1.0f; // bullets
  ST_F[li][5] = 2.0f; ST_F[li][6] = 5.0f; ST_F[li][7] = 8.0f;    // asteroid positions

  for (int i=0;i<8;i++) ST_I[li][i] = 0;
  for (int a=0;a<k;a++) ST_I[li][a] = hp; // asteroid hp
  ST_I[li][6] = 0; // score
}}

static inline void updateAsteroids(int li, float dt, float sp, float so, float dn, float pf0, float pf1, float pi0) {{
  if (!ST_INIT[li]) {{ state_reset_layer(li); resetAsteroids(li, so, dn, 0.0f); ST_INIT[li]=1; }}

  int k = (int)roundf(1.0f + clamp01(dn) * 2.0f);
  if (k < 1) k = 1;
  if (k > 3) k = 3;
  int hp0 = (int)roundf(1.0f + clamp01(so) * 4.0f);
  if (hp0 < 1) hp0 = 1;
  if (hp0 > 5) hp0 = 5;

  float speed = fmaxf(0.0f, sp);
  // paddle control via purpose_f0 (0..1)
  if (pf0 > 0.02f) ST_F[li][2] = clamp01(pf0) * (float)(NUM_LEDS-1);
  // ship control 0..1 -> position
  ST_F[li][0] = clamp01(pf0) * (float)(NUM_LEDS-1);

  // cooldown & auto-fire (purpose_f1 controls rate)
  float fireRate = 0.35f - clamp01(pf1) * 0.25f; // 0.35..0.10
  float cool = ST_F[li][1];
  cool -= dt;
  if (cool <= 0.0f) {{
    for (int b=0;b<3;b++) {{
      if (ST_F[li][2+b] < 0.0f) {{ ST_F[li][2+b] = ST_F[li][0] - 1.0f; break; }}
    }}
    cool = fireRate;
  }}
  ST_F[li][1] = cool;

  // move bullets left
  for (int b=0;b<3;b++) {{
    float bp = ST_F[li][2+b];
    if (bp >= 0.0f) {{
      bp -= speed * dt * 25.0f;
      if (bp < 0.0f) bp = -1.0f;
      ST_F[li][2+b] = bp;
    }}
  }}

  // move asteroids right slowly, wrap
  for (int a=0;a<k;a++) {{
    float ap = ST_F[li][5+a];
    ap += (2.0f + (float)a) * speed * dt * 3.0f;
    if (ap > (float)(NUM_LEDS-1)) ap = 0.0f;
    ST_F[li][5+a] = ap;
    if (ST_I[li][a] <= 0) {{ ST_I[li][a] = hp0; ST_F[li][5+a] = 0.0f; }}
  }}

  // collisions bullets vs asteroids
  for (int b=0;b<3;b++) {{
    float bp = ST_F[li][2+b];
    if (bp < 0.0f) continue;
    for (int a=0;a<k;a++) {{
      if (ST_I[li][a] <= 0) continue;
      float ap = ST_F[li][5+a];
      if (fabsf(ap - bp) <= 0.6f) {{
        ST_I[li][a] -= 1;
        ST_I[li][6] += 1;
        ST_F[li][2+b] = -1.0f;
        break;
      }}
    }}
  }}
}}

static inline void evalAsteroids(int li, int i, float br, float so, float dn, float &r, float &g, float &b) {{
  int k = (int)roundf(1.0f + clamp01(dn) * 2.0f);
  if (k < 1) k = 1;
  if (k > 3) k = 3;

  r = g = b = 0.0f;

  int ship = (int)roundf(ST_F[li][0]);
  if (i == ship) {{
    r = (float)L_RBG[li] * br;
    g = (float)L_GBG[li] * br;
    b = (float)L_BBG[li] * br;
    return;
  }}

  for (int bb=0; bb<3; bb++) {{
    int bp = (int)roundf(ST_F[li][2+bb]);
    if (bp >= 0 && i == bp) {{
      r = (float)L_R[li] * br;
      g = (float)L_G[li] * br;
      b = (float)L_B[li] * br;
      return;
    }}
  }}

  for (int a=0; a<k; a++) {{
    if (ST_I[li][a] <= 0) continue;
    int ap = (int)roundf(ST_F[li][5+a]);
    if (i == ap) {{
      r = (float)L_R2[li] * br;
      g = (float)L_G2[li] * br;
      b = (float)L_B2[li] * br;
      return;
    }}
  }}
}}

inline void evalWipe(int li, int i, float t, float br, float sp, float so, float dir, float &r, float &g, float &b) {{
  float phase = fmodf(t * fmaxf(0.0f, sp), 1.0f);
  float edge = ((dir >= 0.0f) ? phase : (1.0f - phase)) * (float)(NUM_LEDS - 1);
  float d = (float)i - edge;
  float a = 0.0f;
  if (so <= 0.001f) {{
    a = (d <= 0.0f) ? 1.0f : 0.0f;
  }} else {{
    float w = so * 10.0f; // softness in LEDs
    a = clamp01(1.0f - (d / fmaxf(0.001f, w)));
  }}
  r = (float)L_R[li] * br * a;
  g = (float)L_G[li] * br * a;
  b = (float)L_B[li] * br * a;
}}

// --- Phase 3E: Games cluster (Snake / Invaders / Shooter / Blocks+Ball) ---
// These are deterministic "lite" runtimes designed to be export-safe and board-agnostic.
// They operate in LED-index space (strip), which also renders on matrices via the mapping layer.

static inline void resetSnakeLite(int li) {
  state_reset_layer(li);
  ST_F[li][0] = 0.0f;   // head
  ST_F[li][1] = 1.0f;   // dir
  ST_F[li][2] = 6.0f;   // tail length
  ST_F[li][3] = 0.0f;   // accumulator
}

static inline void updateSnakeLite(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) { resetSnakeLite(li); ST_INIT[li]=1; }
  float speed = 2.0f + clamp01(sp) * 14.0f;     // steps per second
  float tail  = 3.0f + clamp01(pf1) * 24.0f;    // 3..27
  ST_F[li][2] = tail;

  // direction control: pi0 bit0 flips direction, pf0 can "nudge" (Rules)
  float dir = (pi0 & 1) ? -1.0f : 1.0f;
  if (pf0 > 0.75f) dir = -1.0f;
  else if (pf0 > 0.25f) dir = 1.0f;
  ST_F[li][1] = dir;

  ST_F[li][3] += dt * speed;
  while (ST_F[li][3] >= 1.0f) {
    ST_F[li][3] -= 1.0f;
    float h = ST_F[li][0] + dir;
    if (h < 0.0f) h = (float)(NUM_LEDS-1);
    if (h > (float)(NUM_LEDS-1)) h = 0.0f;
    ST_F[li][0] = h;
  }
}

static inline void evalSnakeLite(int li, int i, float br, float &r, float &g, float &b) {
  r=g=b=0.0f;
  int head = (int)roundf(ST_F[li][0]);
  int tail = (int)roundf(ST_F[li][2]);
  float dir = ST_F[li][1];
  if (i == head) { r = 0.0f; g = 255.0f * br; b = 60.0f * br; return; }
  // simple trailing glow behind head
  for (int k=1;k<=tail && k<=28;k++){
    int idx = head - (int)(dir * (float)k);
    while (idx < 0) idx += NUM_LEDS;
    while (idx >= NUM_LEDS) idx -= NUM_LEDS;
    if (i == idx) {
      float a = 1.0f - ((float)k / (float)(tail+1));
      r = 20.0f * br * a;
      g = 200.0f * br * a;
      b = 40.0f * br * a;
      return;
    }
  }
}

static inline void resetInvadersLite(int li) {
  state_reset_layer(li);
  ST_F[li][0] = 0.0f;  // phase
  ST_F[li][1] = 1.0f;  // dir
  ST_F[li][2] = 0.0f;  // accumulator
}

static inline void updateInvadersLite(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) { resetInvadersLite(li); ST_INIT[li]=1; }
  float speed = 0.25f + clamp01(sp) * 2.0f; // scroll speed
  ST_F[li][0] += dt * speed * ((pi0 & 1) ? -1.0f : 1.0f);
  if (ST_F[li][0] < 0.0f) ST_F[li][0] += 1.0f;
  if (ST_F[li][0] > 1.0f) ST_F[li][0] -= 1.0f;
}

static inline void evalInvadersLite(int li, int i, float br, float &r, float &g, float &b) {
  r=g=b=0.0f;
  // repeating invader columns
  int period = 14;
  int off = (int)floorf(ST_F[li][0] * (float)period);
  int p = (i + off) % period;
  if (p == 2 || p == 3 || p == 10 || p == 11) {
    r = 255.0f * br;
    g = 40.0f * br;
    b = 20.0f * br;
  } else if (p == 6 || p == 7) {
    r = 50.0f * br;
    g = 220.0f * br;
    b = 50.0f * br;
  }
}

static inline void resetShooterLite(int li) {
  state_reset_layer(li);
  ST_F[li][0] = (float)(NUM_LEDS/2); // ship
  ST_F[li][1] = -1.0f;              // bullet
  ST_F[li][2] = 0.0f;               // fire phase
  ST_F[li][3] = 0.0f;               // accumulator
}

static inline void updateShooterLite(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) { resetShooterLite(li); ST_INIT[li]=1; }
  float speed = 0.8f + clamp01(sp) * 3.0f;

  // ship drift (deterministic)
  ST_F[li][0] += dt * speed * 6.0f * ((pi0 & 1) ? -1.0f : 1.0f);
  if (ST_F[li][0] < 1.0f) ST_F[li][0] = (float)(NUM_LEDS-2);
  if (ST_F[li][0] > (float)(NUM_LEDS-2)) ST_F[li][0] = 1.0f;

  // fire trigger via pf0 > 0.5 OR periodic
  ST_F[li][2] += dt * (0.6f + clamp01(pf1) * 2.0f);
  bool want_fire = (pf0 > 0.5f) || (ST_F[li][2] >= 1.0f);
  if (ST_F[li][2] >= 1.0f) ST_F[li][2] -= 1.0f;

  if (want_fire && ST_F[li][1] < 0.0f) {
    ST_F[li][1] = ST_F[li][0]; // spawn bullet at ship
  }

  // bullet move
  if (ST_F[li][1] >= 0.0f) {
    ST_F[li][1] += dt * (12.0f + clamp01(sp) * 20.0f);
    if (ST_F[li][1] > (float)(NUM_LEDS-1)) ST_F[li][1] = -1.0f;
  }
}

static inline void evalShooterLite(int li, int i, float br, float &r, float &g, float &b) {
  r=g=b=0.0f;
  int ship = (int)roundf(ST_F[li][0]);
  int bull = (int)roundf(ST_F[li][1]);
  if (i == ship) { r = 30.0f * br; g = 120.0f * br; b = 255.0f * br; return; }
  if (ST_F[li][1] >= 0.0f && i == bull) { r = 255.0f * br; g = 255.0f * br; b = 255.0f * br; return; }
  // enemies: periodic red dots
  if ((i % 17) == 0) { r = 255.0f * br; g = 30.0f * br; b = 20.0f * br; }
}

static inline void resetBlocksBallLite(int li) {
  state_reset_layer(li);
  ST_F[li][0] = (float)(NUM_LEDS - 4); // ball
  ST_F[li][1] = -1.0f;                // vel
  ST_F[li][2] = (float)(NUM_LEDS - 6); // paddle
  ST_I[li][0] = 12;                   // blocks count
}

static inline void updateBlocksBallLite(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) { resetBlocksBallLite(li); ST_INIT[li]=1; }
  float speed = 6.0f + clamp01(sp) * 18.0f;
  float ball = ST_F[li][0];
  float vel  = (ST_F[li][1] == 0.0f) ? -1.0f : ST_F[li][1];

  // paddle control via pf0
  if (pf0 > 0.02f) ST_F[li][2] = clamp01(pf0) * (float)(NUM_LEDS - 1);

  ball += vel * dt * speed;
  if (ball < 0.0f) { ball = 0.0f; vel = -vel; }
  if (ball > (float)(NUM_LEDS-1)) { ball = (float)(NUM_LEDS-1); vel = -vel; }

  // simple "block hit" region at start of strip
  int blocks = ST_I[li][0];
  int bi = (int)roundf(ball);
  if (blocks > 0 && bi < blocks) {
    ST_I[li][0] = blocks - 1;
    vel = -vel;
  }

  ST_F[li][0] = ball;
  ST_F[li][1] = vel;
}

static inline void evalBlocksBallLite(int li, int i, float br, float &r, float &g, float &b) {
  r=g=b=0.0f;
  int blocks = ST_I[li][0];
  if (i < blocks) { r = 200.0f * br; g = 80.0f * br; b = 20.0f * br; return; }
  int ball = (int)roundf(ST_F[li][0]);
  if (i == ball) { r = 255.0f * br; g = 255.0f * br; b = 120.0f * br; return; }
  int paddle = (int)roundf(ST_F[li][2]);
  if (abs(i - paddle) <= 1) { r = 30.0f * br; g = 255.0f * br; b = 120.0f * br; return; }
}

// ---- Phase A+E (exportable showcase equivalents) ----
// NOTE: These implementations are intentionally lightweight and deterministic.

static inline float _gauss1(float d, float sigma) {
  // Cheap gaussian-ish falloff (no expf)
  sigma = fmaxf(1.0f, sigma);
  float x = d / sigma;
  float a = 1.0f - x;
  if (a < 0.0f) a = 0.0f;
  // Sharpen curve
  return a * a;
}

static inline void evalBoidsSwarm(int li, int i, float t, float br, float sp, float wd, float dn, float &r, float &g, float &b) {
  // Three "agents" moving with slightly different frequencies.
  // wd controls spot size, dn controls how many are visible (density-like).
  r=g=b=0.0f;
  float speed = 0.15f + clamp01(sp) * 1.20f;
  float sigma = 1.0f + clamp01(wd) * (float)NUM_LEDS * 0.06f;
  int agents = (dn < 0.34f) ? 1 : ((dn < 0.67f) ? 2 : 3);
  for (int a=0; a<agents; a++) {
    float ph = (float)li * 0.07f + (float)a * 0.31f;
    float u = 0.5f + 0.5f * sinf((t * speed * (0.9f + 0.25f * a) + ph) * 6.2831853f);
    float pos = u * (float)(NUM_LEDS - 1);
    float d = fabsf((float)i - pos);
    float aa = _gauss1(d, sigma);
    // Alternate base/secondary colors for variety.
    float cr = (a == 1) ? (float)L_R2[li] : (float)L_R[li];
    float cg = (a == 1) ? (float)L_G2[li] : (float)L_G[li];
    float cb = (a == 1) ? (float)L_B2[li] : (float)L_B[li];
    r += cr * br * aa;
    g += cg * br * aa;
    b += cb * br * aa;
  }
}

static inline void resetPredatorPrey(int li) {
  state_reset_layer(li);
  ST_F[li][0] = 0.0f;                    // predator pos
  ST_F[li][1] = (float)(NUM_LEDS - 1);   // prey pos
  ST_F[li][2] = -1.0f;                   // prey dir
  ST_I[li][0] = 0;                       // score
  ST_INIT[li] = 1;
}

static inline void updatePredatorPrey(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) resetPredatorPrey(li);
  float predator = ST_F[li][0];
  float prey     = ST_F[li][1];
  float prey_dir = (ST_F[li][2] == 0.0f) ? -1.0f : ST_F[li][2];

  float ps = 4.0f + clamp01(sp) * 18.0f;     // predator speed
  float ys = 2.0f + clamp01(sp) * 10.0f;     // prey speed

  // prey: small deterministic wiggle + optional external push via pf0 (0..1 => bias right)
  float bias = (clamp01(pf0) - 0.5f) * 2.0f;
  float wig  = sinf((float)li * 1.7f + (float)pi0 * 0.13f + prey * 0.09f) * 0.25f;
  float dir = prey_dir + bias * 0.35f + wig;
  dir = (dir >= 0.0f) ? 1.0f : -1.0f;
  prey += dir * dt * ys;
  if (prey < 0.0f) { prey = 0.0f; dir = 1.0f; }
  if (prey > (float)(NUM_LEDS-1)) { prey = (float)(NUM_LEDS-1); dir = -1.0f; }
  ST_F[li][2] = dir;

  // predator: chase prey
  float chase = (prey > predator) ? 1.0f : -1.0f;
  predator += chase * dt * ps;
  if (predator < 0.0f) predator = 0.0f;
  if (predator > (float)(NUM_LEDS-1)) predator = (float)(NUM_LEDS-1);

  // capture
  if (fabsf(predator - prey) < 1.0f) {
    ST_I[li][0] = (int16_t)(ST_I[li][0] + 1);
    // respawn prey far from predator
    prey = (predator < (float)NUM_LEDS * 0.5f) ? (float)(NUM_LEDS-1) : 0.0f;
    ST_F[li][2] = (prey < predator) ? -1.0f : 1.0f;
  }

  ST_F[li][0] = predator;
  ST_F[li][1] = prey;
}

static inline void evalPredatorPrey(int li, int i, float br, float &r, float &g, float &b) {
  r=g=b=0.0f;
  int predator = (int)roundf(ST_F[li][0]);
  int prey     = (int)roundf(ST_F[li][1]);
  int score    = (int)ST_I[li][0];

  // background faint
  r = 2.0f * br; g = 2.0f * br; b = 2.0f * br;

  // prey (green-ish)
  if (i == prey) {
    r = 40.0f * br; g = 255.0f * br; b = 60.0f * br;
    return;
  }
  // predator (red-ish)
  if (i == predator) {
    r = 255.0f * br; g = 50.0f * br; b = 40.0f * br;
    return;
  }
  // score ticks at the start of strip
  if (i < (score % 16)) {
    r = 120.0f * br; g = 120.0f * br; b = 255.0f * br;
  }
}

static inline void resetMemoryHeatmap(int li) {
  state_reset_layer(li);
  ST_F[li][0] = (float)(NUM_LEDS * 0.25f); // pos0
  ST_F[li][1] = 0.0f;                     // val0
  ST_F[li][2] = (float)(NUM_LEDS * 0.75f); // pos1
  ST_F[li][3] = 0.0f;                     // val1
  ST_INIT[li] = 1;
}

static inline void updateMemoryHeatmap(int li, float dt, float sp, float pf0, float pf1, int pi0) {
  if (!ST_INIT[li]) resetMemoryHeatmap(li);
  // decay
  float decay = 0.25f + clamp01(pf1) * 1.25f;
  ST_F[li][1] *= fmaxf(0.0f, 1.0f - dt * decay);
  ST_F[li][3] *= fmaxf(0.0f, 1.0f - dt * decay);

  // wander hotspots slowly
  float wander = 0.8f + clamp01(sp) * 6.0f;
  ST_F[li][0] += sinf((float)li * 1.1f + (float)pi0 * 0.07f + ST_F[li][0] * 0.03f) * dt * wander;
  ST_F[li][2] += cosf((float)li * 1.3f + (float)pi0 * 0.09f + ST_F[li][2] * 0.03f) * dt * wander;
  if (ST_F[li][0] < 0.0f) ST_F[li][0] = 0.0f;
  if (ST_F[li][0] > (float)(NUM_LEDS-1)) ST_F[li][0] = (float)(NUM_LEDS-1);
  if (ST_F[li][2] < 0.0f) ST_F[li][2] = 0.0f;
  if (ST_F[li][2] > (float)(NUM_LEDS-1)) ST_F[li][2] = (float)(NUM_LEDS-1);

  // excite memory with pf0 (intended to be moduloted by audio energy)
  float inp = clamp01(pf0);
  if (inp > 0.02f) {
    // push into whichever hotspot is currently weaker
    if (ST_F[li][1] < ST_F[li][3]) ST_F[li][1] = fminf(1.0f, ST_F[li][1] + inp * 0.6f);
    else ST_F[li][3] = fminf(1.0f, ST_F[li][3] + inp * 0.6f);
  }
}

static inline void evalMemoryHeatmap(int li, int i, float br, float wd, float &r, float &g, float &b) {
  r=g=b=0.0f;
  float sigma = 1.0f + clamp01(wd) * (float)NUM_LEDS * 0.08f;
  float d0 = fabsf((float)i - ST_F[li][0]);
  float d1 = fabsf((float)i - ST_F[li][2]);
  float a0 = _gauss1(d0, sigma) * clamp01(ST_F[li][1]);
  float a1 = _gauss1(d1, sigma) * clamp01(ST_F[li][3]);
  float a  = fminf(1.0f, a0 + a1);
  // heat palette: blue -> red
  r = (40.0f + 215.0f * a) * br;
  g = (20.0f +  40.0f * (1.0f-a)) * br;
  b = (200.0f * (1.0f-a)) * br;
}

static inline void evalAmbientDashboard(int li, int i, float t, float br, float pf0, float pf1, float pf2, float pf3, float &r, float &g, float &b) {
  // Segment the strip into 4 bands showing pf0..pf3 (0..1).
  // Background is a slow hue drift between primary and secondary colors.
  float u = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS-1));
  float drift = 0.5f + 0.5f * sinf(t * 0.25f);
  float bgR = ((1.0f-drift) * (float)L_R[li] + drift * (float)L_R2[li]) * 0.15f;
  float bgG = ((1.0f-drift) * (float)L_G[li] + drift * (float)L_G2[li]) * 0.15f;
  float bgB = ((1.0f-drift) * (float)L_B[li] + drift * (float)L_B2[li]) * 0.15f;

  float v = 0.0f;
  if (u < 0.25f) v = clamp01(pf0);
  else if (u < 0.50f) v = clamp01(pf1);
  else if (u < 0.75f) v = clamp01(pf2);
  else v = clamp01(pf3);

  // indicator color: bright white scaled by v
  float ind = v;
  r = (bgR + 255.0f * ind) * br;
  g = (bgG + 255.0f * ind) * br;
  b = (bgB + 255.0f * ind) * br;
}

static inline void evalSparkle(int li, int i, float t, float br, float dn, float &r, float &g, float &b) {{
  // dn is density 0..1; sparkle chance per frame per led
  // use hashed RNG based on led and time bucket
  uint32_t bucket = (uint32_t)(t * 30.0f); // 30fps-ish bucket
  uint32_t h = (uint32_t)i * 2654435761u ^ bucket * 2246822519u ^ 0x9E3779B9u;
  h ^= h >> 16; h *= 2246822519u; h ^= h >> 13; h *= 3266489917u; h ^= h >> 16;
  float u = (float)(h & 0xFFFFu) / 65535.0f;
  float a = (u < dn) ? 1.0f : 0.0f;
  r = (float)L_R[li] * br * a;
  g = (float)L_G[li] * br * a;
  b = (float)L_B[li] * br * a;
}}

static inline float smoothstep(float x) {{
  x = clamp01(x);
  return x*x*(3.0f - 2.0f*x);
}}

static inline void evalScanner(int li, int i, float t, float br, float sp, float wd, float so, float dir, float &r, float &g, float &b) {{
  float phase = fmodf(t * fmaxf(0.2f, sp), 1.0f);
  float tri = 1.0f - fabsf(2.0f*phase - 1.0f);
  float pos01 = (dir >= 0.0f) ? tri : (1.0f - tri);
  float pos = pos01 * (float)(NUM_LEDS - 1);
  float halfw = fmaxf(0.5f, wd * (float)NUM_LEDS * 0.5f);
  float d = fabsf((float)i - pos);
  float a = 0.0f;
  if (d <= halfw) {{
    if (so <= 0.001f) a = 1.0f;
    else {{
      float x = 1.0f - (d / halfw);
      a = (1.0f - so) * 1.0f + so * smoothstep(x);
    }}
  }}
  r = (float)L_R[li] * br * a;
  g = (float)L_G[li] * br * a;
  b = (float)L_B[li] * br * a;
}}

#ifndef MODULO_PROFILE
#define MODULO_PROFILE 0
#endif

#if MODULO_PROFILE
static uint32_t PROF_LAST_US = 0;
static uint32_t PROF_PIXELS_US = 0;
static uint32_t PROF_FRAME = 0;
#endif

static uint32_t __last_ms = 0;
static float    __accum_s = 0.0f;
static const float __FIXED_DT = 1.0f/60.0f;

static uint8_t LAST_BEH[LAYERS];

void setup() {{
  if (DBG_PURPOSE_SERIAL) {{
    Serial.begin(DBG_SERIAL_BAUD);
    delay(10);
  }}

  modulo_led_init();
  msgeq7_setup();
  modulo_wifi_init();
}}

void loop() {{
  unsigned long now = millis();
#if MODULO_PROFILE
  uint32_t __prof_loop0 = micros();
  uint32_t __prof_pix0 = 0;
#endif
  modulo_wifi_tick();
  float t = (float)now / 1000.0f;
  msgeq7_read();

  // Reset per-frame rule-driven runtime overrides
#if MODULA_POSTFX_ENABLED
  PFX_TRAIL_RT = PFX_TRAIL_BASE; PFX_TRAIL_SET = false;
  PFX_BLEED_RT = PFX_BLEED_BASE; PFX_BLEED_SET = false;
  PFX_BLEED_R_RT = PFX_BLEED_R_BASE; PFX_BLEED_R_SET = false;
#endif
  for (int li=0; li<LAYERS; li++) {{
    L_OP_RT[li] = L_OP[li]; L_OP_SET[li] = false;
    L_BR_RT[li] = L_BR[li]; L_BR_SET[li] = false;
    // Operator param runtime overrides (Rules: operator.gain)
    for (int oi=0; oi<OPS_PER_LAYER; oi++) {{
      int idx = li * OPS_PER_LAYER + oi;
      OP_P0_RT[idx] = OP_P0[idx];
      OP_P0_SET[idx] = false;
    }}
  }}

{rules_apply}

  for (int i=0; i<NUM_LEDS; i++) {{
#if MODULO_PROFILE
  __prof_pix0 = micros();
#endif
    float outR = 0.0f, outG = 0.0f, outB = 0.0f;

    for (int li=0; li<LAYERS; li++) {{
      if (!targetContains((uint16_t)i, L_TGT_KIND[li], L_TGT_REF[li])) continue;

      float br, sp, wd, so, dn, dir;
      float pf0=0.0f, pf1=0.0f, pf2=0.0f, pf3=0.0f;
      float pi0=0.0f, pi1=0.0f, pi2=0.0f, pi3=0.0f;
      computeLayerParams(li, t, br, sp, wd, so, dn, dir, pf0, pf1, pf2, pf3, pi0, pi1, pi2, pi3);

      float lr=0.0f, lg=0.0f, lb=0.0f;
      uint8_t beh = L_BEH[li];
      if (beh == 0) evalSolid(li, br, lr, lg, lb);
      else if (beh == 8) evalBouncer(li, i, br, sp, wd, lr, lg, lb);
      else if (beh == 5) evalFade(li, t, br, sp, lr, lg, lb);
      else if (beh == 6) evalStrobe(li, t, br, sp, L_DUTY[li], lr, lg, lb);
      else if (beh == 7) evalRainbow(li, i, t, br, sp, L_HUEOFF[li], L_HUESPAN[li], lr, lg, lb);
      else if (beh == 11) evalTilemapSprite(li, i, t, br, sp, pf0, pf1, lr, lg, lb);
      else if (beh == 12) evalCACluster(li, i, t, br, sp, pf1, pf2, pf3, lr, lg, lb);
      else if (beh == 13) evalMSGEQ7(li, i, t, br, sp, pf1, lr, lg, lb);
      else if (beh == 9) evalBreakout(li, i, br, wd, so, dn, lr, lg, lb);
      else if (beh == 10) evalAsteroids(li, i, br, so, dn, lr, lg, lb);
      else if (beh == 14) evalSnakeLite(li, i, br, lr, lg, lb);
      else if (beh == 15) evalInvadersLite(li, i, br, lr, lg, lb);
      else if (beh == 16) evalShooterLite(li, i, br, lr, lg, lb);
      else if (beh == 17) evalBlocksBallLite(li, i, br, lr, lg, lb);
      else if (beh == 18) evalBoidsSwarm(li, i, t, br, sp, wd, dn, lr, lg, lb);
      else if (beh == 19) evalPredatorPrey(li, i, br, lr, lg, lb);
      else if (beh == 20) evalMemoryHeatmap(li, i, br, wd, lr, lg, lb);
      else if (beh == 21) evalAmbientDashboard(li, i, t, br, pf0, pf1, pf2, pf3, lr, lg, lb);
      else if (beh == 22) evalKernelDSL(li, i, t, br, (uint32_t)L_PI1[li], lr, lg, lb);
      else if (beh == 23) evalWriteLoop(li, i, t, dt, br, (uint32_t)L_PI1[li], pf0, pf1, pf2, pf3, lr, lg, lb);
      else if (beh == 1) evalChase(li, i, t, br, sp, wd, dir, lr, lg, lb);
      else if (beh == 2) evalWipe(li, i, t, br, sp, so, dir, lr, lg, lb);
      else if (beh == 3) evalSparkle(li, i, t, br, dn, lr, lg, lb);
      else if (beh == 4) evalScanner(li, i, t, br, sp, wd, so, dir, lr, lg, lb);
      else evalSolid(li, br, lr, lg, lb);

      // Apply per-layer operators before blend/opacity
      apply_layer_operators(li, lr, lg, lb);

      float op = clamp01(L_OP_RT[li]);

      float blendedR = blendChan(outR, lr, L_BLEND[li]);
      float blendedG = blendChan(outG, lg, L_BLEND[li]);
      float blendedB = blendChan(outB, lb, L_BLEND[li]);

      outR = outR * (1.0f - op) + blendedR * op;
      outG = outG * (1.0f - op) + blendedG * op;
      outB = outB * (1.0f - op) + blendedB * op;
    }}

    leds[i] = CRGB((uint8_t)clamp01(outR/255.0f)*255, (uint8_t)clamp01(outG/255.0f)*255, (uint8_t)clamp01(outB/255.0f)*255);
  }}

{postfx_apply}
  modulo_led_show();

#if MODULO_PROFILE
  PROF_PIXELS_US = (uint32_t)(micros() - __prof_pix0);
  PROF_LAST_US = (uint32_t)(micros() - __prof_loop0);
  PROF_FRAME++;
  if (DBG_PURPOSE_SERIAL && (PROF_FRAME % 60u == 0u)) {
    Serial.print("[Modulo] frame_us="); Serial.print(PROF_LAST_US);
    Serial.print(" pixels_us="); Serial.print(PROF_PIXELS_US);
    Serial.print(" fps_est=");
    if (PROF_LAST_US > 0) Serial.println(1000000.0f / (float)PROF_LAST_US); else Serial.println(0);
  }
#endif

}}
'''


def render_layerstack_sketch(context: dict) -> str:
    """Render the final layerstack sketch from a prepared export context."""
    import re

    values = dict(context)
    values.setdefault("EXPORT_MARKER", EXPORT_MARKER)

    def repl(match: re.Match[str]) -> str:
        expr = match.group(1).strip()
        if expr == "1 if DBG_PURPOSE else 0":
            return str(1 if bool(values.get("DBG_PURPOSE")) else 0)
        if expr == "int(num_leds)":
            return str(int(values.get("num_leds", 0)))
        if expr == "int(led_pin)":
            return str(int(values.get("led_pin", 0)))
        if expr.startswith("csv_values(") and expr.endswith(")"):
            key = expr[len("csv_values("):-1].strip()
            return csv_values(values.get(key, []))
        if expr in values:
            return str(values[expr])
        low = expr.lower()
        if low in values:
            return str(values[low])
        return match.group(0)

    sketch = re.sub(r"\{([^{}]+)\}", repl, TEMPLATE)
    return sketch
