from __future__ import annotations

from qt.qt_compat import QtCore, QtWidgets  # type: ignore


class OperatorsTabUiMixin:
    def _build_ui(self):
        root = QtWidgets.QVBoxLayout(self)
        root.addWidget(QtWidgets.QLabel('Operator Stack — operators process the composed layer output in order.'))
        root.setContentsMargins(0, 0, 0, 0)

        intro = QtWidgets.QLabel("Operators shape the result after Signals, Variables, and Rules are in place. This UI exposes stable canonical project.postfx controls.")
        intro.setWordWrap(True)
        root.addWidget(intro)

        self.grp_operator_gate = QtWidgets.QGroupBox("Historical Operator Gate")
        og = QtWidgets.QVBoxLayout(self.grp_operator_gate)
        self.lbl_operator_gate = QtWidgets.QLabel("")
        self.lbl_operator_gate.setWordWrap(True)
        og.addWidget(self.lbl_operator_gate)
        root.addWidget(self.grp_operator_gate)
        step = QtWidgets.QLabel("Shape the composed result before verification and export.")
        step.setStyleSheet("font-weight:600;")
        root.addWidget(step)
        summary = QtWidgets.QLabel("Workflow Summary: operators shape the composed output after the project logic and layer stack are already in place.")
        summary.setWordWrap(True)
        root.addWidget(summary)
        quick = QtWidgets.QLabel("Quick Tip: Operators modify the final output before it reaches the LEDs.")
        quick.setWordWrap(True)
        root.addWidget(quick)
        stage_hint = QtWidgets.QLabel("Operator Stage: Layers → Composition → Operators → Hardware Output")
        stage_hint.setWordWrap(True)
        root.addWidget(stage_hint)

        helpers = QtWidgets.QGroupBox("Operator Helpers")
        hlay = QtWidgets.QHBoxLayout(helpers)
        self.btn_trail_preset = QtWidgets.QPushButton("Trail Preset")
        self.btn_bleed_preset = QtWidgets.QPushButton("Bleed Preset")
        self.btn_clear_postfx = QtWidgets.QPushButton("Clear PostFX")
        hlay.addWidget(self.btn_trail_preset)
        hlay.addWidget(self.btn_bleed_preset)
        hlay.addWidget(self.btn_clear_postfx)
        hlay.addStretch(1)
        root.addWidget(helpers)
        helper_note = QtWidgets.QLabel("Operator Helpers: preset buttons write canonical postfx values. You can still edit the raw canonical JSON below for full control.")
        helper_note.setWordWrap(True)
        root.addWidget(helper_note)
        self.grp_active_ops = QtWidgets.QGroupBox("Active Operators")
        ops_box = QtWidgets.QVBoxLayout(self.grp_active_ops)

        add_row = QtWidgets.QHBoxLayout()
        self.cmb_add_operator = QtWidgets.QComboBox()
        add_row.addWidget(self.cmb_add_operator, 1)
        self.btn_add_operator = QtWidgets.QPushButton("Add Operator Key")
        add_row.addWidget(self.btn_add_operator)
        ops_box.addLayout(add_row)

        self.list_ops = QtWidgets.QListWidget(); ops_box.addWidget(self.list_ops, 1)
        self.btn_move_up = QtWidgets.QPushButton("Move Up")
        self.btn_move_down = QtWidgets.QPushButton("Move Down")
        edit_row = QtWidgets.QHBoxLayout()
        self.btn_remove_operator = QtWidgets.QPushButton("Remove Selected Key")
        edit_row.addWidget(self.btn_remove_operator)
        edit_row.addWidget(self.btn_move_up)
        edit_row.addWidget(self.btn_move_down)
        edit_row.addStretch(1)
        ops_box.addLayout(edit_row)

        self.lbl_ops_info = QtWidgets.QLabel("These are active canonical postfx keys. This UI edits the real project.postfx object; operator execution ordering is not changed here.")
        self.lbl_ops_info.setWordWrap(True)
        ops_box.addWidget(self.lbl_ops_info)
        root.addWidget(self.grp_active_ops)

        self.grp_operator_address = QtWidgets.QGroupBox("Canonical Address")
        addr_box = QtWidgets.QVBoxLayout(self.grp_operator_address)
        self.lbl_operator_addr = QtWidgets.QLabel("Read-only canonical address for the selected operator key.")
        self.lbl_operator_addr.setWordWrap(True)
        addr_box.addWidget(self.lbl_operator_addr)
        self.txt_operator_addr = QtWidgets.QLineEdit(); self.txt_operator_addr.setReadOnly(True)
        addr_box.addWidget(self.txt_operator_addr)
        root.addWidget(self.grp_operator_address)

        self.grp_operator_editor = QtWidgets.QGroupBox("Selected Operator Value")
        editor_box = QtWidgets.QVBoxLayout(self.grp_operator_editor)
        self.lbl_operator_editor = QtWidgets.QLabel("Edit the selected canonical operator key here.")
        self.lbl_operator_editor.setWordWrap(True)
        editor_box.addWidget(self.lbl_operator_editor)

        self.operator_value_stack = QtWidgets.QStackedWidget()
        self.op_value_float = QtWidgets.QDoubleSpinBox(); self.op_value_float.setDecimals(3); self.op_value_float.setRange(-999999.0, 999999.0); self.op_value_float.setSingleStep(0.05)
        self.op_value_int = QtWidgets.QSpinBox(); self.op_value_int.setRange(-999999, 999999)
        self.op_value_bool = QtWidgets.QCheckBox("Enabled")
        self.op_value_enum = QtWidgets.QComboBox()
        self.op_value_text = QtWidgets.QLineEdit()
        for w in (self.op_value_float, self.op_value_int, self.op_value_bool, self.op_value_enum, self.op_value_text):
            self.operator_value_stack.addWidget(w)
        editor_box.addWidget(self.operator_value_stack)
        self.btn_apply_operator_value = QtWidgets.QPushButton("Apply Selected Operator Value")
        editor_box.addWidget(self.btn_apply_operator_value)
        root.addWidget(self.grp_operator_editor)

        root.addWidget(QtWidgets.QLabel("Full Power: operator keys map directly to canonical project.postfx addresses used by the engine."))
        next_step = QtWidgets.QLabel("Next: use Diagnostics to verify wiring and parity, then Export for hardware output.")
        next_step.setWordWrap(True)
        root.addWidget(next_step)

        bar = QtWidgets.QHBoxLayout(); root.addLayout(bar)
        self.btn_reload = QtWidgets.QPushButton("Reload")
        self.btn_apply = QtWidgets.QPushButton("Apply"); self.btn_apply.setToolTip("Applies JSON into project.postfx")
        bar.addWidget(self.btn_reload); bar.addWidget(self.btn_apply); bar.addStretch(1)
        self.txt = QtWidgets.QPlainTextEdit(); self.txt.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        root.addWidget(self.txt, 1)
        self.lbl = QtWidgets.QLabel("Note: This is a minimal stable Operators view. Only canonical postfx keys are accepted here; unknown keys are rejected.")
        self.lbl.setWordWrap(True)
        root.addWidget(self.lbl)

        self.btn_reload.clicked.connect(self.reload)
        self.btn_apply.clicked.connect(self.apply)
        self.btn_trail_preset.clicked.connect(self._apply_trail_preset)
        self.btn_bleed_preset.clicked.connect(self._apply_bleed_preset)
        self.btn_clear_postfx.clicked.connect(self._clear_postfx)
        self.btn_add_operator.clicked.connect(self._add_operator_key)
        self.btn_remove_operator.clicked.connect(self._remove_selected_operator_key)
        self.btn_move_up.clicked.connect(self._move_operator_up)
        self.btn_move_down.clicked.connect(self._move_operator_down)
        self.list_ops.currentRowChanged.connect(self._select_operator_key)
        self.btn_apply_operator_value.clicked.connect(self._apply_selected_operator_value)

        QtCore.QTimer.singleShot(0, self.reload)
        QtCore.QTimer.singleShot(0, self._populate_operator_choices)
        self.btn_apply_operator_value.setEnabled(False)
        QtCore.QTimer.singleShot(0, self._apply_operator_gate)
