from __future__ import annotations
SHIPPED = True

from typing import List, Tuple

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int, int, int]


def _clamp01(x: float) -> float:
    try:
        x = float(x)
    except Exception:
        x = 0.0
    if x < 0.0:
        return 0.0
    if x > 1.0:
        return 1.0
    return x


def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    """Fill all pixels with a single color scaled by `level`.

    Intended usage:
    - A Rules v6 tick rule routes `audio.energy` into params['level'].
    """
    n = max(1, int(num_leds))

    # Base RGB (defaults to a readable green)
    c = params.get("color", (0, 255, 0))
    try:
        r, g, b = int(c[0]) & 255, int(c[1]) & 255, int(c[2]) & 255
    except Exception:
        r, g, b = 0, 255, 0

    level = _clamp01(params.get("level", 0.15))
    # Optional shaping for visibility at low levels
    gamma = float(params.get("gamma", 1.8))
    try:
        level_shaped = level ** gamma
    except Exception:
        level_shaped = level

    rr = int(r * level_shaped) & 255
    gg = int(g * level_shaped) & 255
    bb = int(b * level_shaped) & 255
    px = (rr, gg, bb)
    return [px] * n


def _arduino_emit(*, layout: dict, params: dict) -> str:
    """Firmware export: MSGEQ7 energy meter (fills all pixels).

    - On targets without MSGEQ7 wired, the meter will sit near zero.
    - Kept intentionally simple: a single scalar level drives RGB scaling.
    """
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    c = params.get("color", (0, 255, 0))
    try: r,g,b = int(c[0]) & 255, int(c[1]) & 255, int(c[2]) & 255
    except Exception: r,g,b = 0,255,0
    gamma = float(params.get("gamma", 1.8) or 1.8)
    # MSGEQ7 default pins (kept consistent with other exports)
    resetPin = 5
    strobePin = 4
    monoPin = "A0"
    # smoothing
    alpha = float(params.get("softness", 0.35) or 0.35)
    if alpha < 0.02: alpha = 0.02
    if alpha > 0.85: alpha = 0.85

    return f"""// Generated by Modulo (Audio Meter)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

const int RESET_PIN = {resetPin};
const int STROBE_PIN = {strobePin};
const int MONO_PIN = {monoPin};

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

float energy = 0.0f;

void msgeq7_setup() {{
  pinMode(RESET_PIN, OUTPUT);
  pinMode(STROBE_PIN, OUTPUT);
  digitalWrite(RESET_PIN, LOW);
  digitalWrite(STROBE_PIN, HIGH);
}}

static inline void msgeq7_read(float* out7) {{
  digitalWrite(RESET_PIN, HIGH);
  delayMicroseconds(100);
  digitalWrite(RESET_PIN, LOW);
  delayMicroseconds(100);

  for (int i=0; i<7; i++) {{
    digitalWrite(STROBE_PIN, LOW);
    delayMicroseconds(30);
    int v = analogRead(MONO_PIN);
    digitalWrite(STROBE_PIN, HIGH);
    delayMicroseconds(30);

    // normalize approx 0..1023 to 0..1
    float x = (float)v / 1023.0f;
    out7[i] = clamp01(x);
  }}
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
  msgeq7_setup();
}}

void loop() {{
  float bands[7];
  msgeq7_read(bands);

  // energy as mean of bands
  float e = 0.0f;
  for (int i=0; i<7; i++) e += bands[i];
  e *= (1.0f/7.0f);

  // simple smoothing
  energy = (1.0f - (float){alpha}f) * energy + (float){alpha}f * e;
  float level = clamp01(energy);

  // gamma shaping
  float shaped = powf(level, (float){gamma}f);

  uint8_t rr = (uint8_t)clamp01(((float){r})/255.0f * shaped) * 255;
  uint8_t gg = (uint8_t)clamp01(((float){g})/255.0f * shaped) * 255;
  uint8_t bb = (uint8_t)clamp01(((float){b})/255.0f * shaped) * 255;

  CRGB c = CRGB(rr,gg,bb);
  for (int i=0; i<NUM_LEDS; i++) leds[i] = c;

  FastLED.show();
  delay(10);
}}
"""

def register_audio_meter():
    return register(
        BehaviorDef(
            "audio_meter",
            title="Audio Meter (Preview Utility)",
            uses=["color", "level", "gamma"],
            preview_emit=_preview_emit,
            arduino_emit=_arduino_emit,
        )
    )
