from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _lerp(a: float, b: float, t: float) -> float:
    return a + (b-a)*t

def _noise1(x: float, seed: int) -> float:
    x0 = int(math.floor(x))
    x1 = x0 + 1
    t = x - float(x0)
    v0 = _u01(_hash_u32(x0 ^ seed))
    v1 = _u01(_hash_u32(x1 ^ seed))
    return _lerp(v0, v1, t)

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","width","softness","color"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.55)))       # larger = smoother curtains
    softness = _clamp01(float(params.get("softness", 0.65))) # lower = more contrast
    tint = params.get("color", (80,255,200))                 # used as tint multiply

    if width < 0.10: width = 0.10

    tr,tg,tb = int(tint[0])&255, int(tint[1])&255, int(tint[2])&255

    spatial = 0.20 + (1.0/width) * 0.45
    scroll = t * max(0.1, speed) * 0.5
    contrast = 1.5 - softness * 1.0  # 0.5..1.5-ish

    out: List[RGB] = []
    for i in range(n):
        x = i / max(1.0, (n-1))
        # layered moving noise -> curtain intensity
        v = 0.0
        v += 0.55 * _noise1(x*spatial + scroll*1.0, 777)
        v += 0.30 * _noise1(x*spatial*2.0 + scroll*1.7, 888)
        v += 0.15 * _noise1(x*spatial*4.0 + scroll*3.1, 999)
        v = (v - 0.5) * contrast + 0.5
        v = _clamp01(v)
        # hue varies slowly with x and time, value from v
        hue = (0.55 + 0.25*v + x*0.15 + scroll*0.08) % 1.0
        r,g,b = _hsv_to_rgb(hue, 1.0, br * v)
        # tint multiply
        r = r * tr // 255
        g = g * tg // 255
        b = b * tb // 255
        out.append((r,g,b))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.55))
    softness = float(params.get("softness", 0.65))
    tint = params.get("color", (80,255,200))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.10: width = 0.10
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    tr,tg,tb = int(tint[0])&255, int(tint[1])&255, int(tint[2])&255
    spatial = 0.20 + (1.0/width) * 0.45
    contrast = 1.5 - softness * 1.0
    scroll_speed = max(0.1, speed) * 0.5

    return f"""// Generated by Modulo (Effect: aurora)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline float lerp(float a, float b, float t) {{
  return a + (b-a)*t;
}}

static inline float noise1(float x, uint32_t seed) {{
  int x0 = (int)floorf(x);
  int x1 = x0 + 1;
  float tt = x - (float)x0;
  float v0 = u01(hash_u32((uint32_t)x0 ^ seed));
  float v1 = u01(hash_u32((uint32_t)x1 ^ seed));
  return lerp(v0, v1, tt);
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float t = (float)now / 1000.0f;
  float br = clamp01((float){br}f);
  float spatial = (float){spatial}f;
  float contrast = (float){contrast}f;
  float scroll = t * (float){scroll_speed}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float v = 0.0f;
    v += 0.55f * noise1(x*spatial + scroll*1.0f, 777u);
    v += 0.30f * noise1(x*spatial*2.0f + scroll*1.7f, 888u);
    v += 0.15f * noise1(x*spatial*4.0f + scroll*3.1f, 999u);
    v = (v - 0.5f) * contrast + 0.5f;
    v = clamp01(v);

    float hue = fmodf(0.55f + 0.25f*v + x*0.15f + scroll*0.08f, 1.0f);
    uint8_t r,g,b;
    hsv_to_rgb(hue, 1.0f, br * v, &r, &g, &b);

    // tint multiply
    r = (uint8_t)((uint16_t)r * (uint16_t){tr} / 255u);
    g = (uint8_t)((uint16_t)g * (uint16_t){tg} / 255u);
    b = (uint8_t)((uint16_t)b * (uint16_t){tb} / 255u);

    leds[i] = CRGB(r,g,b);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_aurora():
    return register(BehaviorDef(
        "aurora",
        title="Aurora (Curtains)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
