from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]
USES = ["brightness","speed","softness","density","width"]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _preview_emit(*, num_leds: int, params: dict, t: float, state=None) -> List[RGB]:
    n=max(1,int(num_leds))
    br=_clamp01(float(params.get("brightness",1.0)))
    softness=_clamp01(float(params.get("softness",0.45)))
    density=_clamp01(float(params.get("density",0.55))) # sensitivity
    width=_clamp01(float(params.get("width",0.35)))     # strobe length
    if width < 0.05: width = 0.05

    ev = (params.get("_audio_events") or {})
    beat = float(ev.get("beat", 0.0) or 0.0)

    if state is None or not isinstance(state, dict):
        state={"flash":0.0}
    # on beat, recharge flash
    if beat > 0.5:
        state["flash"] = 1.0
    # decay flash
    decay = 0.10 + 0.60*(1.0-softness) + 0.25*(1.0-density)
    state["flash"] = max(0.0, state["flash"] - decay*(1.0/60.0))

    v = br * (state["flash"] ** (0.55 + 2.5*softness))
    on = (255,255,255)
    off = (0,0,0)
    out=[]
    for i in range(n):
        # width shapes ends
        x = i/max(1.0,(n-1))
        edge = (x*(1.0-x))
        gate = edge ** (0.15 + 1.4*(1.0-width))
        vv = v * (0.6 + 0.4*gate)
        if vv < 0.002:
            out.append(off)
        else:
            out.append((int(on[0]*vv), int(on[1]*vv), int(on[2]*vv)))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n=int(layout["num_leds"]); pin=int(layout["led_pin"])
    br=float(params.get("brightness",1.0))
    softness=float(params.get("softness",0.45))
    density=float(params.get("density",0.55))
    width=float(params.get("width",0.35))
    if br<0: br=0.0
    if br>1: br=1.0
    if softness<0: softness=0.0
    if softness>1: softness=1.0
    if density<0: density=0.0
    if density>1: density=1.0
    if width<0.05: width=0.05
    if width>1: width=1.0

    # Use mono beat from energy delta
    alpha = 0.10 + 0.35*softness
    decay = 0.10 + 0.60*(1.0-softness) + 0.25*(1.0-density)

    return f"""// Generated by Modulo (Beat Strobe)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

// MSGEQ7 pins (default)
const int RESET_PIN = 5;
const int STROBE_PIN = 4;
const int LEFT_PIN = A0;
const int RIGHT_PIN = A1;

float mono=0.0f, mono_prev=0.0f, mono_peak=0.0f;
int mono_cd=0;
float flash=0.0f;

static inline float clamp01(float x) {{
  if (x<0.0f) return 0.0f;
  if (x>1.0f) return 1.0f;
  return x;
}}
static inline float read01(int pin) {{
  int v=analogRead(pin);
  return clamp01((float)v/1023.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
  pinMode(RESET_PIN, OUTPUT);
  pinMode(STROBE_PIN, OUTPUT);
  digitalWrite(RESET_PIN, LOW);
  digitalWrite(STROBE_PIN, HIGH);
}}

void loop() {{
  // mono energy
  float le=0.0f,re=0.0f;
  digitalWrite(RESET_PIN, HIGH); delayMicroseconds(5); digitalWrite(RESET_PIN, LOW);
  for (int i=0;i<7;i++) {{
    digitalWrite(STROBE_PIN, LOW); delayMicroseconds(30);
    le += read01(LEFT_PIN);
    re += read01(RIGHT_PIN);
    digitalWrite(STROBE_PIN, HIGH);
  }}
  le/=7.0f; re/=7.0f;
  float em=0.5f*(le+re);

  mono_prev = mono;
  mono = (1.0f-{alpha}f)*mono + {alpha}f*em;
  float md = mono - mono_prev;
  mono_peak = fmaxf(mono_peak - 0.020f, mono);
  float thr = 0.05f + mono_peak*0.20f;

  bool beat=false;
  if (mono_cd>0) mono_cd--;
  else {{
    if (md > thr) {{ beat=true; mono_cd=4; }}
  }}

  if (beat) flash=1.0f;
  flash = fmaxf(0.0f, flash - {decay}f*(1.0f/60.0f));

  float br = clamp01((float){br}f);
  float softness = clamp01((float){softness}f);
  float width = clamp01((float){width}f);

  float v = br * powf(flash, (0.55f + 2.5f*softness));

  for (int i=0;i<NUM_LEDS;i++) {{
    float x=(NUM_LEDS<=1)?0.0f:((float)i/(float)(NUM_LEDS-1));
    float edge = x*(1.0f-x);
    float gate = powf(edge, (0.15f + 1.4f*(1.0f-width)));
    float vv = v*(0.6f + 0.4f*gate);
    uint8_t c=(uint8_t)fminf(255.0f, 255.0f*vv);
    leds[i]=CRGB(c,c,c);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_beat_strobe():
    return register(BehaviorDef(
        "beat_strobe",
        title="Beat Strobe (Audio Events)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
