from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","softness","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = float(params.get("speed", 1.0))
    softness = _clamp01(float(params.get("softness", 0.5)))
    width = _clamp01(float(params.get("width", 0.25)))  # palette spread along strip
    if width < 0.05: width = 0.05

    # bpm in cycles/sec
    cps = max(0.1, speed) * 0.45
    u = (t * cps) % 1.0
    beat = 0.5 - 0.5*math.cos(2.0*math.pi*u)
    exp = 0.8 + softness * 2.2
    a = pow(beat, exp)

    out: List[RGB] = []
    for i in range(n):
        x = i / max(1.0, (n-1))
        hue = (x / width + t * 0.08) % 1.0
        r,g,b = _hsv_to_rgb(hue, 1.0, br * (0.25 + 0.75*a))
        out.append((r,g,b))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.5))
    width = float(params.get("width", 0.25))
    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    cps = max(0.1, speed) * 0.45
    period_ms = int(max(400.0, min(20000.0, 1000.0 / cps)))

    return f"""// Generated by Modulo (Effect: bpm)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float u = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float beat = 0.5f - 0.5f * cosf(2.0f * 3.1415926f * u);
  float exp = 0.8f + clamp01((float){softness}f) * 2.2f;
  float a = powf(beat, exp);

  float br = clamp01((float){br}f) * (0.25f + 0.75f*a);
  float width = (float){width}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float hue = fmodf((x / width) + ((float)now/1000.0f)*0.08f, 1.0f);
    uint8_t r,g,b;
    hsv_to_rgb(hue, 1.0f, br, &r, &g, &b);
    leds[i] = CRGB(r,g,b);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_bpm():
    return register(BehaviorDef(
        "bpm",
        title="BPM (Palette Pulse)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
