from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _add(out: RGB, add: RGB) -> RGB:
    return (min(255, out[0]+add[0]), min(255, out[1]+add[1]), min(255, out[2]+add[2]))

USES = ["color","brightness","speed","density","softness","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(120,200,255))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = float(params.get("speed", 1.0))
    density = _clamp01(float(params.get("density", 0.45)))   # comet count
    softness = _clamp01(float(params.get("softness", 0.55))) # tail length
    width = _clamp01(float(params.get("width", 0.18)))       # head size
    if width < 0.03: width = 0.03

    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)

    comet_n = max(3, int(round(3 + density*12)))
    tail = 2.0 + softness*10.0
    head = 0.6 + width*2.5

    out = [(0,0,0) for _ in range(n)]
    for c in range(comet_n):
        h = _hash_u32(c*7331)
        dir_ = -1.0 if (_hash_u32(h ^ 0xBEEF) & 1) else 1.0
        offset = _u01(_hash_u32(h ^ 0xABCD))
        v = _u01(_hash_u32(h ^ 0x1234))
        # speed per comet
        sp = (0.25 + 1.5*v) * max(0.2, speed) * 0.25
        u = (t*sp + offset) % 1.0
        x = u if dir_>0 else (1.0-u)
        idx = x * (n-1 if n>1 else 1)

        for i in range(n):
            d = (i - idx) * dir_  # positive behind head
            if d > 0:
                a = math.exp(-(d*d)/(2.0*tail*tail))
            else:
                a = math.exp(-(d*d)/(2.0*head*head))
            if a < 0.002: 
                continue
            add = (int(base[0]*br*a)&255, int(base[1]*br*a)&255, int(base[2]*br*a)&255)
            out[i] = _add(out[i], add)
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(120,200,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    density = float(params.get("density", 0.45))
    softness = float(params.get("softness", 0.55))
    width = float(params.get("width", 0.18))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.03: width = 0.03
    if width > 1.0: width = 1.0

    r0,g0,b0 = int(col[0])&255, int(col[1])&255, int(col[2])&255
    comet_n = max(3, int(round(3 + density*12.0)))
    tail = 2.0 + softness*10.0
    head = 0.6 + width*2.5
    base_sp = max(0.2, speed) * 0.25

    return f"""// Generated by Modulo (Effect: comet_storm)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float t = (float)now / 1000.0f;
  float br = clamp01((float){br}f);

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  for (int c=0; c<{comet_n}; c++) {{
    uint32_t h = hash_u32((uint32_t)c * 7331u);
    float dir = (hash_u32(h ^ 0x0000BEEFu) & 1u) ? -1.0f : 1.0f;
    float offset = u01(hash_u32(h ^ 0x0000ABCDu));
    float v = u01(hash_u32(h ^ 0x00001234u));
    float sp = (0.25f + 1.5f*v) * (float){base_sp}f;
    float u = fmodf(t*sp + offset, 1.0f);
    float x = (dir > 0.0f) ? u : (1.0f - u);
    float idx = x * (float)(NUM_LEDS - 1);

    for (int i=0; i<NUM_LEDS; i++) {{
      float d = ((float)i - idx) * dir; // positive behind
      float a = (d > 0.0f) ? expf(-(d*d) / (2.0f*(float){tail}f*(float){tail}f)) : expf(-(d*d) / (2.0f*(float){head}f*(float){head}f));
      if (a < 0.002f) continue;
      float k = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, (float){r0}f*k, (float){g0}f*k, (float){b0}f*k);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_comet_storm():
    return register(BehaviorDef(
        "comet_storm",
        title="Comet Storm / Debris",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
