from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","width","softness","density"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n=max(1,int(num_leds))
    br=_clamp01(float(params.get("brightness",1.0)))
    speed=max(0.1,float(params.get("speed",1.0)))
    width=_clamp01(float(params.get("width",0.35)))       # shard size
    softness=_clamp01(float(params.get("softness",0.45))) # edge softness
    density=_clamp01(float(params.get("density",0.55)))   # prism intensity
    if width < 0.05: width = 0.05

    shard = 0.08 + width*0.22
    wob = 0.18 + density*0.55
    edge = 0.6 + softness*2.2

    out=[]
    for i in range(n):
        x = i / max(1.0,(n-1))
        # refractive warp
        w = math.sin(2.0*math.pi*(x*1.7 + t*speed*0.05)) * wob*0.12
        w += math.sin(2.0*math.pi*(x*3.1 - t*speed*0.03)) * wob*0.07
        xx = (x + w) % 1.0
        # shard bands
        k = (xx / shard)
        frac = k - math.floor(k)
        tri = 1.0 - abs(frac*2.0 - 1.0)
        tri = tri ** edge
        hue = (0.58 + xx*0.4 + t*speed*0.04 + tri*0.15) % 1.0
        v = 0.10 + 0.90*tri
        r,g,b=_hsv_to_rgb(hue, 1.0, br*v)
        out.append((r,g,b))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n=int(layout["num_leds"]); pin=int(layout["led_pin"])
    br=float(params.get("brightness",1.0))
    speed=max(0.1,float(params.get("speed",1.0)))
    width=float(params.get("width",0.35))
    softness=float(params.get("softness",0.45))
    density=float(params.get("density",0.55))

    br = 0.0 if br<0.0 else (1.0 if br>1.0 else br)
    softness = 0.0 if softness<0.0 else (1.0 if softness>1.0 else softness)
    density = 0.0 if density<0.0 else (1.0 if density>1.0 else density)
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    shard = 0.08 + width*0.22
    wob = 0.18 + density*0.55
    edge = 0.6 + softness*2.2
    period_ms=int(max(300.0, min(60000.0, 18000.0 / speed)))

    return f"""// Generated by Modulo (Effect: crystal_shards)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float t = phase;

  float br = clamp01((float){br}f);
  float shard = (float){shard}f;
  float wob = (float){wob}f;
  float edge = (float){edge}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS<=1)?0.0f:((float)i/(float)(NUM_LEDS-1));
    float w = sinf(2.0f*3.1415926f*(x*1.7f + t*(float){speed}f*0.05f)) * wob*0.12f;
    w += sinf(2.0f*3.1415926f*(x*3.1f - t*(float){speed}f*0.03f)) * wob*0.07f;
    float xx = fmodf(x + w + 1.0f, 1.0f);

    float k = xx / shard;
    float frac = k - floorf(k);
    float tri = 1.0f - fabsf(frac*2.0f - 1.0f);
    tri = powf(tri, edge);

    float hue = fmodf(0.58f + xx*0.4f + t*(float){speed}f*0.04f + tri*0.15f, 1.0f);
    float v = 0.10f + 0.90f*tri;

    uint8_t r,g,b;
    hsv_to_rgb(hue, 1.0f, br*v, &r,&g,&b);
    leds[i] = CRGB(r,g,b);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_crystal_shards():
    return register(BehaviorDef(
        "crystal_shards",
        title="Crystal Shards",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
