from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255, a[0]+b[0]), min(255, a[1]+b[1]), min(255, a[2]+b[2]))

def _apply(rgb: RGB, k: float) -> RGB:
    k = _clamp01(float(k))
    return (int(rgb[0]*k)&255, int(rgb[1]*k)&255, int(rgb[2]*k)&255)

USES = ["color","brightness","speed","width","softness","density"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    c1 = params.get("color",(200,0,255))
    c1 = (int(c1[0])&255, int(c1[1])&255, int(c1[2])&255)
    c2 = (c1[2], c1[0], c1[1])  # derived
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.25)))      # strand thickness
    softness = _clamp01(float(params.get("softness", 0.6)))  # blur
    density = _clamp01(float(params.get("density", 0.55)))   # twists

    if width < 0.05: width = 0.05
    twists = 1.5 + density * 6.0
    phase = t * max(0.2, speed) * 0.35
    sigma = 0.6 + softness * 3.2
    thick = 0.8 + width * 3.0

    out = [(0,0,0) for _ in range(n)]
    for i in range(n):
        x = i / max(1.0, (n-1))
        a = 2.0*math.pi*(twists*x + phase)
        # two strands positions around center
        p1 = 0.5 + 0.35*math.sin(a)
        p2 = 0.5 + 0.35*math.sin(a + math.pi)
        idx1 = p1 * (n-1 if n>1 else 1)
        idx2 = p2 * (n-1 if n>1 else 1)

        d1 = abs(i - idx1)
        d2 = abs(i - idx2)
        k1 = math.exp(-(d1*d1)/(2.0*sigma*sigma)) * (1.0 / (1.0 + d1/thick))
        k2 = math.exp(-(d2*d2)/(2.0*sigma*sigma)) * (1.0 / (1.0 + d2/thick))

        col = _add(_apply(c1, br*k1), _apply(c2, br*k2))
        out[i] = col
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    c1 = params.get("color",(200,0,255))
    r1,g1,b1 = int(c1[0])&255, int(c1[1])&255, int(c1[2])&255
    r2,g2,b2 = b1, r1, g1

    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.25))
    softness = float(params.get("softness", 0.6))
    density = float(params.get("density", 0.55))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0

    twists = 1.5 + density * 6.0
    sigma = 0.6 + softness * 3.2
    thick = 0.8 + width * 3.0
    period_ms = int(max(600.0, min(60000.0, 20000.0 / max(0.2, speed))))

    return f"""// Generated by Modulo (Effect: dna_helix)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float br = clamp01((float){br}f);

  float twists = (float){twists}f;
  float sigma = (float){sigma}f;
  float thick = (float){thick}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float a = 2.0f * 3.1415926f * (twists*x + phase*0.35f);

    float p1 = 0.5f + 0.35f*sinf(a);
    float p2 = 0.5f + 0.35f*sinf(a + 3.1415926f);

    float idx1 = p1 * (float)(NUM_LEDS - 1);
    float idx2 = p2 * (float)(NUM_LEDS - 1);

    float d1 = fabsf((float)i - idx1);
    float d2 = fabsf((float)i - idx2);

    float k1 = gauss(d1, sigma) * (1.0f / (1.0f + d1/thick));
    float k2 = gauss(d2, sigma) * (1.0f / (1.0f + d2/thick));

    float rr = (float){r1}f * br * k1 + (float){r2}f * br * k2;
    float gg = (float){g1}f * br * k1 + (float){g2}f * br * k2;
    float bb = (float){b1}f * br * k1 + (float){b2}f * br * k2;

    leds[i] = CRGB((uint8_t)fminf(255.0f, rr), (uint8_t)fminf(255.0f, gg), (uint8_t)fminf(255.0f, bb));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_dna_helix():
    return register(BehaviorDef(
        "dna_helix",
        title="DNA Helix (Illusion)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
