from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["brightness","speed","density","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = _clamp01(float(params.get("density", 0.55)))   # burst frequency
    width = _clamp01(float(params.get("width", 0.25)))       # radius
    softness = _clamp01(float(params.get("softness", 0.55))) # fade
    if width < 0.03: width = 0.03

    bursts = 1 + int(round(density*4.0))  # overlapping
    rate = speed*(0.25 + density*1.8)
    bucket = int(t*rate)
    u = (t*rate) - bucket
    rad = 1.0 + width*10.0
    sigma = 0.9 + softness*2.0

    out=[(0,0,0) for _ in range(n)]
    for b in range(bursts):
        h = _hash_u32((bucket-b) ^ (b*1709))
        center = _u01(h) * (n-1 if n>1 else 1)
        hue = _u01(_hash_u32(h ^ 0x1234))
        # age stagger
        age = (u + b*0.22) % 1.0
        # expanding ring
        r = age * rad
        amp = (1.0 - age) ** (1.1 + softness*1.8)

        pr,pg,pb = _hsv_to_rgb(hue, 1.0, 1.0)
        # sparkles along ring
        for i in range(n):
            d = abs(i - center)
            du = abs(d - r)
            a = math.exp(-(du*du)/(2.0*sigma*sigma)) * amp
            if a < 0.002: 
                continue
            out[i]=_add(out[i], (int(pr*br*a), int(pg*br*a), int(pb*br*a)))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n=int(layout["num_leds"])
    pin=int(layout["led_pin"])
    br=float(params.get("brightness",1.0))
    speed=max(0.1,float(params.get("speed",1.0)))
    density=float(params.get("density",0.55))
    width=float(params.get("width",0.25))
    softness=float(params.get("softness",0.55))

    br = 0.0 if br<0.0 else (1.0 if br>1.0 else br)
    density = 0.0 if density<0.0 else (1.0 if density>1.0 else density)
    softness = 0.0 if softness<0.0 else (1.0 if softness>1.0 else softness)
    if width < 0.03: width = 0.03
    if width > 1.0: width = 1.0

    bursts = 1 + int(round(density*4.0))
    rate = speed*(0.25 + density*1.8)
    bucket_ms = int(max(180.0, min(60000.0, 1000.0 / max(0.05, rate))))
    rad = 1.0 + width*10.0
    sigma = 0.9 + softness*2.0

    return f"""// Generated by Modulo (Effect: fireworks)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  float br = clamp01((float){br}f);
  float sigma = (float){sigma}f;
  float rad = (float){rad}f;
  float softness = clamp01((float){softness}f);

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  for (int b=0; b<{bursts}; b++) {{
    uint32_t h = hash_u32(((uint32_t)bucket - (uint32_t)b) ^ (uint32_t)(b*1709));
    float center = u01(h) * (float)(NUM_LEDS - 1);
    float hue = u01(hash_u32(h ^ 0x00001234u));
    float age = fmodf(u + (float)b*0.22f, 1.0f);
    float r = age * rad;
    float amp = powf(1.0f - age, 1.1f + softness*1.8f);

    uint8_t pr,pg,pb;
    hsv_to_rgb(hue, 1.0f, 1.0f, &pr,&pg,&pb);

    for (int i=0; i<NUM_LEDS; i++) {{
      float d = fabsf((float)i - center);
      float du = fabsf(d - r);
      float a = gauss(du, sigma) * amp;
      if (a < 0.002f) continue;
      float kf = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, (float)pr*kf, (float)pg*kf, (float)pb*kf);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_fireworks():
    return register(BehaviorDef(
        "fireworks",
        title="Fireworks",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
