from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","density","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = _clamp01(float(params.get("density", 0.55)))  # glitch rate
    width = _clamp01(float(params.get("width", 0.35)))      # slice size
    softness = _clamp01(float(params.get("softness", 0.45)))# severity
    if width < 0.05: width = 0.05

    # base rainbow wave
    base=[]
    for i in range(n):
        x = i / max(1.0,(n-1))
        hue = (x*0.7 + t*speed*0.08) % 1.0
        v = 0.25 + 0.75*(0.5 - 0.5*math.cos(2.0*math.pi*(x*2.0 + t*speed*0.22)))
        r,g,b = _hsv_to_rgb(hue, 1.0, br*v)
        base.append((r,g,b))

    # glitch slicing
    rate = speed * (0.5 + density*4.0)
    bucket = int(t * rate)
    u = (t * rate) - bucket
    slices = 3 + int(round(1.0/width))  # more slices when width small
    if slices < 3: slices = 3
    if slices > 18: slices = 18

    out = base[:]
    for s in range(slices):
        h = _hash_u32(bucket ^ (s*919))
        if _u01(h) < (0.25 + 0.55*density):
            # apply a random offset to this slice
            off = int(round((_u01(_hash_u32(h ^ 0xBEEF))*2.0 - 1.0) * softness * n * 0.15))
            # swap channels sometimes
            sw = _u01(_hash_u32(h ^ 0x1234))
            i0 = int((s / slices) * n)
            i1 = int(((s+1) / slices) * n)
            for i in range(i0, min(n, i1)):
                j = (i + off) % n
                r,g,b = base[j]
                if sw < 0.33:
                    out[i] = (g,r,b)
                elif sw < 0.66:
                    out[i] = (b,g,r)
                else:
                    out[i] = (r,b,g)
    # occasional line dropout
    if _u01(_hash_u32(bucket ^ 0xFACE)) < 0.15*density:
        cut = int(_u01(_hash_u32(bucket ^ 0xCAFE)) * n)
        for i in range(max(0,cut-2), min(n,cut+2)):
            out[i] = (0,0,0)
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = float(params.get("density", 0.55))
    width = float(params.get("width", 0.35))
    softness = float(params.get("softness", 0.45))

    br = 0.0 if br < 0.0 else (1.0 if br > 1.0 else br)
    density = 0.0 if density < 0.0 else (1.0 if density > 1.0 else density)
    softness = 0.0 if softness < 0.0 else (1.0 if softness > 1.0 else softness)
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    rate = speed * (0.5 + density*4.0)
    bucket_ms = int(max(120.0, min(60000.0, 1000.0 / rate)))
    slices = 3 + int(round(1.0/width))
    if slices < 3: slices = 3
    if slices > 18: slices = 18

    return f"""// Generated by Modulo (Effect: glitch_datamosh)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  float br = clamp01((float){br}f);
  float density = clamp01((float){density}f);
  float softness = clamp01((float){softness}f);

  // base rainbow wave into temp buffer
  static CRGB base[NUM_LEDS];
  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS<=1)?0.0f:((float)i/(float)(NUM_LEDS-1));
    float hue = fmodf(x*0.7f + u*(float){speed}f*0.08f, 1.0f);
    float v = 0.25f + 0.75f*(0.5f - 0.5f*cosf(2.0f*3.1415926f*(x*2.0f + u*(float){speed}f*0.22f)));
    uint8_t r,g,b;
    hsv_to_rgb(hue, 1.0f, br*v, &r,&g,&b);
    base[i] = CRGB(r,g,b);
    leds[i] = base[i];
  }}

  // glitch slicing
  const int slices = {slices};
  for (int s=0; s<slices; s++) {{
    uint32_t h = hash_u32((uint32_t)bucket ^ (uint32_t)(s*919));
    if (u01(h) < (0.25f + 0.55f*density)) {{
      int off = (int)roundf((u01(hash_u32(h ^ 0x0000BEEFu))*2.0f - 1.0f) * softness * (float)NUM_LEDS * 0.15f);
      float sw = u01(hash_u32(h ^ 0x00001234u));
      int i0 = (int)((float)s / (float)slices * (float)NUM_LEDS);
      int i1 = (int)((float)(s+1) / (float)slices * (float)NUM_LEDS);
      for (int i=i0; i<i1 && i<NUM_LEDS; i++) {{
        int j = (i + off) % NUM_LEDS; if (j < 0) j += NUM_LEDS;
        CRGB c = base[j];
        if (sw < 0.33f) leds[i] = CRGB(c.g, c.r, c.b);
        else if (sw < 0.66f) leds[i] = CRGB(c.b, c.g, c.r);
        else leds[i] = CRGB(c.r, c.b, c.g);
      }}
    }}
  }}

  // occasional dropout
  if (u01(hash_u32((uint32_t)bucket ^ 0x0000FACEu)) < 0.15f*density) {{
    int cut = (int)(u01(hash_u32((uint32_t)bucket ^ 0x0000CAFEu)) * (float)NUM_LEDS);
    for (int i=max(0,cut-2); i<min(NUM_LEDS,cut+2); i++) leds[i] = CRGB(0,0,0);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_glitch_datamosh():
    return register(BehaviorDef(
        "glitch_datamosh",
        title="Glitch / Datamosh",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
