from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["brightness","speed","density","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = _clamp01(float(params.get("density", 0.6)))   # star count
    width = _clamp01(float(params.get("width", 0.35)))      # streak length
    softness = _clamp01(float(params.get("softness", 0.45)))# bloom
    if width < 0.05: width = 0.05

    stars = 8 + int(round(density*70.0))   # 8..78
    streak = 0.6 + width*6.0
    sigma = 0.5 + softness*2.5

    out = [(0,0,0) for _ in range(n)]
    rate = 0.35*speed
    bucket = int(t*rate)
    u = (t*rate) - bucket
    for k in range(stars):
        h = _hash_u32(bucket ^ (k*9973))
        x0 = _u01(h)
        v = (0.3 + 1.7*_u01(_hash_u32(h ^ 0xBEEF))) * speed
        pos = (x0 + v*u) % 1.0
        idx = pos * (n-1 if n>1 else 1)
        # head brightness
        head = 0.25 + 0.75*_u01(_hash_u32(h ^ 0x1234))
        # cool white -> blue
        tint = _u01(_hash_u32(h ^ 0x4444))
        pr = int(200 + 55*(1.0-tint))
        pg = int(220 + 35*(1.0-tint))
        pb = 255

        for i in range(n):
            d = idx - i
            if d < 0: d = -d
            # trail behind
            tail = max(0.0, 1.0 - (d / streak))
            a = head * tail * tail
            # bloom
            a *= math.exp(-(d*d)/(2.0*sigma*sigma))
            if a < 0.002:
                continue
            out[i] = _add(out[i], (int(pr*br*a), int(pg*br*a), int(pb*br*a)))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = float(params.get("density", 0.6))
    width = float(params.get("width", 0.35))
    softness = float(params.get("softness", 0.45))

    br = 0.0 if br < 0.0 else (1.0 if br > 1.0 else br)
    density = 0.0 if density < 0.0 else (1.0 if density > 1.0 else density)
    softness = 0.0 if softness < 0.0 else (1.0 if softness > 1.0 else softness)
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    stars = 8 + int(round(density*70.0))
    streak = 0.6 + width*6.0
    sigma = 0.5 + softness*2.5
    rate = 0.35*speed
    bucket_ms = int(max(120.0, min(60000.0, 1000.0 / max(0.05, rate))))

    return f"""// Generated by Modulo (Effect: hyperspace)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  float br = clamp01((float){br}f);
  float sigma = (float){sigma}f;
  float streak = (float){streak}f;

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  for (int k=0; k<{stars}; k++) {{
    uint32_t h = hash_u32((uint32_t)bucket ^ (uint32_t)(k*9973));
    float x0 = u01(h);
    float v = (0.3f + 1.7f*u01(hash_u32(h ^ 0x0000BEEFu))) * (float){speed}f;
    float pos = fmodf(x0 + v*u, 1.0f);
    float idx = pos * (float)(NUM_LEDS - 1);

    float head = 0.25f + 0.75f*u01(hash_u32(h ^ 0x00001234u));
    float tint = u01(hash_u32(h ^ 0x00004444u));
    float pr = 200.0f + 55.0f*(1.0f-tint);
    float pg = 220.0f + 35.0f*(1.0f-tint);
    float pb = 255.0f;

    for (int i=0; i<NUM_LEDS; i++) {{
      float d = fabsf(idx - (float)i);
      float tail = fmaxf(0.0f, 1.0f - (d / streak));
      float a = head * tail * tail;
      a *= gauss(d, sigma);
      if (a < 0.002f) continue;
      float kf = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, pr*kf, pg*kf, pb*kf);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_hyperspace():
    return register(BehaviorDef(
        "hyperspace",
        title="Hyperspace",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
