from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["color","brightness","speed","density","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(255,120,220))
    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = _clamp01(float(params.get("density", 0.55))) # impacts per second
    width = _clamp01(float(params.get("width", 0.2)))      # ring thickness
    softness = _clamp01(float(params.get("softness", 0.6)))# falloff

    if width < 0.02: width = 0.02
    impacts = 1 + int(round(1 + density*5.0))
    bps = speed * (0.4 + density*1.6)
    bucket = int(t * bps)
    u = (t * bps) - bucket
    sigma = 0.02 + width*(0.18 + softness*0.85)

    out = [(0,0,0) for _ in range(n)]
    for j in range(impacts):
        h = _hash_u32((bucket-j) ^ (j*131))
        center = _u01(h)
        # ripple age: staggered
        age = u + j*(0.15 + 0.25*(1.0-density))
        age = age % 1.0
        r = age * 0.75
        a0 = (1.0 - 0.6*age)

        for i in range(n):
            x = i / max(1.0, (n-1))
            d = abs(x - center)
            du = abs(d - r)
            a = math.exp(-(du*du)/(2.0*sigma*sigma)) * a0
            if a < 0.002: 
                continue
            add = (int(base[0]*br*a), int(base[1]*br*a), int(base[2]*br*a))
            out[i] = _add(out[i], (min(255,add[0]),min(255,add[1]),min(255,add[2])))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,120,220))
    r0,g0,b0 = int(col[0])&255, int(col[1])&255, int(col[2])&255
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = float(params.get("density", 0.55))
    width = float(params.get("width", 0.2))
    softness = float(params.get("softness", 0.6))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if width < 0.02: width = 0.02
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    impacts = 1 + int(round(1 + density*5.0))
    bps = speed * (0.4 + density*1.6)
    bucket_ms = int(max(180.0, min(60000.0, 1000.0 / bps)))
    sigma = 0.02 + width*(0.18 + softness*0.85)

    return f"""// Generated by Modulo (Effect: impact_ripples)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  float br = clamp01((float){br}f);
  float density = clamp01((float){density}f);
  float sigma = (float){sigma}f;

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  for (int j=0; j<{impacts}; j++) {{
    uint32_t h = hash_u32(((uint32_t)bucket - (uint32_t)j) ^ (uint32_t)(j*131));
    float center = u01(h);
    float age = fmodf(u + (float)j*(0.15f + 0.25f*(1.0f-density)), 1.0f);
    float r = age * 0.75f;
    float a0 = (1.0f - 0.6f*age);

    for (int i=0; i<NUM_LEDS; i++) {{
      float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
      float d = fabsf(x - center);
      float du = fabsf(d - r);
      float a = gauss(du, sigma) * a0;
      if (a < 0.002f) continue;
      float k = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, (float){r0}f*k, (float){g0}f*k, (float){b0}f*k);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_impact_ripples():
    return register(BehaviorDef(
        "impact_ripples",
        title="Impact Ripples",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
