from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","density","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    density = _clamp01(float(params.get("density", 0.25)))   # chance of flash per bucket
    softness = _clamp01(float(params.get("softness", 0.35))) # decay

    base = _apply_brightness((int(col[0])&255, int(col[1])&255, int(col[2])&255), br)

    # buckets per second
    bps = max(0.2, speed) * 3.5
    b = int(t * bps)
    u = (t * bps) - float(b)

    h = _hash_u32(b ^ 0xA11CE)
    chance = _u01(h)
    if chance > density:
        return [(0,0,0) for _ in range(n)]

    # flashes: 1..4 pulses within a bucket
    pulses = 1 + int(_u01(_hash_u32(h ^ 0xBEEF)) * 4.0)
    # pulse schedule
    a = 0.0
    decay = 0.08 + softness * 0.22
    for p in range(pulses):
        ph = _u01(_hash_u32(h ^ (p*9973)))
        dt = abs(u - ph)
        # small window around ph
        if dt < decay:
            k = 1.0 - (dt / decay)
            a = max(a, k*k)

    rgb = (int(base[0]*a)&255, int(base[1]*a)&255, int(base[2]*a)&255)
    return [rgb for _ in range(n)]

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    density = float(params.get("density", 0.25))
    softness = float(params.get("softness", 0.35))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    r0 = int(int(col[0]) * br) & 255
    g0 = int(int(col[1]) * br) & 255
    b0 = int(int(col[2]) * br) & 255

    bps = max(0.2, speed) * 3.5
    bucket_ms = int(max(60.0, min(3000.0, 1000.0 / bps)))
    decay = 0.08 + softness * 0.22
    decay_ms = int(max(10.0, float(bucket_ms) * decay))

    return f"""// Generated by Modulo (Effect: lightning)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  uint32_t h = hash_u32((uint32_t)bucket ^ 0x00A11CEu);
  float chance = u01(h);
  float a = 0.0f;

  if (chance <= (float){density}f) {{
    int pulses = 1 + (int)(u01(hash_u32(h ^ 0x0000BEEFu)) * 4.0f);
    for (int p=0; p<pulses; p++) {{
      float ph = u01(hash_u32(h ^ (uint32_t)(p*9973)));
      float dt = fabsf(u - ph);
      if (dt * (float){bucket_ms} <= (float){decay_ms}) {{
        float k = 1.0f - (dt * (float){bucket_ms}) / (float){decay_ms};
        float kk = k*k;
        if (kk > a) a = kk;
      }}
    }}
  }}

  uint8_t r = (uint8_t)fminf(255.0f, (float){r0}f * a);
  uint8_t g = (uint8_t)fminf(255.0f, (float){g0}f * a);
  uint8_t b = (uint8_t)fminf(255.0f, (float){b0}f * a);

  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = CRGB(r,g,b);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_lightning():
    return register(BehaviorDef(
        "lightning",
        title="Lightning / Flash",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
