from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _lerp(a: float, b: float, t: float) -> float:
    return a + (b-a)*t

def _noise1(x: float, seed: int) -> float:
    x0 = int(math.floor(x))
    x1 = x0 + 1
    t = x - float(x0)
    v0 = _u01(_hash_u32(x0 ^ seed))
    v1 = _u01(_hash_u32(x1 ^ seed))
    return _lerp(v0, v1, t)

USES = ["brightness","speed","width","softness","density","color"]

def _preview_emit(*, num_leds: int, params: dict, t: float, state=None) -> List[RGB]:
    n = max(1, int(num_leds))
    tint = params.get("color",(180,220,255))
    tr,tg,tb = int(tint[0])&255, int(tint[1])&255, int(tint[2])&255
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    width = _clamp01(float(params.get("width", 0.45)))       # flow scale
    softness = _clamp01(float(params.get("softness", 0.45))) # highlight sharpness
    density = _clamp01(float(params.get("density", 0.55)))   # ripple amount

    if width < 0.08: width = 0.08
    flow = (1.0/width) * 0.7
    wobble = 0.3 + density * 1.2
    sharp = 1.5 + (1.0-softness) * 6.0

    out=[]
    for i in range(n):
        x = i / max(1.0, (n-1))
        # base field
        a = _noise1(x*flow + t*speed*0.25, 4242)
        b = _noise1(x*flow*2.0 - t*speed*0.18, 31337)
        w = (a*0.7 + b*0.3)
        # specular highlight
        spec = pow(_clamp01(1.0 - abs(w-0.5)*2.0), sharp)
        # subtle color shift
        base = 0.15 + 0.55*w
        v = br * _clamp01(base + spec*wobble)
        r = int(v * (0.55*tr + 0.45*255) / 255.0)
        g = int(v * (0.55*tg + 0.45*255) / 255.0)
        b2 = int(v * (0.55*tb + 0.45*255) / 255.0)
        out.append((min(255,r), min(255,g), min(255,b2)))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    tint = params.get("color",(180,220,255))
    tr,tg,tb = int(tint[0])&255, int(tint[1])&255, int(tint[2])&255
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    width = float(params.get("width", 0.45))
    softness = float(params.get("softness", 0.45))
    density = float(params.get("density", 0.55))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.08: width = 0.08
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0

    flow = (1.0/width) * 0.7
    wobble = 0.3 + density * 1.2
    sharp = 1.5 + (1.0-softness) * 6.0
    period_ms = int(max(400.0, min(60000.0, 16000.0 / speed)))

    return f"""// Generated by Modulo (Effect: liquid_metal)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline float lerp(float a, float b, float t) {{
  return a + (b-a)*t;
}}

static inline float noise1(float x, uint32_t seed) {{
  int x0 = (int)floorf(x);
  int x1 = x0 + 1;
  float tt = x - (float)x0;
  float v0 = u01(hash_u32((uint32_t)x0 ^ seed));
  float v1 = u01(hash_u32((uint32_t)x1 ^ seed));
  return lerp(v0, v1, tt);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float t = phase;
  float br = clamp01((float){br}f);
  float flow = (float){flow}f;
  float wobble = (float){wobble}f;
  float sharp = (float){sharp}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float a = noise1(x*flow + t*(float){speed}f*0.25f, 4242u);
    float b = noise1(x*flow*2.0f - t*(float){speed}f*0.18f, 31337u);
    float w = a*0.7f + b*0.3f;
    float spec = powf(clamp01(1.0f - fabsf(w-0.5f)*2.0f), sharp);
    float base = 0.15f + 0.55f*w;
    float v = br * clamp01(base + spec*wobble);

    float r = v * ((0.55f*(float){tr}f + 0.45f*255.0f) / 255.0f);
    float g = v * ((0.55f*(float){tg}f + 0.45f*255.0f) / 255.0f);
    float bb = v * ((0.55f*(float){tb}f + 0.45f*255.0f) / 255.0f);
    leds[i] = CRGB((uint8_t)fminf(255.0f, r*255.0f), (uint8_t)fminf(255.0f, g*255.0f), (uint8_t)fminf(255.0f, bb*255.0f));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_liquid_metal():
    return register(BehaviorDef(
        "liquid_metal",
        title="Liquid Metal",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
