from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color", (0,255,255))
    br = params.get("brightness", 1.0)
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.25)))
    softness = _clamp01(float(params.get("softness", 0.3)))

    base = _apply_brightness((int(col[0])&255, int(col[1])&255, int(col[2])&255), br)

    tail = max(1, int(round(width * n)))
    head = (t * max(0.1, speed) * 10.0) % n
    sigma = max(0.5, softness * 3.0)

    out: List[RGB] = []
    for i in range(n):
        d = (head - i) % n
        if d >= tail:
            out.append((0,0,0))
            continue
        a = 1.0 - (d / float(tail))
        if d <= 6.0:
            g = math.exp(-(d*d)/(2.0*sigma*sigma))
            a = min(1.0, a + 0.35*g)
        if a < 0.0: a = 0.0
        out.append((int(base[0]*a)&255, int(base[1]*a)&255, int(base[2]*a)&255))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(0,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.25))
    softness = float(params.get("softness", 0.3))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.0: width = 0.0
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    tail = int(round(width * n))
    if tail < 1: tail = 1

    r = int(int(col[0]) * br) & 255
    g = int(int(col[1]) * br) & 255
    b = int(int(col[2]) * br) & 255

    cycle_ms = int(max(60.0, min(5000.0, 1500.0 / max(0.2, speed))))

    return f"""// Generated by Modulo (Effect: meteor)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){cycle_ms}) / (float){cycle_ms};
  float head = phase * (float)NUM_LEDS;
  float sigma = 0.5f + (float){softness}f * 3.0f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float d = head - (float)i;
    while (d < 0.0f) d += (float)NUM_LEDS;
    if (d >= (float){tail}f) {{
      leds[i] = CRGB(0,0,0);
      continue;
    }}
    float a = 1.0f - (d / (float){tail}f);
    if (d <= 6.0f) {{
      a = fminf(1.0f, a + 0.35f * gauss(d, sigma));
    }}
    a = clamp01(a);
    leds[i] = CRGB((uint8_t)({r}f*a), (uint8_t)({g}f*a), (uint8_t)({b}f*a));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_meteor():
    return register(BehaviorDef(
        "meteor",
        title="Meteor / Comet",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
