from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _lerp(a: float, b: float, t: float) -> float:
    return a + (b-a)*t

def _noise1(x: float, seed: int) -> float:
    x0 = int(math.floor(x))
    x1 = x0 + 1
    t = x - float(x0)
    h0 = _hash_u32(x0 ^ seed)
    h1 = _hash_u32(x1 ^ seed)
    v0 = _u01(h0)
    v1 = _u01(h1)
    return _lerp(v0, v1, t)

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","width","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.35)))      # larger = smoother
    softness = _clamp01(float(params.get("softness", 0.5))) # contrast
    if width < 0.05: width = 0.05

    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)
    spatial = 0.25 + (1.0/width) * 0.35
    scroll = t * max(0.1, speed) * 1.1

    out: List[RGB] = []
    for i in range(n):
        v = 0.0
        v += 0.65 * _noise1(i*spatial + scroll*1.0, 101)
        v += 0.35 * _noise1(i*spatial*2.0 + scroll*2.1, 202)
        # contrast via softness (softness high => lower contrast)
        c = 1.4 - softness * 0.9
        v = (v - 0.5) * c + 0.5
        v = _clamp01(v)
        out.append(_apply_brightness(base, br * v))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.35))
    softness = float(params.get("softness", 0.5))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    r0 = int(col[0]) & 255
    g0 = int(col[1]) & 255
    b0 = int(col[2]) & 255

    spatial = 0.25 + (1.0/width) * 0.35
    scroll_speed = max(0.1, speed) * 1.1

    return f"""// Generated by Modulo (Effect: noise)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline float lerp(float a, float b, float t) {{
  return a + (b-a)*t;
}}

static inline float noise1(float x, uint32_t seed) {{
  int x0 = (int)floorf(x);
  int x1 = x0 + 1;
  float t = x - (float)x0;
  float v0 = u01(hash_u32((uint32_t)x0 ^ seed));
  float v1 = u01(hash_u32((uint32_t)x1 ^ seed));
  return lerp(v0, v1, t);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float t = (float)now / 1000.0f;
  float br = clamp01((float){br}f);
  float softness = clamp01((float){softness}f);
  float c = 1.4f - softness * 0.9f;

  float spatial = (float){spatial}f;
  float scroll = t * (float){scroll_speed}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float v = 0.0f;
    v += 0.65f * noise1((float)i*spatial + scroll*1.0f, 101u);
    v += 0.35f * noise1((float)i*spatial*2.0f + scroll*2.1f, 202u);
    v = (v - 0.5f) * c + 0.5f;
    v = clamp01(v);
    float a = br * v;
    leds[i] = CRGB((uint8_t)((float){r0}f*a), (uint8_t)((float){g0}f*a), (uint8_t)((float){b0}f*a));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_noise():
    return register(BehaviorDef(
        "noise",
        title="Noise (Texture)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
