from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","width","softness","density"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    width = _clamp01(float(params.get("width", 0.35)))       # frequency
    softness = _clamp01(float(params.get("softness", 0.5)))  # contrast
    density = _clamp01(float(params.get("density", 0.55)))   # color roll
    if width < 0.05: width = 0.05

    freq = (1.0/width) * 1.6
    roll = 0.15 + density*0.85
    exp = 0.7 + (1.0-softness)*1.8

    out=[]
    for i in range(n):
        x = i / max(1.0,(n-1))
        a = math.sin(2.0*math.pi*(x*freq + t*speed*0.22))
        b = math.sin(2.0*math.pi*(x*freq*0.73 - t*speed*0.18))
        c = math.sin(2.0*math.pi*(x*freq*1.21 + t*speed*0.11))
        v = (a + b + c) / 3.0
        v = 0.5 + 0.5*v
        v = pow(_clamp01(v), exp)
        hue = (x*roll + t*speed*0.05 + v*0.25) % 1.0
        r,g,b2 = _hsv_to_rgb(hue, 1.0, br*(0.10 + 0.90*v))
        out.append((r,g,b2))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    width = float(params.get("width", 0.35))
    softness = float(params.get("softness", 0.5))
    density = float(params.get("density", 0.55))

    br = 0.0 if br < 0.0 else (1.0 if br > 1.0 else br)
    softness = 0.0 if softness < 0.0 else (1.0 if softness > 1.0 else softness)
    density = 0.0 if density < 0.0 else (1.0 if density > 1.0 else density)
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    freq = (1.0/width) * 1.6
    roll = 0.15 + density*0.85
    exp = 0.7 + (1.0-softness)*1.8
    period_ms = int(max(300.0, min(60000.0, 14000.0 / speed)))

    return f"""// Generated by Modulo (Effect: plasma_lattice)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float t = phase;

  float br = clamp01((float){br}f);
  float freq = (float){freq}f;
  float roll = (float){roll}f;
  float exp = (float){exp}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS<=1)?0.0f:((float)i/(float)(NUM_LEDS-1));
    float a = sinf(2.0f*3.1415926f*(x*freq + t*(float){speed}f*0.22f));
    float b = sinf(2.0f*3.1415926f*(x*freq*0.73f - t*(float){speed}f*0.18f));
    float c = sinf(2.0f*3.1415926f*(x*freq*1.21f + t*(float){speed}f*0.11f));
    float v = (a + b + c) / 3.0f;
    v = 0.5f + 0.5f*v;
    v = powf(clamp01(v), exp);
    float hue = fmodf(x*roll + t*(float){speed}f*0.05f + v*0.25f, 1.0f);
    uint8_t r,g,b2;
    hsv_to_rgb(hue, 1.0f, br*(0.10f + 0.90f*v), &r,&g,&b2);
    leds[i] = CRGB(r,g,b2);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_plasma_lattice():
    return register(BehaviorDef(
        "plasma_lattice",
        title="Plasma Lattice",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
