from __future__ import annotations
SHIPPED = True

from typing import List, Tuple

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int, int, int]


def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    import math
    a = 0.5 + 0.5 * math.sin(t * 2.0 * math.pi * 0.8)
    v = int(40 + a * 215)
    return [(0, v, 0)] * int(num_leds)


def _arduino_emit(*, layout: dict, params: dict) -> str:
    num_leds = int(layout["num_leds"])
    return f"""// Generated by Modulo (Era: 1980s pulse green)
#include <FastLED.h>

#define NUM_LEDS {num_leds}
#define LED_PIN @@DATA_PIN@@
#define LED_TYPE @@LED_TYPE@@
#define COLOR_ORDER @@COLOR_ORDER@@
#define LED_BRIGHTNESS @@LED_BRIGHTNESS@@

CRGB leds[NUM_LEDS];

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  uint8_t br = beatsin8(48, 40, 255);
  FastLED.setBrightness(br);
  for (int i = 0; i < NUM_LEDS; i++) {{
    leds[i] = CRGB(0, 255, 0);
  }}
  FastLED.show();
  delay(10);
}}
"""


def register_pulse_green_1980s():
    return register(
        BehaviorDef(
            "pulse_green_1980s",
            title="1980s Pulse (Green)",
            uses=[],
            preview_emit=_preview_emit,
            arduino_emit=_arduino_emit,
            capabilities={
                "title": "1980s Pulse (Green)",
                "supports": "both",
                "supports_strip": True,
                "supports_matrix": True,
                "requires_audio": False,
                "shipped": True,
                "ui_category": "era",
            },
        )
    )
