from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","softness"]

def _curve(u: float, softness: float) -> float:
    # u in [0,1]; returns smooth pulse in [0,1]
    # softness controls how "peaky" vs "breathy" the pulse is
    # base is sin wave mapped to 0..1
    s = 0.5 - 0.5 * math.cos(2.0 * math.pi * u)
    # soften: exponent from 0.7..3.0
    exp = 0.7 + _clamp01(softness) * 2.3
    return pow(s, exp)

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color", (255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.5))

    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)
    # cycles per second
    cps = max(0.08, speed) * 0.35
    u = (t * cps) % 1.0
    a = _curve(u, softness)
    rgb = _apply_brightness(base, br * a)
    return [rgb for _ in range(n)]

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.5))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    r0 = int(col[0]) & 255
    g0 = int(col[1]) & 255
    b0 = int(col[2]) & 255

    # cycle_ms controls speed (lower = faster)
    cps = max(0.08, speed) * 0.35
    cycle_ms = int(max(300.0, min(15000.0, 1000.0 / cps)))

    return f"""// Generated by Modulo (Effect: pulse)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float curve(float u, float softness) {{
  float s = 0.5f - 0.5f * cosf(2.0f * 3.1415926f * u);
  float exp = 0.7f + clamp01(softness) * 2.3f;
  return powf(s, exp);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float u = (float)(now % (unsigned long){cycle_ms}) / (float){cycle_ms};
  float a = curve(u, (float){softness}f);
  float br = clamp01((float){br}f) * a;

  uint8_t r = (uint8_t)((float){r0}f * br);
  uint8_t g = (uint8_t)((float){g0}f * br);
  uint8_t b = (uint8_t)((float){b0}f * br);

  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = CRGB(r,g,b);
  }}
  FastLED.show();
  delay(1);
}}
"""

def register_pulse():
    return register(BehaviorDef(
        "pulse",
        title="Pulse / Breathing",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
