from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

USES = ["brightness","speed","softness","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = float(params.get("speed", 1.0))
    softness = _clamp01(float(params.get("softness", 0.0)))  # edge softness
    width = _clamp01(float(params.get("width", 0.25)))       # wipe thickness
    if width < 0.02: width = 0.02

    # head advances across strip and wraps
    head = (t * max(0.1, speed) * 0.25) % 1.0  # 0..1
    thickness = width
    out: List[RGB] = []
    for i in range(n):
        x = i / max(1.0, (n-1))
        # distance to head along wrap
        d = (x - head) % 1.0
        # within thickness -> on
        if d > thickness:
            out.append((0,0,0))
            continue
        # edge soften
        a = 1.0
        if softness > 0.0:
            edge = softness * thickness
            if edge > 1e-6 and d > (thickness - edge):
                a = max(0.0, 1.0 - (d - (thickness-edge)) / edge)
                a = a*a
        hue = (x + t * max(0.1, speed) * 0.15) % 1.0
        r,g,b = _hsv_to_rgb(hue, 1.0, br * a)
        out.append((r,g,b))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.0))
    width = float(params.get("width", 0.25))
    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.02: width = 0.02
    if width > 1.0: width = 1.0

    # ms per full traverse (lower = faster)
    traverse_ms = int(max(800.0, min(30000.0, 9000.0 / max(0.2, speed))))
    thickness = width
    return f"""// Generated by Modulo (Effect: rainbow_wipe)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float head = (float)(now % (unsigned long){traverse_ms}) / (float){traverse_ms}; // 0..1
  float br = clamp01((float){br}f);
  float softness = clamp01((float){softness}f);
  float thickness = (float){thickness}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float d = x - head;
    while (d < 0.0f) d += 1.0f;
    if (d > thickness) {{
      leds[i] = CRGB(0,0,0);
      continue;
    }}
    float a = 1.0f;
    if (softness > 0.0f) {{
      float edge = softness * thickness;
      if (edge > 1e-6f && d > (thickness - edge)) {{
        float k = 1.0f - (d - (thickness - edge)) / edge;
        if (k < 0.0f) k = 0.0f;
        a = k*k;
      }}
    }}
    float hue = fmodf(x + ((float)now/1000.0f) * (0.15f * (float){speed}f), 1.0f);
    uint8_t r,g,b;
    hsv_to_rgb(hue, 1.0f, br * a, &r, &g, &b);
    leds[i] = CRGB(r,g,b);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_rainbow_wipe():
    return register(BehaviorDef(
        "rainbow_wipe",
        title="Rainbow Wipe",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
