from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","width","softness","density"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(0,200,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.18)))       # ring thickness
    softness = _clamp01(float(params.get("softness", 0.55))) # falloff
    density = _clamp01(float(params.get("density", 0.45)))   # repetition / multi-rings

    if width < 0.02: width = 0.02
    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)

    # distance from center in [0,1]
    out: List[RGB] = []
    center = 0.5
    # wave radius grows and wraps; density controls how many repeating rings (frequency)
    freq = 1.0 + density * 5.0
    radius = (t * max(0.1, speed) * 0.18) % 1.0

    # softness -> exponential falloff around ring edge
    sigma = 0.02 + width * (0.18 + softness * 0.9)

    for i in range(n):
        x = (i / max(1.0, (n-1)))
        d = abs(x - center) * 2.0  # 0..1
        # repeating rings using fractional part of d*freq - radius*freq
        u = (d * freq - radius * freq) % 1.0
        # ring centered at u=0 (and u=1). take min distance to 0/1.
        du = min(u, 1.0 - u)
        a = math.exp(-(du*du) / (2.0*sigma*sigma))
        out.append(_apply_brightness(base, br * a))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(0,200,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.18))
    softness = float(params.get("softness", 0.55))
    density = float(params.get("density", 0.45))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.02: width = 0.02
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0

    r0 = int(col[0]) & 255
    g0 = int(col[1]) & 255
    b0 = int(col[2]) & 255

    freq = 1.0 + density * 5.0
    sigma = 0.02 + width * (0.18 + softness * 0.9)
    period_ms = int(max(600.0, min(30000.0, 16000.0 / max(0.2, speed))))

    return f"""// Generated by Modulo (Effect: ripple)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float t = (float)(now % (unsigned long){period_ms}) / (float){period_ms}; // 0..1
  float br = clamp01((float){br}f);
  float freq = (float){freq}f;
  float sigma = (float){sigma}f;

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.5f : ((float)i / (float)(NUM_LEDS - 1));
    float d = fabsf(x - 0.5f) * 2.0f; // 0..1
    float u = fmodf(d * freq - t * freq, 1.0f);
    if (u < 0.0f) u += 1.0f;
    float du = fminf(u, 1.0f - u);
    float a = gauss(du, sigma);
    float k = br * a;
    leds[i] = CRGB((uint8_t)((float){r0}f*k), (uint8_t)((float){g0}f*k), (uint8_t)((float){b0}f*k));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_ripple():
    return register(BehaviorDef(
        "ripple",
        title="Ripple / Shockwave",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
