from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["brightness","speed","density","softness","width","color"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(90,200,255))
    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = _clamp01(float(params.get("density", 0.55)))   # number of shocks
    softness = _clamp01(float(params.get("softness", 0.45))) # decay
    width = _clamp01(float(params.get("width", 0.18)))       # pulse width
    if width < 0.03: width = 0.03

    shocks = 2 + int(round(density * 8.0))  # 2..10
    sigma = 0.8 + width * 6.0
    damp = 0.12 + softness*0.35

    # periodic reseed
    bps = 0.25 * speed
    bucket = int(t * bps)
    u = (t * bps) - bucket

    out = [(0,0,0) for _ in range(n)]
    for k in range(shocks):
        h = _hash_u32(bucket ^ (k*1777))
        x0 = _u01(h)  # start position
        v0 = (_u01(_hash_u32(h ^ 0xBEEF)) * 2.0 - 1.0) * (0.65 + 1.2*density)
        # bounce in [0,1] using triangle wave
        x = x0 + v0 * u
        x = abs((x % 2.0) - 1.0)
        idx = x * (n-1 if n>1 else 1)

        # amplitude decays over u and per shock id
        a0 = 1.0 - damp*u
        a0 *= 0.7 + 0.3*math.sin((k+1)*12.3 + bucket*0.7)
        a0 = max(0.0, a0)

        # hue shifts slightly with k
        hue = (0.55 + 0.15*_u01(_hash_u32(h ^ 0x1234)) + u*0.15) % 1.0
        pr,pg,pb = _hsv_to_rgb(hue, 1.0, 1.0)
        pr = int((pr*0.55 + base[0]*0.45)) & 255
        pg = int((pg*0.55 + base[1]*0.45)) & 255
        pb = int((pb*0.55 + base[2]*0.45)) & 255

        for i in range(n):
            d = abs(i - idx)
            a = math.exp(-(d*d)/(2.0*sigma*sigma)) * a0
            if a < 0.002: 
                continue
            add = (int(pr*br*a), int(pg*br*a), int(pb*br*a))
            out[i] = _add(out[i], (min(255,add[0]),min(255,add[1]),min(255,add[2])))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(90,200,255))
    r0,g0,b0 = int(col[0])&255, int(col[1])&255, int(col[2])&255
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = float(params.get("density", 0.55))
    softness = float(params.get("softness", 0.45))
    width = float(params.get("width", 0.18))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.03: width = 0.03
    if width > 1.0: width = 1.0

    shocks = 2 + int(round(density * 8.0))
    sigma = 0.8 + width * 6.0
    damp = 0.12 + softness*0.35
    bucket_ms = int(max(900.0, min(60000.0, 4000.0 / (0.25*speed))))

    return f"""// Generated by Modulo (Effect: shock_chain)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  unsigned long bucket = now / (unsigned long){bucket_ms};
  float u = (float)(now % (unsigned long){bucket_ms}) / (float){bucket_ms};

  float br = clamp01((float){br}f);
  float sigma = (float){sigma}f;
  float damp = (float){damp}f;
  float density = clamp01((float){density}f);

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  for (int k=0; k<{shocks}; k++) {{
    uint32_t h = hash_u32((uint32_t)bucket ^ (uint32_t)(k*1777));
    float x0 = u01(h);
    float v0 = (u01(hash_u32(h ^ 0x0000BEEFu))*2.0f - 1.0f) * (0.65f + 1.2f*density);
    float x = x0 + v0 * u;
    x = fabsf(fmodf(x, 2.0f) - 1.0f); // bounce
    float idx = x * (float)(NUM_LEDS - 1);

    float a0 = 1.0f - damp*u;
    a0 *= 0.7f + 0.3f*sinf(((float)k+1.0f)*12.3f + (float)bucket*0.7f);
    if (a0 < 0.0f) a0 = 0.0f;

    float hue = fmodf(0.55f + 0.15f*u01(hash_u32(h ^ 0x00001234u)) + u*0.15f, 1.0f);
    uint8_t pr,pg,pb;
    hsv_to_rgb(hue, 1.0f, 1.0f, &pr,&pg,&pb);
    pr = (uint8_t)fminf(255.0f, (float)pr*0.55f + (float){r0}f*0.45f);
    pg = (uint8_t)fminf(255.0f, (float)pg*0.55f + (float){g0}f*0.45f);
    pb = (uint8_t)fminf(255.0f, (float)pb*0.55f + (float){b0}f*0.45f);

    for (int i=0; i<NUM_LEDS; i++) {{
      float d = fabsf((float)i - idx);
      float a = gauss(d, sigma) * a0;
      if (a < 0.002f) continue;
      float kf = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, (float)pr*kf, (float)pg*kf, (float)pb*kf);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_shock_chain():
    return register(BehaviorDef(
        "shock_chain",
        title="Shock Chain",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
