from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","softness","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(255,0,0))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = _clamp01(float(params.get("softness", 0.6))) # trail softness
    width = _clamp01(float(params.get("width", 0.2)))       # dot size
    base = _apply_brightness((int(col[0])&255, int(col[1])&255, int(col[2])&255), br)

    # position
    u = (t * max(0.1, speed) * 0.35) % 1.0
    pos = 0.5 - 0.5*math.cos(2.0*math.pi*u)
    x = pos * (n-1 if n>1 else 1)

    dot = max(1, int(round(width * n * 0.15)))
    sigma = max(0.6, softness * 5.0)

    out = [(0,0,0) for _ in range(n)]
    for i in range(n):
        d = abs(i - x)
        if d > dot + 10:
            continue
        a = math.exp(-(d*d)/(2.0*sigma*sigma))
        out[i] = (int(base[0]*a)&255, int(base[1]*a)&255, int(base[2]*a)&255)
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,0,0))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.6))
    width = float(params.get("width", 0.2))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.0: width = 0.0
    if width > 1.0: width = 1.0

    r0 = int(int(col[0]) * br) & 255
    g0 = int(int(col[1]) * br) & 255
    b0 = int(int(col[2]) * br) & 255

    dot = int(max(1.0, round(width * float(n) * 0.15)))
    sigma = float(max(0.6, softness * 5.0))
    period_ms = int(max(700.0, min(30000.0, 9000.0 / max(0.2, speed))))

    return f"""// Generated by Modulo (Effect: sinelon)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float u = (float)(now % (unsigned long){period_ms}) / (float){period_ms}; // 0..1
  float pos = 0.5f - 0.5f * cosf(2.0f * 3.1415926f * u);
  float x = pos * (float)(NUM_LEDS - 1);

  for (int i=0; i<NUM_LEDS; i++) {{
    float d = fabsf((float)i - x);
    if (d > (float)({dot} + 10)) {{
      leds[i] = CRGB(0,0,0);
      continue;
    }}
    float a = gauss(d, (float){sigma}f);
    leds[i] = CRGB((uint8_t)({r0}f*a), (uint8_t)({g0}f*a), (uint8_t)({b0}f*a));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_sinelon():
    return register(BehaviorDef(
        "sinelon",
        title="Sinelon (Dot + Trail)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
