from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math
import random

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _apply_brightness(rgb, br: float):
    try:
        br = float(br)
    except Exception:
        br = 1.0
    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    c = params.get("color", (255,255,255))
    br = params.get("brightness", 1.0)
    speed = float(params.get("speed", 1.0))
    density = float(params.get("density", 0.2))

    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0

    # number of sparkles per frame, scaled
    k = int(round(density * n))
    if k < 1 and density > 0.0:
        k = 1

    base = _apply_brightness((int(c[0])&255, int(c[1])&255, int(c[2])&255), br)
    out = [(0,0,0)] * n

    # deterministic-ish seed so it animates but is stable per time slice
    step = int(t * max(0.1, speed) * 25.0)
    rnd = random.Random(step * 2654435761 & 0xFFFFFFFF)

    for _ in range(k):
        idx = rnd.randrange(0, n)
        out[idx] = base
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    c = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    density = float(params.get("density", 0.2))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0

    r = int(int(c[0]) * br) & 255
    g = int(int(c[1]) * br) & 255
    b = int(int(c[2]) * br) & 255

    # ms per refresh; speed 0..10 -> slower..faster
    refresh_ms = int(max(10.0, 150.0 / max(0.2, speed)))

    return f"""// Generated by Modulo (Phase 3H: Sparkle)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

unsigned long lastRefresh = 0;

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
  random16_set_seed(analogRead(A0));
}}

void loop() {{
  unsigned long now = millis();
  if (now - lastRefresh < (unsigned long){refresh_ms}) {{
    delay(1);
    return;
  }}
  lastRefresh = now;

  // clear
  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = CRGB(0,0,0);
  }}

  // sparkles: pick K random LEDs each frame
  int k = (int)({density}f * (float)NUM_LEDS + 0.5f);
  if (k < 1 && {density}f > 0.0f) k = 1;

  for (int s=0; s<k; s++) {{
    int idx = random16(NUM_LEDS);
    leds[idx] = CRGB({r},{g},{b});
  }}

  FastLED.show();
}}
"""

def register_sparkle():
    return register(BehaviorDef(
        "sparkle",
        title="Sparkle",
        uses=["color","brightness","speed","density"],
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
