from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _hsv_to_rgb(h: float, s: float, v: float) -> RGB:
    h = (h % 1.0) * 6.0
    i = int(h) % 6
    f = h - float(i)
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    if i == 0: r,g,b = v,t,p
    elif i == 1: r,g,b = q,v,p
    elif i == 2: r,g,b = p,v,t
    elif i == 3: r,g,b = p,q,v
    elif i == 4: r,g,b = t,p,v
    else: r,g,b = v,p,q
    return (int(r*255)&255, int(g*255)&255, int(b*255)&255)

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["brightness","speed","softness","density","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float, state=None) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    softness = _clamp01(float(params.get("softness", 0.45)))
    density = _clamp01(float(params.get("density", 0.55)))  # how many bands contribute strongly
    width = _clamp01(float(params.get("width", 0.35)))      # ripple width
    if width < 0.05: width = 0.05

    audio = params.get("_audio_flat") or {}
    L = [float(audio.get(f"l{i}", 0.0) or 0.0) for i in range(7)]
    R = [float(audio.get(f"r{i}", 0.0) or 0.0) for i in range(7)]
    bands = L + R  # 14
    # normalize and smooth
    if state is None or not isinstance(state, dict):
        state = {}
    a = 0.05 + 0.45*softness
    if "b" not in state:
        state["b"] = [max(0.0, min(1.0, v)) for v in bands]
    else:
        for i in range(14):
            v = max(0.0, min(1.0, bands[i]))
            state["b"][i] = (1.0-a)*state["b"][i] + a*v
    bands = state["b"]

    # Each band emits a ripple from its anchor position along the strip.
    # Low bands: slow wide ripples, high bands: fast tight ripples.
    base_w = 0.04 + width*0.14
    out = [(0,0,0) for _ in range(n)]

    for i in range(14):
        amp = bands[i]
        if amp <= 0.002:
            continue
        # density gating: reduce contribution of quieter bands
        amp = max(0.0, amp - (1.0-density)*0.35) / max(1e-6, (1.0 - (1.0-density)*0.35))
        amp = _clamp01(amp)

        x0 = i / 13.0
        # speed per band (bass slower)
        f = (i / 13.0)
        wave_speed = (0.10 + 0.55*speed) * (0.55 + 1.25*f)
        k = 2.0 + 10.0*(f)  # frequency
        # phase driven by time and band index
        ph = t*wave_speed + i*0.07
        # ripple width by band (treble tighter)
        sig = base_w * (1.8 - 1.1*f) * (0.6 + 1.6*softness)

        hue = (0.62 + 0.33*f) % 1.0
        pr,pg,pb = _hsv_to_rgb(hue, 1.0, 1.0)
        for px in range(n):
            x = px / max(1.0,(n-1))
            d = abs(x - x0)
            d = min(d, 1.0-d)
            # ring wave around anchor
            w = 0.5 + 0.5*math.sin(2.0*math.pi*(d*k - ph))
            # localize around anchor
            a0 = math.exp(-(d*d)/(2.0*sig*sig))
            a1 = (w**2.2) * a0
            a2 = amp * a1
            if a2 < 0.001:
                continue
            out[px] = _add(out[px], (int(pr*br*a2), int(pg*br*a2), int(pb*br*a2)))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n=int(layout["num_leds"]); pin=int(layout["led_pin"])
    br=float(params.get("brightness",1.0))
    speed=max(0.1,float(params.get("speed",1.0)))
    softness=float(params.get("softness",0.45))
    density=float(params.get("density",0.55))
    width=float(params.get("width",0.35))
    if br<0: br=0.0
    if br>1: br=1.0
    if softness<0: softness=0.0
    if softness>1: softness=1.0
    if density<0: density=0.0
    if density>1: density=1.0
    if width<0.05: width=0.05
    if width>1: width=1.0

    alpha = 0.05 + 0.45*softness
    base_w = 0.04 + width*0.14

    return f"""// Generated by Modulo (Spectral Ripples 14)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

// MSGEQ7 pins (default)
const int RESET_PIN = 5;
const int STROBE_PIN = 4;
const int LEFT_PIN = A0;
const int RIGHT_PIN = A1;

float B[14] = {{0}};

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

static inline float read01(int pin) {{
  int v = analogRead(pin);
  return clamp01((float)v / 1023.0f);
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
  pinMode(RESET_PIN, OUTPUT);
  pinMode(STROBE_PIN, OUTPUT);
  digitalWrite(RESET_PIN, LOW);
  digitalWrite(STROBE_PIN, HIGH);
}}

void loop() {{
  // read 14 bands
  digitalWrite(RESET_PIN, HIGH); delayMicroseconds(5); digitalWrite(RESET_PIN, LOW);
  for (int i=0;i<7;i++) {{
    digitalWrite(STROBE_PIN, LOW); delayMicroseconds(30);
    float lv = read01(LEFT_PIN);
    float rv = read01(RIGHT_PIN);
    digitalWrite(STROBE_PIN, HIGH);
    B[i]   = (1.0f-{alpha}f)*B[i]   + {alpha}f*lv;
    B[i+7] = (1.0f-{alpha}f)*B[i+7] + {alpha}f*rv;
  }}

  float br = clamp01((float){br}f);
  float speed = (float){speed}f;
  float softness = clamp01((float){softness}f);
  float density = clamp01((float){density}f);
  float base_w = (float){base_w}f;

  float tt = millis()/1000.0f;

  for (int p=0;p<NUM_LEDS;p++) leds[p] = CRGB(0,0,0);

  for (int i=0;i<14;i++) {{
    float amp = B[i];
    if (amp <= 0.002f) continue;

    float gate = (1.0f-density)*0.35f;
    amp = fmaxf(0.0f, amp - gate) / fmaxf(1e-6f, (1.0f-gate));
    amp = clamp01(amp);

    float x0 = (float)i / 13.0f;
    float f = (float)i / 13.0f;
    float wave_speed = (0.10f + 0.55f*speed) * (0.55f + 1.25f*f);
    float k = 2.0f + 10.0f*f;
    float ph = tt*wave_speed + (float)i*0.07f;
    float sig = base_w * (1.8f - 1.1f*f) * (0.6f + 1.6f*softness);

    float hue = fmodf(0.62f + 0.33f*f, 1.0f);
    uint8_t pr,pg,pb;
    hsv_to_rgb(hue, 1.0f, 1.0f, &pr,&pg,&pb);

    for (int p=0;p<NUM_LEDS;p++) {{
      float x = (NUM_LEDS<=1)?0.0f:((float)p/(float)(NUM_LEDS-1));
      float d = fabsf(x - x0);
      d = fminf(d, 1.0f-d);
      float w = 0.5f + 0.5f*sinf(2.0f*3.1415926f*(d*k - ph));
      float a0 = expf(-(d*d)/(2.0f*sig*sig));
      float a1 = powf(w, 2.2f) * a0;
      float a2 = amp * a1;
      if (a2 < 0.001f) continue;
      float kf = br*a2;
      add_rgb(&leds[p].r, &leds[p].g, &leds[p].b, (float)pr*kf, (float)pg*kf, (float)pb*kf);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_spectral_ripples_14():
    return register(BehaviorDef(
        "spectral_ripples_14",
        title="Spectral Ripples (14-band)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
