from __future__ import annotations
SHIPPED = True

from typing import List, Tuple

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _add(a: RGB, b: RGB) -> RGB:
    return (min(255,a[0]+b[0]), min(255,a[1]+b[1]), min(255,a[2]+b[2]))

USES = ["brightness","speed","softness"]

def _preview_emit(*, num_leds: int, params: dict, t: float, state=None) -> List[RGB]:
    n = max(1, int(num_leds))
    br = _clamp01(float(params.get("brightness", 1.0)))
    speed = max(0.1, float(params.get("speed", 1.0)))
    softness = _clamp01(float(params.get("softness", 0.35)))  # smoothing-ish

    audio = params.get("_audio_flat") or {}
    # sources: l0..l6, r0..r6 (0..1)
    L = [float(audio.get(f"l{i}", 0.0) or 0.0) for i in range(7)]
    R = [float(audio.get(f"r{i}", 0.0) or 0.0) for i in range(7)]

    # basic temporal smoothing stored in state
    if state is None or not isinstance(state, dict):
        state = {}
    smooth = 0.05 + 0.45*softness
    if "L" not in state:
        state["L"] = L[:]
        state["R"] = R[:]
    else:
        for i in range(7):
            state["L"][i] = (1.0-smooth)*state["L"][i] + smooth*L[i]
            state["R"][i] = (1.0-smooth)*state["R"][i] + smooth*R[i]
    L = [max(0.0, min(1.0, v)) for v in state["L"]]
    R = [max(0.0, min(1.0, v)) for v in state["R"]]

    # map 14 bars across strip
    bars = 14
    seg = max(1, n // bars)
    out = [(0,0,0) for _ in range(n)]

    def band_color(i: int, side: str) -> RGB:
        # bass->red, mid->green, treble->blue, with side tint
        x = i / 6.0
        r = int(255*(1.0-x))
        g = int(255*(1.0-abs(x-0.5)*2.0))
        b = int(255*(x))
        if side == "L":
            return (r, g, min(255, b+40))
        else:
            return (min(255, r+40), g, b)

    for b in range(bars):
        side = "L" if b < 7 else "R"
        i = b if b < 7 else (b-7)
        amp = (L[i] if side=="L" else R[i])
        # speed controls gain a little (for responsiveness feeling)
        amp = max(0.0, min(1.0, amp * (0.8 + 0.3*min(3.0, speed))))
        col = band_color(i, side)
        fill = int(round(amp * seg))
        base = b*seg
        for k in range(seg):
            idx = base + k
            if idx >= n: break
            if k < fill:
                out[idx] = (int(col[0]*br)&255, int(col[1]*br)&255, int(col[2]*br)&255)
            else:
                out[idx] = (0,0,0)

    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    softness = float(params.get("softness", 0.35))

    if br < 0: br = 0.0
    if br > 1: br = 1.0
    if softness < 0: softness = 0.0
    if softness > 1: softness = 1.0
    if speed < 0.1: speed = 0.1

    # MSGEQ7 pins (default, can be made configurable later)
    resetPin = 5;
    strobePin = 4;
    leftPin = "A0";
    rightPin = "A1";

    seg = max(1, n // 14)
    alpha = 0.05 + 0.45*softness

    return f"""// Generated by Modulo (Spectrum Bars Stereo)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

const int RESET_PIN = {resetPin};
const int STROBE_PIN = {strobePin};
const int LEFT_PIN = {leftPin};
const int RIGHT_PIN = {rightPin};

float L[7] = {{0,0,0,0,0,0,0}};
float R[7] = {{0,0,0,0,0,0,0}};

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline void bandColor(int i, bool isLeft, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float x = (float)i / 6.0f;
  float rr = 255.0f*(1.0f-x);
  float gg = 255.0f*(1.0f - fabsf(x-0.5f)*2.0f);
  float bb = 255.0f*(x);
  if (isLeft) {{
    bb = fminf(255.0f, bb + 40.0f);
  }} else {{
    rr = fminf(255.0f, rr + 40.0f);
  }}
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);

  pinMode(RESET_PIN, OUTPUT);
  pinMode(STROBE_PIN, OUTPUT);
  digitalWrite(RESET_PIN, LOW);
  digitalWrite(STROBE_PIN, HIGH);
}}

static inline float readBand(int analogPin) {{
  int v = analogRead(analogPin); // 0..1023
  float x = (float)v / 1023.0f;
  return clamp01(x);
}}

void loop() {{
  // Read 7 bands from both channels
  digitalWrite(RESET_PIN, HIGH);
  delayMicroseconds(5);
  digitalWrite(RESET_PIN, LOW);

  for (int i=0; i<7; i++) {{
    digitalWrite(STROBE_PIN, LOW);
    delayMicroseconds(30);
    float lv = readBand(LEFT_PIN);
    float rv = readBand(RIGHT_PIN);
    digitalWrite(STROBE_PIN, HIGH);

    // simple smoothing
    L[i] = (1.0f - {alpha}f)*L[i] + {alpha}f*lv;
    R[i] = (1.0f - {alpha}f)*R[i] + {alpha}f*rv;
  }}

  const float br = clamp01({br}f);
  const float gain = 0.8f + 0.3f*fminf(3.0f, (float){speed}f);

  // Draw 14 segments
  const int seg = {seg};
  for (int b=0; b<14; b++) {{
    bool isLeft = (b < 7);
    int i = isLeft ? b : (b-7);
    float amp = isLeft ? L[i] : R[i];
    amp = clamp01(amp * gain);

    uint8_t r,g,bcol;
    bandColor(i, isLeft, &r,&g,&bcol);

    int fill = (int)lroundf(amp * (float)seg);
    int base = b*seg;
    for (int k=0; k<seg; k++) {{
      int idx = base + k;
      if (idx >= NUM_LEDS) break;
      if (k < fill) {{
        leds[idx] = CRGB((uint8_t)(r*br), (uint8_t)(g*br), (uint8_t)(bcol*br));
      }} else {{
        leds[idx] = CRGB(0,0,0);
      }}
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_spectrum_bars_stereo():
    return register(BehaviorDef(
        "spectrum_bars_stereo",
        title="Spectrum Bars (Stereo)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
