from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","width"]

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color", (255,0,0))
    br = params.get("brightness", 1.0)
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.25)))

    base = _apply_brightness((int(col[0])&255, int(col[1])&255, int(col[2])&255), br)

    on_len = max(1, int(round(width * n)))
    if on_len > 6: on_len = 6
    gap_len = on_len
    period = on_len + gap_len

    pos = int((t * max(0.1, speed) * 12.0) % period)

    out: List[RGB] = []
    for i in range(n):
        k = (i + pos) % period
        out.append(base if k < on_len else (0,0,0))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,0,0))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.25))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.0: width = 0.0
    if width > 1.0: width = 1.0

    on_len = int(round(width * n))
    if on_len < 1: on_len = 1
    if on_len > 6: on_len = 6
    gap_len = on_len
    period = on_len + gap_len

    r = int(int(col[0]) * br) & 255
    g = int(int(col[1]) * br) & 255
    b = int(int(col[2]) * br) & 255

    step_ms = int(max(10.0, 120.0 / max(0.2, speed)))

    return f"""// Generated by Modulo (Effect: theater_chase)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

unsigned long lastStep = 0;
int pos = 0;

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  if (now - lastStep >= (unsigned long){step_ms}) {{
    lastStep = now;
    pos = (pos + 1) % {period};
  }}

  for (int i=0; i<NUM_LEDS; i++) {{
    int k = (i + pos) % {period};
    leds[i] = (k < {on_len}) ? CRGB({r},{g},{b}) : CRGB(0,0,0);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_theater_chase():
    return register(BehaviorDef(
        "theater_chase",
        title="Theater Chase",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
