from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","density","width"]

def _hash_u32(x: int) -> int:
    x = (x ^ 0x9E3779B9) & 0xFFFFFFFF
    x = (x * 0x85EBCA6B) & 0xFFFFFFFF
    x = (x ^ (x >> 13)) & 0xFFFFFFFF
    x = (x * 0xC2B2AE35) & 0xFFFFFFFF
    x = (x ^ (x >> 16)) & 0xFFFFFFFF
    return x

def _u01_from_hash(h: int) -> float:
    return float(h & 0xFFFFFF) / float(0x1000000)

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color", (255,255,255))
    br = params.get("brightness", 1.0)
    speed = float(params.get("speed", 1.0))
    density = _clamp01(float(params.get("density", 0.25)))
    width = _clamp01(float(params.get("width", 0.25)))
    if width < 0.05: width = 0.05

    base = _apply_brightness((int(col[0])&255, int(col[1])&255, int(col[2])&255), br)
    freq = max(0.1, speed) * 0.6

    out: List[RGB] = []
    for i in range(n):
        h = _hash_u32(i + 1)
        sel = _u01_from_hash(h)
        if sel > density:
            out.append((0,0,0))
            continue
        phase = _u01_from_hash(_hash_u32(h ^ 0xA5A5A5A5))
        u = (t * freq + phase) % 1.0
        if u >= width:
            out.append((0,0,0))
            continue
        a = 1.0 - (u / width)
        a = a*a
        out.append((int(base[0]*a)&255, int(base[1]*a)&255, int(base[2]*a)&255))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(255,255,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    density = float(params.get("density", 0.25))
    width = float(params.get("width", 0.25))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    r = int(int(col[0]) * br) & 255
    g = int(int(col[1]) * br) & 255
    b = int(int(col[2]) * br) & 255

    cycle_ms = int(max(120.0, min(5000.0, 2200.0 / max(0.2, speed))))
    tw_ms = int(max(20.0, float(cycle_ms) * width))

    return f"""// Generated by Modulo (Effect: twinkle)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01_from_hash(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float t01 = (float)(now % (unsigned long){cycle_ms}) / (float){cycle_ms};

  for (int i=0; i<NUM_LEDS; i++) {{
    uint32_t h = hash_u32((uint32_t)(i + 1));
    float sel = u01_from_hash(h);
    if (sel > (float){density}f) {{
      leds[i] = CRGB(0,0,0);
      continue;
    }}
    float phase = u01_from_hash(hash_u32(h ^ 0xA5A5A5A5u));
    float u = t01 + phase;
    u = u - floorf(u);
    float ms = u * (float){cycle_ms};
    if (ms >= (float){tw_ms}) {{
      leds[i] = CRGB(0,0,0);
      continue;
    }}
    float a = 1.0f - (ms / (float){tw_ms});
    a = a * a;
    leds[i] = CRGB((uint8_t)({r}f*a), (uint8_t)({g}f*a), (uint8_t)({b}f*a));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_twinkle():
    return register(BehaviorDef(
        "twinkle",
        title="Twinkle",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
