from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

USES = ['brightness', 'density', 'softness', 'speed', 'width']

from runtime.vortex_particles_core_v1 import vortex_particles_strip_v1

from runtime.shader_math_v1 import clamp01 as _clamp01, hash_u32 as _hash_u32, u01 as _u01, hsv_to_rgb as _hsv_to_rgb, add_rgb as _add, gauss as _gauss

def _preview_emit(
    *,
    num_leds: int,
    params: dict,
    t: float,
    state=None,
    layout=None,
    dt: float = 0.0,
    audio=None,
    **_kwargs,
) -> List[RGB]:
    # Accept the full Modulo preview_emit contract even though this effect is stateless.
    return vortex_particles_strip_v1(num_leds=num_leds, params=params, t=t)


def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    br = float(params.get("brightness", 1.0))
    speed = max(0.1, float(params.get("speed", 1.0)))
    density = float(params.get("density", 0.55))
    softness = float(params.get("softness", 0.45))
    width = float(params.get("width", 0.35))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if density < 0.0: density = 0.0
    if density > 1.0: density = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0

    pcount = 10 + int(round(density*50.0))
    sigma = 0.6 + softness*3.5
    strength = 0.25 + width*1.35
    period_ms = int(max(450.0, min(60000.0, 18000.0 / speed)))

    return f"""// Generated by Modulo (Effect: vortex_particles)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline uint32_t hash_u32(uint32_t x) {{
  x ^= 0x9E3779B9u;
  x *= 0x85EBCA6Bu;
  x ^= (x >> 13);
  x *= 0xC2B2AE35u;
  x ^= (x >> 16);
  return x;
}}

static inline float u01(uint32_t h) {{
  return (float)(h & 0xFFFFFFu) / 16777216.0f;
}}

static inline void hsv_to_rgb(float h, float s, float v, uint8_t* r, uint8_t* g, uint8_t* b) {{
  float hh = fmodf(h, 1.0f) * 6.0f;
  int i = (int)floorf(hh) % 6;
  float f = hh - (float)i;
  float p = v * (1.0f - s);
  float q = v * (1.0f - f * s);
  float t = v * (1.0f - (1.0f - f) * s);
  float rr,gg,bb;
  if (i==0) {{ rr=v; gg=t; bb=p; }}
  else if (i==1) {{ rr=q; gg=v; bb=p; }}
  else if (i==2) {{ rr=p; gg=v; bb=t; }}
  else if (i==3) {{ rr=p; gg=q; bb=v; }}
  else if (i==4) {{ rr=t; gg=p; bb=v; }}
  else {{ rr=v; gg=p; bb=q; }}
  *r = (uint8_t)(rr*255.0f);
  *g = (uint8_t)(gg*255.0f);
  *b = (uint8_t)(bb*255.0f);
}}

static inline float gauss(float d, float sigma) {{
  return expf(-(d*d) / (2.0f*sigma*sigma));
}}

static inline void add_rgb(uint8_t* r, uint8_t* g, uint8_t* b, float ar, float ag, float ab) {{
  float rr = fminf(255.0f, (float)(*r) + ar);
  float gg = fminf(255.0f, (float)(*g) + ag);
  float bb = fminf(255.0f, (float)(*b) + ab);
  *r = (uint8_t)rr; *g = (uint8_t)gg; *b = (uint8_t)bb;
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms};
  float t = phase;
  float br = clamp01((float){br}f);

  for (int i=0; i<NUM_LEDS; i++) leds[i] = CRGB(0,0,0);

  float sigma = (float){sigma}f;
  float strength = (float){strength}f;

  for (int pid=0; pid<{pcount}; pid++) {{
    uint32_t h = hash_u32((uint32_t)pid*991u);
    float x0 = u01(h);
    float p = t*(float){speed}f*0.22f + u01(hash_u32(h ^ 0x00001234u))*2.0f;
    float pull = (0.5f - x0);
    float x = x0 + strength*pull*sinf(2.0f*3.1415926f*p) + 0.08f*sinf(2.0f*3.1415926f*(p + x0*3.0f));
    x = clamp01(x);
    float idx = x * (float)(NUM_LEDS - 1);

    float hue = fmodf(p*0.12f + x*0.3f + 0.15f*u01(hash_u32(h ^ 0x0000BEEFu)), 1.0f);
    uint8_t pr,pg,pb;
    hsv_to_rgb(hue, 1.0f, 1.0f, &pr,&pg,&pb);

    float e = 0.55f + 0.45f*sinf(2.0f*3.1415926f*(p + (float)pid*0.07f));
    e = clamp01(e);

    for (int i=0; i<NUM_LEDS; i++) {{
      float d = fabsf((float)i - idx);
      float a = gauss(d, sigma) * e;
      if (a < 0.002f) continue;
      float k = br * a;
      add_rgb(&leds[i].r, &leds[i].g, &leds[i].b, (float)pr*k, (float)pg*k, (float)pb*k);
    }}
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_vortex_particles():
    return register(BehaviorDef(
        "vortex_particles",
        title="Vortex Field + Particles",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
