from __future__ import annotations
SHIPPED = True

from typing import List, Tuple
import math

from behaviors.registry import BehaviorDef, register

RGB = Tuple[int,int,int]

def _clamp01(x: float) -> float:
    if x < 0.0: return 0.0
    if x > 1.0: return 1.0
    return x

def _apply_brightness(rgb: RGB, br: float) -> RGB:
    br = _clamp01(float(br))
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

USES = ["color","brightness","speed","width","softness"]

def _shape(s: float, softness: float) -> float:
    # s in [0,1]; shape with exponent (softness low => sharper)
    exp = 0.8 + (1.0 - _clamp01(softness)) * 3.0
    return pow(s, exp)

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    col = params.get("color",(0,140,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = _clamp01(float(params.get("width", 0.35)))       # wavelength relative (bigger = slower spatial change)
    softness = _clamp01(float(params.get("softness", 0.6)))  # shape
    if width < 0.05: width = 0.05

    base = (int(col[0])&255, int(col[1])&255, int(col[2])&255)

    # spatial frequency: smaller width => more cycles along strip
    cycles = (1.0 / width) * 0.6
    phase = t * max(0.1, speed) * 1.0

    out: List[RGB] = []
    for i in range(n):
        x = i / max(1.0, (n-1))
        v = 0.5 + 0.5*math.sin(2.0*math.pi*(cycles*x + phase))
        v = _shape(v, softness)
        out.append(_apply_brightness(base, br * v))
    return out

def _arduino_emit(*, layout: dict, params: dict) -> str:
    n = int(layout["num_leds"])
    pin = int(layout["led_pin"])
    col = params.get("color",(0,140,255))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))
    width = float(params.get("width", 0.35))
    softness = float(params.get("softness", 0.6))

    if br < 0.0: br = 0.0
    if br > 1.0: br = 1.0
    if width < 0.05: width = 0.05
    if width > 1.0: width = 1.0
    if softness < 0.0: softness = 0.0
    if softness > 1.0: softness = 1.0

    r0 = int(col[0]) & 255
    g0 = int(col[1]) & 255
    b0 = int(col[2]) & 255

    cycles = (1.0 / width) * 0.6
    period_ms = int(max(200.0, min(20000.0, 3000.0 / max(0.2, speed))))

    return f"""// Generated by Modulo (Effect: wave)
#include <FastLED.h>
#include <math.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

static inline float clamp01(float x) {{
  if (x < 0.0f) return 0.0f;
  if (x > 1.0f) return 1.0f;
  return x;
}}

static inline float shape(float s, float softness) {{
  float exp = 0.8f + (1.0f - clamp01(softness)) * 3.0f;
  return powf(s, exp);
}}

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
}}

void loop() {{
  unsigned long now = millis();
  float phase = (float)(now % (unsigned long){period_ms}) / (float){period_ms}; // 0..1
  float br = clamp01((float){br}f);
  float cycles = (float){cycles}f;
  float softness = clamp01((float){softness}f);

  for (int i=0; i<NUM_LEDS; i++) {{
    float x = (NUM_LEDS <= 1) ? 0.0f : ((float)i / (float)(NUM_LEDS - 1));
    float v = 0.5f + 0.5f * sinf(2.0f * 3.1415926f * (cycles*x + phase));
    v = shape(v, softness);
    float a = br * v;
    leds[i] = CRGB((uint8_t)((float){r0}f*a), (uint8_t)((float){g0}f*a), (uint8_t)((float){b0}f*a));
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_wave():
    return register(BehaviorDef(
        "wave",
        title="Wave (Sine)",
        uses=USES,
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
