from __future__ import annotations

from core.surface_compat import canonical_surface_config
SHIPPED = True

from typing import List, Tuple

from behaviors.registry import BehaviorDef, register
from behaviors.effects._export_hw import resolve_data_pin

RGB = Tuple[int,int,int]

def _apply_brightness(rgb, br: float):
    try: br = float(br)
    except Exception: br = 1.0
    br = 0.0 if br < 0 else (1.0 if br > 1.0 else br)
    r,g,b = rgb
    return (int(r*br)&255, int(g*br)&255, int(b*br)&255)

def _preview_emit(*, num_leds: int, params: dict, t: float) -> List[RGB]:
    n = max(1, int(num_leds))
    c = params.get("color", (255,0,0))
    br = params.get("brightness", 1.0)
    speed = float(params.get("speed", 1.0))
    # progress loops 0..1
    prog = (t * speed * 0.2) % 1.0  # friendly scale
    filled = int(prog * n)

    on = _apply_brightness((int(c[0])&255, int(c[1])&255, int(c[2])&255), br)
    off = (0,0,0)
    out = [off]*n
    for i in range(filled):
        out[i] = on
    return out

def _arduino_emit(*, surface: dict | None = None, layout: dict | None = None, params: dict) -> str:
    surface = surface if surface is not None else layout
    surface_cfg = canonical_surface_config(surface)
    n = int(surface_cfg["count"])
    pin = resolve_data_pin(surface_cfg)
    c = params.get("color",(255,0,0))
    br = float(params.get("brightness", 1.0))
    speed = float(params.get("speed", 1.0))

    br = 0.0 if br < 0 else (1.0 if br > 1.0 else br)
    r = int(int(c[0]) * br) & 255
    g = int(int(c[1]) * br) & 255
    b = int(int(c[2]) * br) & 255

    # ms per full wipe (speed 0..10 => slower..faster)
    full_ms = int(max(300.0, 4000.0 / max(0.2, speed)))

    return f"""// Generated by Modulo (Phase 3E: Wipe)
#include <FastLED.h>

#define NUM_LEDS {n}
#define LED_PIN {pin}
CRGB leds[NUM_LEDS];

unsigned long startMs = 0;

void setup() {{
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(255);
  startMs = millis();
}}

void loop() {{
  unsigned long now = millis();
  unsigned long dt = now - startMs;
  unsigned long t = dt % (unsigned long){full_ms};
  float prog = (float)t / (float){full_ms}; // 0..1

  int filled = (int)(prog * (float)NUM_LEDS);

  for (int i=0; i<NUM_LEDS; i++) {{
    leds[i] = (i < filled) ? CRGB({r},{g},{b}) : CRGB(0,0,0);
  }}

  FastLED.show();
  delay(1);
}}
"""

def register_wipe():
    return register(BehaviorDef(
        "wipe",
        title="Wipe",
        uses=["color","brightness","speed"],
        preview_emit=_preview_emit,
        arduino_emit=_arduino_emit,
    ))
